project:
  type: book 

book: 
  title: "Prediction, Inference, and Causality" 
  author: "David A. Hirshberg" 
  image: shared-assets/images/example-plot.svg
  chapters: 
    - index.qmd
    - lectures/Lecture1.qmd
    - lectures/Lab1.qmd
    - homework/week0-homework.qmd
    - lectures/Lecture2.qmd
    - lectures/Lecture3.qmd
    - references.qmd

format: 
  live-html:
    code-annotations: hover
    filters: 
      - homework/custom-callout.lua
    css:
      - homework/homework.css
    callout-appearance: simple
    callout-icon: false
    highlight-style: haddock
    df-print: paged
    embed-resources: false
    fig-format: svg
    html-math-method: mathjax
    include-in-header: 
      text: |
        <script>
          window.MathJax = {
            options : {
              menuOptions: {
                settings: {
                  assistiveMml: false,
                  collapsible: false,  
                  explorer: false    
                }
              }
            },
            loader: {load: ['[tex]/physics', '[tex]/unicode']},
            tex: {packages: {'[+]': ['physics', 'unicode']}}
          }
        </script>
        
knitr:
  opts_chunk:
    dev: svglite
    dev.args:
      bg: transparent
webr:
  cell-options:
    autorun: true
    fig-width: 14
  packages:
    - "ggplot2"
    - "purrr"
    - "dplyr"
    - "tidyr"

execute: 
  echo: false
  message: false
  warning: false