project:
  type: book 

book: 
  title: "Prediction, Inference, and Causality" 
  author: "David A. Hirshberg" 
  cover-image: shared-assets/images/example-plot.svg
  chapters:
    - index.qmd
    - lectures/Lecture1-prose.qmd
    - lectures/Lab1-prose.qmd
    - homework/week0-homework.qmd
    - lectures/Lecture2-prose.qmd
    - lectures/Lab2.qmd
    - homework/week1-homework.qmd
    - lectures/Lecture3.qmd
    - lectures/Lab3.qmd
    - homework/week2-homework.qmd
    - lectures/Lecture4.qmd
    - lectures/Lecture5.qmd
    - lectures/Lab4.qmd
    - homework/week3-homework.qmd
    - lectures/Lecture6.qmd
    - exams/practice-midterm-1.qmd
    - lectures/Lecture7.qmd
    - lectures/Lecture8.qmd
    - lectures/Lab5.qmd
    - lectures/Lecture9.qmd
    - lectures/Lab6.qmd
    - homework/week5-homework.qmd
    - lectures/Lecture12.qmd
    - lectures/Lecture13.qmd
    - lectures/Lab7.qmd
    - lectures/Lecture14.qmd
    - homework/week7-homework.qmd
    - exams/practice-midterm-2.qmd
    - lectures/Lecture15.qmd
    - lectures/Lecture16.qmd
    - homework/week9-homework.qmd
    - exams/practice-final.qmd
    - references.qmd

format: 
  live-html:
    theme: [default, "class.scss"]
    code-annotations: hover
    number-depth: 1
    filters: 
      - homework/custom-callout.lua
    callout-appearance: simple
    callout-icon: false
    highlight-style: haddock
    df-print: paged
    embed-resources: false
    fig-format: svg
    html-math-method: mathjax
    favicon: assets/favicon.ico
    include-in-header: 
      text: |
        <script>
          window.MathJax = {
            options : {
              menuOptions: {
                settings: {
                  assistiveMml: false,
                  collapsible: false,  
                  explorer: false    
                }
              }
            },
            loader: {load: ['[tex]/physics', '[tex]/unicode']},
            tex: {packages: {'[+]': ['physics', 'unicode']}}
          }
        </script>
        
knitr:
  opts_chunk:
    dev: svglite
    dev.args:
      bg: transparent
webr:
  cell-options:
    autorun: true
    fig-retina: true
  packages:
    - "ggplot2"
    - "purrr"
    - "dplyr"
    - "tidyr"

execute: 
  echo: false
  message: false
  warning: false