```{r}
#| label: ga-turnout-setup
#| include: false 
library(tidyverse)
```

```{r}
#| label: ga-maps
#| cache: true

# The county info is from https://en.wikipedia.org/wiki/List_of_counties_in_Georgia
# and has been converted to csv using https://wikitable2csv.ggor.de
to.number = function(s) { as.numeric(str_trim(gsub(",", "", s))) }
ga_county_info = read.csv('data/georgia_county_info.csv') |>
  mutate(subregion = tolower(sub(' County', '', County))) |>
  mutate(pop =  to.number(Population)) |>
  mutate(area = to.number(sub('sq.*', '', Area))) 

counties = map_data('county', region='georgia')
ga_county = counties |>
  filter(region == "georgia")
ga_county = left_join(ga_county, ga_county_info, by=c('subregion'='subregion'))
ga_county$subregion = gsub("de kalb", "dekalb", ga_county$subregion)

# Create fake locations for the people in our population
# by taking random convex combinations of county vertices
# To reduce computation, we'll have 10K locations + jitter
sample.within.subregion = function(subregions, seed=1) {
  output = data.frame(subregion=subregions, lat=NA, long=NA)
  for(subregion in unique(subregions)) { 
      vertices = ga_county[ga_county$subregion==subregion, c('lat','long')]
      U = sum(subregions==subregion)
      V = nrow(vertices)
      weights = abs(rt(U*V, 1))
      dim(weights) = c(U,V)
      weights = (1/rowSums(weights)) * weights
      output[subregions==subregion, c('lat', 'long')] = 
                 cbind(weights %*% vertices$lat, weights %*% vertices$long)
    }
    output
}

L = 10000
county = sample(ga_county_info$subregion, size=L, replace=T, prob=ga_county_info$pop)
base.locations = sample.within.subregion(county)
```

```{r}
#| label: make-state-maps
# Make maps of California with and without population density shown

state.plot = ggplot(data=ga_county, mapping=aes(x=long, y=lat, group=group)) + 
  coord_quickmap() +
  geom_polygon(fill='gray', color = "white", alpha=.4) +
      scale_fill_gradient(trans="log10") + 
      theme_void()

state.pop.plot = ggplot(data=ga_county, mapping=aes(x=long, y=lat, group=group)) + 
  coord_quickmap() +
  geom_polygon(aes(fill = pop/area), color = "white") +
      scale_fill_gradient(trans="log10") + 
      theme_void()
```

```{r}
#| label: ga-population
set.seed(4)
m = 7233584
n = 625

b0 = floor(.7*m)
b1 = ceiling(.3*m)
y0 = rbinom(n=b0,size=1,prob=.68)
y1 = rbinom(n=b1,size=1,prob=.74)
pop = data.frame(y=c(y0,y1), x=c(rep(0,b0),rep(1,b1)))
pop = pop[sample(1:m),] # shuffle the rows

x = pop$x
y = pop$y
```

```{r}
#| label: ga-population-xy
# Create fake locations for the people in our population
base.ind = 1 + ( (0:(m-1)) %% L )
locations = base.locations[base.ind,]
pop$lat  = locations$lat  + rnorm(m, sd=.01)
pop$long = locations$long + rnorm(m, sd=.01)
pop$group = 1 # for ggplot mapping
```

```{r}
#| label: ga-sample
# Generate Sample Data for us (J1) and three friends (J2,J3,JM)
set.seed(0)
J1 = sample(1:m,size=n,replace=T)
J2 = sample(1:m,size=n,replace=T)
J3 = sample(1:m,size=n,replace=T)
JM = sample(1:m,size=n,replace=T)

J = J1
sam = pop[J,]
```


```{r}
#| label: plot-ga-sample-and-population

# Now we'll plot the sample and the population on the map.
# Probably in the future this should be done in the lecture file,
# as we may want them colored differently lecture by lecture.

sample.plot = state.plot + geom_point(aes(x=long, y=lat), data=sam, size=.2, alpha=.5)
sample.plot.inf = state.pop.plot + geom_point(aes(x=long, y=lat), data=sam, size=.2, alpha=.5)
pop.plot    = state.plot + geom_point(aes(x=long, y=lat), data=pop[1:L, ], size=.02, alpha=.1) 
pop.plot.inf = state.pop.plot + geom_point(aes(x=long, y=lat), data=pop[1:L, ], size=.01, alpha=.1)  
```

```{r}
#| label: old-names
dfsam = sam
X = sam$x
Y = sam$y

dfpop = pop
x = pop$x
y = pop$y
```

```{r}
#| label: last-ga-turnout-chunk
```