---
title: "Lab 6"
subtitle: "Least Squares in **R**"
resources:
  - data
webr:
  resources:
    - data/ca-income-pop.csv
---


## Setup 


```{=html}
<style>
.reveal { background: #ffffff; }
</style>
```
{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}
{{< include shared-code.qmd >}}
{{< include ca-income.qmd >}}

::: {.panel-tabset}
### Loading the Data and Sampling
```{webr}
#| autorun: true
ca.pop = read.csv('data/ca-income-pop.csv')
pop = data.frame(w=(ca.pop$sex=='female') + 0, x=ca.pop$education, y=ca.pop$income)
m = nrow(pop)

set.seed(1)
n = 2000
J = sample(1:m, n, replace=TRUE)
sam = pop[J,]
```

### Plotting Code 

```{webr}
#| autorun: true
library(ggplot2)
library(scales) 

scale_y = function(limits=c(0, 2e5), breaks=seq(0, max(limits), by=25e3), ...) { 
  list(scale_y_continuous(breaks=breaks, 
                          labels=label_dollar(scale=1e-3, suffix='k'), ...), 
       coord_cartesian(ylim=limits))
}
years = 8:20
scale_x = function(limits=c(min(years)-.5, max(years)+.5)) { 
  scale_x_continuous(breaks=years, labels=sprintf('%dy', years), limits=limits)
}

dot.size = 2
plotX = function(w,x, shift=.15) { x + shift*(2*w-1) }
mean_sd = function(x) { 
  data.frame(y=mean(x), ymin=mean(x)-sd(x), ymax=mean(x)+sd(x))
}

scatter.plot = function(sam, alpha=rep(.2, nrow(sam)), dot.size=1) {
  ggplot(sam) + geom_point(aes(x=plotX(w,x), y=y, color=factor(w), alpha=I(alpha)), 
    position=position_jitter(width=.15, seed=1), size=dot.size) + 
    stat_summary(aes(x=plotX(w,x), y=y, fill=factor(w)), 
      fun.data=mean_sd, geom='pointrange', alpha=.3, shape=21) + 
    scale_x() + scale_y() + guides(color='none', fill='none')
}

red   = rgb(248,118,109, maxColorValue=255)
green = rgb(0,191,196,   maxColorValue=255)
scatter.plot.uni = function(sam, color=green, dot.size=1, alpha=.2) {
  ggplot(sam) + geom_point(aes(x=x, y=y), color=color, alpha=.2,   
    position=position_jitter(width=.15, seed=1), size=dot.size) + 
    stat_summary(aes(x=x, y=y), fill=color, fun.data=mean_sd, geom='pointrange', alpha=.3, shape=21) + 
    scale_x() + scale_y() + guides(color='none', fill='none')
}

x = seq(min(pop$x), max(pop$x), length.out=1000)
grid = expand.grid(x=x, w=c(0, 1))
```

### Styling


```{webr}
#| label: ggplot-theme
#| autorun: true
lightgray = "#bbbbbb"
gridcolor = rgb(0,0,0,.1, maxColorValue=1)

lab.theme = theme(
        plot.background = element_rect(fill = "transparent", colour = NA),
        panel.background = element_rect(fill = "transparent", colour = NA),
                    legend.background = element_rect(fill="transparent", colour = NA),
                    legend.box.background = element_rect(fill="transparent", colour = NA),
                    legend.key = element_rect(fill="transparent", colour = NA),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x  = element_text(colour = lightgray),
        axis.text.y  = element_text(colour = lightgray),
        axis.title.x  = element_blank(),
        axis.title.y  = element_blank(),
        panel.grid.major=element_line(colour=gridcolor),
        panel.grid.minor=element_line(colour=gridcolor, linewidth=0.25))

theme_set(lab.theme)
set.seed(1)
```

:::

## Least Squares in Linear Models

::: {.panel-tabset}
### Sample
```{webr}
#| autorun: true
scatter.plot(sam)
```

### Population
```{webr}
#| autorun: true
scatter.plot(pop, dot.size=.1)
```
:::

::: {.panel-tabset}
### Least Squares 
- The estimation targets we've talked about are all summaries of column means *in the population*.

$$
\begin{aligned}
\mu(w,x) 
&= \frac{1}{m_{w,x}}\sum_{j:w_j=w,x_j=x} y_j \qfor m_{w,x} = \sum_{j: w_j=w, x_j=x} 1 \\
&= \E[Y_i \mid W_i=w, X_i=x] \qfor (W_i,X_i,Y_i) \qqtext{sampled uniformly-at-random}
\end{aligned}
$$

- Least Squares Regression is a method for *choosing a function* to estimate these column means. 
  - When we choose from the set of *all functions* of $(w,x)$ ... 
  - ... we get the mean in the corresponding column of the sample.

$$
\begin{aligned}
\hat\mu(w,x) 
&= \argmin_{m \in \model} \sum_{i=1}^n \qty{Y_i - m(W_i,X_i)}^2 \\
&= \frac{1}{N_{w,x}}\sum_{i:W_i=w,X_i=x} Y_i \qqtext{ when } \model = \{ \text{all functions of } (w,x) \}
\end{aligned}
$$

### Linear Models 
- The set of functions we choose from is our **model**. 
  - Or **regression model** if we want to be verbose. 
  - And there are, of course, many other models. 
- When we don't have a lot of data in some columns in the sample ... 
  - Column means are really sensitive to who we happened to sample. 
  - And we're probably better off using a smaller model, i.e., one that includes fewer functions.
- The models we'll focus on in this class are linear models. 
  - They're closed under *addition*, *subtraction*, and *scalar multiplication*. 
  - That means when you add, subtract, or scale any functions in the model ...
  - ... you get another function in the model.

:::

# Least Squares with Univariate Data 

## Models 
```{webr}
#| autorun: true
unisam = sam[sam$w==1,]
fitted.model = lm(y ~ 1+x, data=unisam)
muhat = function(x) { predict(fitted.model, newdata=data.frame(x=x)) }

scatter.plot.uni(unisam) +
  geom_line(aes(x=x, y=muhat(x)), color=green)
```

::: {.panel-tabset}
### Models 
$$
\begin{aligned}
\model &= \{ \text{all functions } \  m(x) \}  && \text{all functions} \\
\model &= \{ \text{all functions } \ m(c(x)) \} && \text{all functions of $c(x)$, a coarsened version of $x$} \\
\model &= \{ m(x) = a + bx \ : \ a,b \in \mathbb{R} \} && \text{all lines} 
\end{aligned}
$$

- We use **R**'s built-in function `lm`^['lm' stands for 'linear model'] to do least squares with linear models.
- To tell it which model to use, we use what **R** calls a 'formula'.
  - What a formula does is describe a *basis* for the model. 
  - i.e. a set of functions that we can *take linear combinations of* to get any function in the model.
$$
\begin{aligned}
\model &= \{ m(x) = a_0 b_0(x) + a_1 b_1(x) + \ldots + a_k b_k(x) \ \ : \ a_0 \ldots a_k \in \mathbb{R} \} \\ 
& \qif b_0(x),b_1(x),\ldots,b_k(x) \ \text{ is a basis for } \ \mathcal{M}. 
\end{aligned}
$$

### The Example Above 
- Where it says `lm(y~1+x, data=unisam)` above, `y~1+x` is the formula and `unisam` is the data.
  - It's saying that we want to choose a function $m$ from our model for which $m(X_i) \approx Y_i$ ...
  - ... where $(X_i,Y_i)$ are `unisam$x[i]` and `unisam$y[i]` for $i=1 \ldots n$.
  - And our model is the set of all linear combinations of the functions $b_0(x) = 1$ and $b_1(x) = x$. 
$$
\hat \mu = \argmin_{m \in \model} \sum_{i=1}^n \qty{Y_i - m(X_i)}^2 \qfor 
\model = \{m(x) = a_0 \ 1 + a_1 \ x \ \ : \ \  a_0,a_1 \in \mathbb{R} \}
$$

### Using `predict` 

- What `lm` gives you is not really the function $\hat\mu$. 
  - It's something else. But whatever it is, you can calculate $\hat\mu(x)$ by calling `predict`.
  - The code below uses `predict` to calculate $\hat\mu(8)$, $\hat\mu(10)$, and $\hat\mu(12)$. 

```{webr}
#| autorun: true
x3 = c(8,10,12)
predict(fitted.model, newdata=data.frame(x=x3))
```

- I like to write a function `muhat` that calls `predict` on its argument.
  - This makes the code shorter and more like the mathematical notation. 

```{webr}
#| autorun: true
muhat = function(x) { predict(fitted.model, newdata=data.frame(x=x)) }
muhat(x3)
```

### How `lm` and `predict` work (optional reading) 

- If you're familiar with object oriented programming ...
  - `lm` returns an object we call `fitted.model`. 
  - `predict` is one of its *methods*.
- Method calls in *R* look a little different than they do in *Python*, *C++*, or *Java*.  
  - But they work pretty much the same way. Almost.
  - *R*, like *Common Lisp* and *Julia*, has an object system based on [multimethods](https://en.wikipedia.org/wiki/Multiple_dispatch).

::: 

## Formulas in Abstract 

```{webr}
#| autorun: true
b.0 = function(x) { array(1, dim=length(x)) }
b.1 = function(x) { x }
b.2 = function(x) { x^2 }
model = lm(y ~ b.0(x) + b.1(x), data=unisam)
muhat = function(x) { predict(model, newdata=data.frame(x=x)) }

scatter.plot.uni(unisam) +
  geom_line(aes(x=x, y=muhat(x)), color=green)
```

::: {.panel-tabset}
### A General Formula

- You can use any **R** functions you like in a formula.
  - Above, I've implemented my own functions `b.0` and `b.1` to use as my basis. 
  - You can also use **R**'s built-in functions. Try replacing `b.1` in the formula with `sin`. 
- You can use as many basis functions as you like. 
  - Try adding `b.2(x)` to the formula `y ~ b.0(x) + b.1(x)` above.

### Typing Less 

- You don't really have to define all these functions. 
  - $1$ and $x$ will do in place of `b.0(x)` and `b.1(x)`.
- But `x^2` won't do in place of `b.2(x)`. 
   - It's because squaring means something special in formulas. 
   - But you can work around this by writing `I(x^2)` instead.  
   - In short, wrapping an expression in `I` says 'interpret this the normal way.'
- Try writing out a formula that does the same thing as `y ~ b.0(x) + b.1(x) + b.2(x)` ...
  - ... but without using `b.0`, `b.1`, or `b.2`. 
  
### A Quirk

- **R** implicitly adds the constant function $b_0(x)=1$ to every basis you give it.
  - Go ahead and get rid of `b.0(x)` in the formula `y~b.0(x)+b.1(x)` above. 
  - Does anything change in the plot?
- If you want to stop it from doing this, you can write `y ~ 0 + b.1(x)` instead. 
  - What changes in the plot? Why?

:::

## The All-Functions Model


## Piecewise-Constant Models 


## Least Squares with Multivariate Data

```{webr}
#| autorun: true
model = lm(y ~ 1 + w, data=sam)
muhat = function(w, x) { predict(model, newdata=data.frame(w=w, x=x)) } 

grid = expand.grid(w=c(0,1), x=x)
scatter.plot(sam) +
  geom_line(aes(x=grid$x, y=muhat(grid$w, grid$x), color=factor(grid$w))) 
```