---
title: "Lab 7"
subtitle: "Misspecification and Averaging"
resources:
  - data
webr:
  resources:
    - data/ca-income.csv
---


## Setup

```{=html}
<style>
.reveal { background: #ffffff; }
</style>
```
{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}

### Shared Between Examples

::: {.panel-tabset}
###
### Libraries 
```{webr}
#| autorun: true
#| warning: false

library(dplyr)
library(tidyr)
library(purrr)
library(ggplot2)

mean_sd = function(x, mult = 1) { 
  mean_se(x, mult = mult*sqrt(length(stats::na.omit(x)))) 
}
```
### Styling

```{webr}
#| autorun: true
groupa   = rgb(248,118,109, maxColorValue=255)
groupb   = rgb(0,191,196,   maxColorValue=255)
```

```{r}
#| autorun: true

# These are the HTML entities for shapes we use in the text. 
# This lets us write `r circle` instead of &#9679; when we want a circle.
triangle =  '&#9652;'
circle = '&#9679;'
pointrange = '&#9087;'
diamond = '&#9671;'
```

### Defaults

```{webr}
#| autorun: true
default.replications = 1000
default.color = groupb
```

```{webr}
#| autorun: true
lightgray = "#bbbbbb"
gridcolor = rgb(0,0,0,.1, maxColorValue=1)

lab.theme = theme(
        plot.background = element_rect(fill = "transparent", colour = NA),
        panel.background = element_rect(fill = "transparent", colour = NA),
                    legend.background = element_rect(fill="transparent", colour = NA),
                    legend.box.background = element_rect(fill="transparent", colour = NA),
                    legend.key = element_rect(fill="transparent", colour = NA),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x  = element_text(colour = lightgray),
        axis.text.y  = element_text(colour = lightgray),
        axis.title.x  = element_blank(),
        axis.title.y  = element_blank(),
        panel.grid.major=element_line(colour=gridcolor),
        panel.grid.minor=element_line(colour=gridcolor, linewidth=0.25))

theme_set(lab.theme)
```

```{webr}
#| label: define-colors
twocolor.red   = rgb(248,118,109, maxColorValue=255)
twocolor.green = rgb(0,191,196,   maxColorValue=255)
groupa = twocolor.red
groupb = twocolor.green

pink     = '#ef476f'  # rgb(239,71,111)
mustard  = '#ffd166'  # rgb(255,209,102)
green    = '#06d6a0'  # rgb(6, 214,160)
teal     = '#118ab2'  # rgb(17,138,178)
midnight = '#073b4c'  # rgb(7,59,76)
# fwiw, col2rgb is a function that converts a color to its RGB values

map.background = green
polla  = midnight
pollb  = pink
pollc  = teal
polld  = green
polle  = mustard
# THESE COLORS ARE DEFINED IN class.scss, TOO. IF YOU CHANGE THEM HERE, CHANGE THEM THERE.
```

::: hidden

$$
\DeclareMathOperator{\E}{E}
\DeclareMathOperator{\V}{V}
\DeclareMathOperator{\Var}{\V}
\DeclareMathOperator{\sd}{sd}
\DeclareMathOperator{\Cov}{Cov}
\DeclareMathOperator*{\argmin}{argmin}
\newcommand{\ind}[1]{1_{\{#1\}}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\model}{\mathcal{M}}

\newcommand{\lcb}[1]{\color{gray}\left\{ \color{black} #1 \color{gray} \right\} \color{black}}
\newcommand{\pcb}[1]{\color[RGB]{239,71,111}\left\{ \color{black} #1 \color[RGB]{239,71,111} \right\} \color{black}}
\newcommand{\tcb}[1]{\color[RGB]{17,138,178}\left\{ \color{black} #1 \color[RGB]{17,138,178} \right\} \color{black}}

\newcommand{\mapbg}{\color[RGB]{6,214,160}}
\newcommand{\polla}{\color[RGB]{7,59,76}}
\newcommand{\pollb}{\color[RGB]{239,71,111}}
\newcommand{\pollc}{\color[RGB]{17,138,178}}
\newcommand{\polld}{\color[RGB]{6,214,160}}
\newcommand{\polle}{\color[RGB]{255,209,102}}
\newcommand{\groupa}{\color[RGB]{248,118,109}}
\newcommand{\groupb}{\color[RGB]{0,191,196}}
\newcommand{\faded}{\color[RGB]{64,64,64}}

\newcommand{\inmapbg}[1]{\textcolor[RGB]{6,214,160}{#1}}
\newcommand{\inpolla}[1]{\textcolor[RGB]{7,59,76}{#1}}
\newcommand{\inpollb}[1]{\textcolor[RGB]{239,71,111}{#1}}
\newcommand{\inpollc}[1]{\textcolor[RGB]{17,138,178}{#1}}
\newcommand{\inpolld}[1]{\textcolor[RGB]{6,214,160}{#1}}
\newcommand{\inpolle}[1]{\textcolor[RGB]{255,209,102}{#1}}
\newcommand{\ingroupa}[1]{\textcolor[RGB]{248,118,109}{#1}}
\newcommand{\ingroupb}[1]{\textcolor[RGB]{0,191,196}{#1}}

\newcommand{\inred}[1]{\ingroupa{#1}}
\newcommand{\ingreen}[1]{\ingroupb{#1}}
\newcommand{\inblue}[1]{\textcolor[RGB]{0,0,255}{#1}}
\newcommand{\inmidnight}[1]{\inpolla{#1}}
\newcommand{\inpink}[1]{\inpollb{#1}}
\newcommand{\inteal}[1]{\inpollc{#1}}
\newcommand{\inpurple}[1]{\textcolor[RGB]{160,32,240}{#1}}

\newcommand{\alert}[1]{\textcolor[RGB]{128,128,128}{#1}}
\newcommand{\faint}[1]{\textcolor[RGB]{128,128,128}{#1}}
\newcommand{\veryfaint}[1]{\textcolor[RGB]{192,192,192}{#1}}

\newcommand{\with}{\ingroupb{\text{degree}}}
\newcommand{\without}{\ingroupa{\text{no degree}}}

\newcommand{\explain}[2]{\overset{\texttip{\small{\unicode{x2753}}}{#2}}{#1}}
\newcommand{\mathexplain}[2]{\overset{\mathtip{\small{\unicode{x2753}}}{#2}}{#1}}

\newcommand{\wone}{\overset{\veryfaint{w}}{1}}
\newcommand{\wzero}{\overset{\veryfaint{w}}{0}}
\newcommand{\xone}{\overset{\veryfaint{x}}{1}}
\newcommand{\xzero}{\overset{\veryfaint{x}}{0}}

$$

:::

:::

### Gym Subsidy Example 

::: {.panel-tabset}

###


### Load Data

```{webr}
#| envir: gym
#| autorun: true 

set.seed(3)

m=10000
is.blue = rbinom(m,1, 1/2)
Yblue   = rbinom(m, 30, 1/4) 
Ygreen0 = rbinom(m, 30, 1/10)
Ygreen50 = rbinom(m, 30, 1/5)

Y0   = ifelse(is.blue, Yblue, Ygreen0)
Y50  = ifelse(is.blue, Yblue, Ygreen50)
Y100 = Y50   ### <--- this tells us we've got no effect.

# Randomizing by rolling two dice. R is their sum
R = sample(c(1:6), size=m, replace=TRUE) + sample(c(1:6), size=m, replace=TRUE)
W = case_match(R,
  1:6~0,
  7:10~50,
  11:12~100)
Y = case_match(W,
  0~Y0,
  50~Y50,
  100~Y100)

pop = data.frame(x=W, y=Y)

pop.model = lm(y~factor(x), data=pop)
mu = function(x) { predict(pop.model, newdata=data.frame(x=x)) }

n = 200
J = sample(1:n, n, replace=TRUE)
sam = pop[J,]
```

### Scatter Plot

```{webr}
#| envir: gym
#| autorun: true 

proportion.scale = 10 
gridx = seq(-30,130, length.out=1000)
uniquex = unique(pop$x)
lsq.plot = function(sam, formula, 
  dot.size=1, dot.alpha=.2, color=default.color, jitter.width=10, mu.alpha=1) { 
  
  base.plot = ggplot(sam) 
  if(mu.alpha > 0) { 
    base.plot = base.plot + 
      geom_point(aes(x=x, y=mu(x)), 
        data=data.frame(x=uniquex),
        color='green', alpha=mu.alpha, shape='square', size=3*dot.size) +
      geom_line(aes(x=x, y=mu(x)), 
        data=data.frame(x=uniquex),
        color='green', alpha=mu.alpha/2, linetype='solid') 
  }
  base.plot = base.plot + 
      geom_point(aes(x=x,y=y), 
        position=position_jitter(seed=0, width=jitter.width),
      alpha=dot.alpha, size=dot.size, color=color) +
    stat_summary(aes(x=x, y=y),
      fun.data=mean_sd, geom='pointrange', 
      shape=21, alpha=.5, fill=color, color='black') + 
      geom_bar(aes(x=x, y=proportion.scale*after_stat(prop)), 
        alpha=.1, linewidth=.05, fill=color, width=jitter.width*2) +
      guides(color='none', fill='none') 
    
    if(is.null(formula)) { base.plot } else {
        model = lm(formula, data=sam)
        muhat = function(x) predict(model, newdata=data.frame(x=x))   
        base.plot + 
          geom_line(aes(x=x, y=muhat(x)), 
            data = data.frame(x=gridx), 
            color=color, alpha=.7, linetype='dotted') + 
          geom_point(aes(x=x, y=muhat(x)), 
            fill=color, color='black', alpha=.5, shape=23) 
    }
}
```

### Sampling Distribution Plots 

```{webr}
#| envir: gym
#| autorun: true 

plot.sampling.distribution = function(pop, formula, target, n=nrow(sam), replications=default.replications) { 
    estimates = 1:replications |> map_vec(function(rep) { 
      J = sample(1:nrow(pop), size=n, replace=TRUE)
      sam = pop[J,]

      fitted.model = lm(formula, data=sam) 
      muhat = function(x) { predict(fitted.model, newdata=data.frame(x=x)) } 
      target(muhat, sam)
    })
    the.target = target(mu, pop)
    ggplot() + 
     geom_vline(xintercept = the.target, color='green', linewidth=2, alpha=.5) +
     geom_vline(xintercept = mean(estimates), color='blue', linewidth=.75, alpha=.9) +
     geom_histogram(aes(x=estimates, y=after_stat(density)), bins=50, alpha=.2)
}
```

:::

### California Income Data 

::: {.panel-tabset}
### 

### Load Data 

```{webr}
#| envir: ca 
#| autorun: true 

ca = read.csv('data/ca-income.csv')
sam = data.frame(
  w = ca$sex == 'female',
  x = ca$education,
  y = ca$income)
```

```{webr}
#| envir: ca 
#| autorun: true 

n = nrow(sam)
m = n*10

set.seed(1)
I = sample(1:n, m, replace=TRUE)
pop = sam[I,]

fuzz = rnorm(m)*sigmahat(pop$w, pop$x)
pop$y = muhat(pop$w, pop$x) + fuzz 
pop$w = 0+pop$w

J = sample(1:m, n, replace=TRUE)
sam = pop[J,]

pop.model = lm(y ~ w*factor(x), data=pop)
mu = function(w,x) { predict(pop.model, newdata=data.frame(w=w,x=x)) }
ca = list(pop=pop, sam=sam, mu=mu)
```

### Scatter Plot

```{webr}
#| envir: ca 
#| autorun: true 

scale_y = function(limits=c(-15000, 1.5e5), breaks=seq(0, max(limits), by=25e3), ...) { 
  list(
    scale_y_continuous(breaks=breaks, labels=sprintf('%dk', breaks/1e3)),  
    coord_cartesian(ylim=limits)
  )
}

years = 8:20
scale_x = function(limits=c(min(years)-.5, max(years)+.5)) { 
  scale_x_continuous(breaks=years, labels=sprintf('%dy', years), limits=limits)
}
```

```{webr}
#| envir: ca 
#| autorun: true 

proportion.scale = 500000
plotX = function(w,x, shift=default.shift) { ifelse(w==0, x-shift, x+shift) }
interleaved.bars = list(
  geom_bar(aes(x=plotX(w,x), y=proportion.scale*after_stat(prop), 
               fill=factor(w), color=factor(w)), 
           position='identity', alpha=.1, linewidth=.1), 
  guides(color='none', fill='none'))
purple.bars = geom_bar(aes(x=x, y=proportion.scale*after_stat(prop)), 
                       alpha=.1, linewidth=.05, fill='purple', color='purple', width=.2)
scales = list(scale_x(), 
              scale_y(sec.axis=sec_axis(~./proportion.scale, name='proportion')))
```

```{webr}
#| envir: ca 
#| autorun: true 

default.shift = .15
lsq.plot = function(sam, formula=NULL, 
  dot.size=1, shift=default.shift) {
  base.plot = ggplot(sam) + 
    geom_point(aes(x=plotX(w,x), y=y,color=factor(w)), 
      position=position_jitter(seed=0, width=shift),
      alpha=.1, size=dot.size) + 
    stat_summary(aes(x=plotX(w,x), y=y, fill=factor(w)), 
      fun.data=mean_sd, geom='pointrange', 
      shape=21, alpha=.5, color='black') +
    interleaved.bars + purple.bars + scales
    
    if(is.null(formula)) { base.plot } else { 
        model = lm(formula, data=sam)
        gridx = seq(-10, 50, length.out=1000)
        muhat = function(w,x) predict(model, newdata=data.frame(w=w,x=x))   
        base.plot + 
          geom_line(aes(x=plotX(w,x), y=muhat(w,x), color=factor(w)), 
            data = expand_grid(w=0:1, x=gridx), alpha=.7, linetype='dashed') +
          geom_point(aes(x=plotX(w,x), y=muhat(w,x), fill=factor(w)), 
            color='black', alpha=.5, shape=23) 
    }
}
```


### Sampling Distribution Plots 

```{webr}
#| envir: ca 
#| autorun: true 

plot.sampling.distribution = function(pop, formula, target, n=nrow(sam), replications=default.replications) { 
    estimates = 1:replications |> map_vec(function(rep) { 
      J = sample(1:nrow(pop), size=n, replace=TRUE)
      sam = pop[J,]

      fitted.model = lm(formula, data=sam) 
      muhat = function(w,x) { predict(fitted.model, newdata=data.frame(w=w, x=x)) } 
      target(muhat, sam)
    })
    the.target = target(mu, pop)
    ggplot() + 
     geom_vline(xintercept = the.target, color='green', linewidth=2, alpha=.5) +
     geom_vline(xintercept = mean(estimates), color='blue', linewidth=.75, alpha=.9) +
     geom_histogram(aes(x=estimates, y=after_stat(density)), bins=50, alpha=.2)
}
```

### Data for the Concluding Exercise 

```{webr}
#| envir: ca 
#| autorun: true 

m0x = rep(c(10,12,14,16,18), c(50, 75, 100, 125, 150))
m1x = rep(c(10,12,14,16,18), c(100,100,100, 100,100))
eps0 = rnorm(length(m0x))
eps1 = rnorm(length(m1x))
for(uu in 1:unique(m1x)) { 
  eps0[m0x==uu] = eps0[m0x==uu] - mean(eps0[m0x==uu])
  eps1[m1x==uu] = eps1[m1x==uu] - mean(eps0[m1x==uu])
}
exercise.pop = rbind(
  data.frame(w=0, x=m0x, y=mu(0,m0x)+eps0),
  data.frame(w=1, x=m1x, y=mu(1,m1x)+eps1))
J = sample(1:nrow(exercise.pop), 1000, replace=TRUE)
exercise.sam = exercise.pop[J,]
```

:::


## What We're Doing 
 
:::: {.panel-tabset}
### Estimating $\mu(w,x)$

```{webr}
#| envir: ca 
#| autorun: true
#| warning: false
#| fig-width: 12
formula = y ~ w*x
sam |> lsq.plot(formula)
```

- Today, we'll look into something we saw in the Week 9 Homework's [last exercise](https://qtm285-1.github.io/assets/homework/week9-homework.html#exr-fake-data-lsq). 
  - We estimated our subpopulation means $\mu(w,x)$ using least squares ...
  - ... to choose a function from the 'not-necessarily-parallel lines' model.
    
$$
\hat\mu(w,x) = \argmin_{m \in \model} \qty{ Y_i - m(W_i,X_i) }^2 \qfor 
\model = \qty{ m(w,x) = a(w) + b(w)x } 
$$


- It didn't fit the data very well: $\hat\mu(w,x) \not\approx \mu(w,x)$.^[In the plot, `r diamond` indicates $\hat\mu(w,x)$ and `r pointrange` indicates $\mu(w,x)$.]
- But when we used it to adjust for covariate shift, it worked well: $\hat \Delta_0 \approx \Delta_0$. $\hphantom{1}$

::: {#eq-adjusted-diff}

$$
\color{gray}
\begin{aligned}
\hat\Delta_0 
&= \ingroupa{\frac{1}{N_0}\sum_{i: W_i=0}} \left\{ \ingroupb{\hat\mu(1,X_i)} - \ingroupa{\hat\mu(0,X_i)} \right\} &&\qfor \ingroupa{N_0 = \sum_{i: W_i=0} 1}
\\
\Delta_0
&= \ingroupa{\frac{1}{m_0} \sum_{j: w_j=0}} \left\{ \ingroupb{\mu(1,x_{j})} - \ingroupa{\mu(0,x_{j})} \right\}  &&\qfor \ingroupa{m_0 = \sum_{j: w_j=0} 1}
\end{aligned}
$$

:::

- How did we know it worked well? We were working with a fake population.
  - We could actually calculate our estimation target. And we did.
  - And we simulated our survey many times to get our estimator's sampling distribution.^[Or, to be precise, a histogram that approximates it. But we used 10,000 simulated surveys, so our approximation was pretty good.]

### The Sampling Distribution of $\hat\mu(1,x)-\hat\mu(0,x)$

```{webr}
#| envir: ca 
#| autorun: true
#| warning: false
#| fig-width: 12
x = 14
target = function(muhat, sam) { 
  muhat(1, x) - muhat(0, x)
}
pop |> plot.sampling.distribution(formula, target)
```


- Look at the difference in mean incomes at one education level. 
- Compare it to [our target $\theta$]{.target}, the actual difference in means in our population. 
$$
\hat\theta = \ingroupb{\hat\mu(1,x)} - \ingroupa{\hat\mu(0,x)} \qqtext{ estimates } 
\theta = \ingroupb{\mu(1,x)} - \ingroupa{\mu(0,x)}
$$

- The sampling distribution of our estimator $\hat\theta$ is shown above.
- For $x=14$ (a 2-year degree), which is what's shown for now, its center is far from the target. 
  - Our estimator is biased. And its bias is *positive*. 
  - In most samples drawn from the population, we *overestimate* the difference. 
- Change $x$ in the code above to see what happens at other education levels.
  - Try $x=12$ (completed high school) and $x=16$ (a 4-year degree). And whatever else you like. 
  - Remember that some levels, e.g. $x=15$, don't exist in our population. 
  - Don't be surprised if you try $x=15$ and it doesn't work.

### The Sampling Distribution of $\hat\Delta_0$

```{webr}
#| envir: ca 
#| autorun: true
#| warning: false
#| fig-width: 12
target = function(muhat, sam) { 
  mean(muhat(1, sam$x[sam$w==0]) - muhat(0, sam$x[sam$w==0]))
}
pop |> plot.sampling.distribution(formula, target)
```

- Here's the sampling distribution of our adjusted difference in means. 
$$
\hat\theta = \ingroupa{\frac{1}{N_0}\sum_{i: W_i=0}} \qty{ \ingroupb{\hat\mu(1,X_i)} - \ingroupa{\hat\mu(0,X_i)} }
\qqtext{ estimates } 
\theta = \ingroupa{\frac{1}{m_0} \sum_{j: w_j=0}} \qty{ \ingroupb{\mu(1,x_{j})} - \ingroupa{\mu(0,x_{j})} } 
$$

- We're using biased estimates of the difference in means at each education level $x$.
- But when we average over the covariate distribution^[In this case, our covariate is education level. So we're averaging over the distribution of education levels in our sample.] of [male CA residents]{.groupa} ... 
  - ... we get an estimator that's barely biased at all.
  - Our term-by-term biases are (imperfectly) canceling each other out.

:::

## This Activity's Goal 

- We're going to understand this cancellation phenomenon a bit better. 
- We'll do the math to find out ...
  - where bias is and isn't coming from. 
  - and what tends to cause cancellation like this.

### Why bother?

- You could argue that we should never use misspecified models. 
  - If we always used the 'all functions model', we wouldn't have to worry about bias. 
- **1**. We can't always use the all functions model.
  - If we have groups in our population that we haven't sampled ...
  - ... we need a smaller model, e.g. lines, to help us make predictions for them.
- **2**. We're not always choosing the model. 
  - When we read someone else's analysis, we want to know whether we should believe what they're saying.
  - Often, you can't get their data so you can't just analyze it your way to check.
- **3**. It's a good warm-up for what we'll cover next. 

# Warm-Up
Our Gym Subsidy Example 

## A Case of Perfect Cancellation

::: {.panel-tabset}
### Estimating $\mu(x)$
```{webr}
#| envir: gym 
#| autorun: true
#| fig-width: 12
#| warning: false
zoom.in = coord_cartesian(y=c(4,8))
formula = y ~ 1+x
sam |> lsq.plot(formula) # + zoom.in
```


- This is the gym subsidy example we looked at in class [a few days ago](https://qtm285-1.github.io/assets/lectures/Lecture13.html).
  - We have 3 levels of $x$: 0, 50, and 100.
  - And we're estimating $\mu$ by least squares using the 'lines' model.

$$
\begin{aligned}
\hat \mu &= \argmin_{m \in \model} \qty{ Y_i - m(X_i) }^2 \qfor \model = \qty{ m(x) = a + bx } && \text{ estimates } \\ 
\mu(x) &= \frac{1}{m_x} \sum_{j: x_j=x} y_j \qfor m_x = \sum_{j: x_j=x} 1
\end{aligned}
$$

- This is simulated data, so we know [$\mu(x)$]{.target}.  It's plotted in [green]{.target} above.
- We haven't done a very good job of estimating it.^[To see that more clearly, uncomment the `+ zoom.in` in the code above.] 
  - It's not because our sample is too small.^[Replace `sam` with `pop` in the code above to see the population least squares predictor $\tilde\mu$.^[$\tilde\mu = \argmin_{m \in \model} \sum_{j=1}^m \qty{ y_j - m(x_j) }^2$.] Still bad.]
  - The problem is misspecification. $\mu$ looks like a hockey stick. No line can fit that.

### The sampling distribution of $\hat\mu(x)$
```{webr}
#| envir: gym 
#| autorun: true
#| fig-width: 12
#| warning: false
target = function(muhat, sam) { muhat(100) }
pop |> plot.sampling.distribution(formula, target)
```

- Here's the sampling distribution of $\hat\mu(100)$, our least squares estimate of [$\mu(100)$.]{.target}. 
  - It's not even close to being centered on [$\mu(100)$]{.target}.
  - It's centered on the *population least squares estimate* of $\mu(100)$.^[We proved that in class earlier this week. It's [here](https://qtm285-1.github.io/assets/lectures/Lecture12.html#/relating-hatmu-and-tildemu) in the slides.]

$$
\tilde\theta = \tilde\mu(100) \qfor 
\tilde \mu = \argmin_{m \in \model} \sum_{j=1}^m \qty{ y_j - m(x_j) }^2
$$

- Here's how $\hat\theta$, $\tilde\theta$, and $\theta$ are calculated in **R**.
- To get the plot above, `plot.sampling.distribution` simulates our experiment over and over and calculates $\hat\theta$ each time. 

```{webr}
#| envir: gym 
#| autorun: true

fit = lm(formula, data=sam)
muhat = function(x) { predict(fit, newdata=data.frame(x=x)) }

pop.fit = lm(formula, data=pop)
mutilde = function(x) { predict(pop.fit, newdata=data.frame(x=x)) }

thetahat    = target(muhat, sam)
thetatilde  = target(mutilde, pop)
theta       = target(mu,    pop)

data.frame(thetahat, thetatilde, theta)
```

- So here's our bias.

```{webr}
#| envir: gym 
#| autorun: true
bias = thetatilde - theta  
bias 
```


- One thing you'll notice if you look at $\hat\mu(x)$ for $x=0$ and $x=50$ is that they're biased in the opposite direction.^[Try it! Change `target` in the code above to `function(muhat, sam) { muhat(0) }` and see.]
  - If we're looking at difference like $\hat\mu(100) - \hat\mu(50)$, that's bad. $\text{too big} - \text{too small} = \text{even more too big}$
  - But if we're looking at a sum, that's good. We'll get some cancellation.

### The sampling distribution of its average
```{webr}
#| envir: gym 
#| autorun: true
#| fig-width: 12
#| warning: false
target = function(muhat, sam) { mean(muhat(sam$x)) }
pop |> plot.sampling.distribution(formula, target)
```

- Let's think about a new target: the average of $y$ in the population. 
  - That's the same thing as the average of $\mu(x_j)$ over the whole population.
  - That's just summing in a certain order. See @sec-summing-in-order.
$$
\theta = \frac{1}{m} \sum_{j=1}^m y_j = \frac{1}{m} \sum_{j=1}^m \mu(x_j) 
$$

- So maybe we should estimate it by averaging $\hat\mu(x)$ over our sample.

$$
\hat\theta = \frac{1}{n} \sum_{i=1}^n \hat\mu(X_i)
$$

- And when we do that, we get an *unbiased* estimator. 
  - The center of our sampling distribution is the *population average* of our *population least squares predictor*.
  - And that's exactly the same as our estimation target $\theta$.

$$
\E[\hat\theta] = \tilde\theta = \frac{1}{m} \sum_{j=1}^m \tilde\mu(x_j) 
$$

- Here's the empirical evidence.

```{webr}
#| envir: gym 
#| autorun: true

fit = lm(formula, data=sam)
muhat = function(x) { predict(fit, newdata=data.frame(x=x)) }

pop.fit = lm(formula, data=pop)
mutilde = function(x) { predict(pop.fit, newdata=data.frame(x=x)) }

thetahat    = target(muhat, sam)
thetatilde  = target(mutilde, pop)
theta       = target(mu,    pop)
data.frame(thetahat, thetatilde, theta)
```

:::

## Orthogonality and Perfect Cancellation

- The *orthogonality of least squares residuals* tells us this happens. 

$$
0 = \sum_{i=1}^n \qty{ Y_i - \hat\mu(X_i) } \ m(X_i) 
\qqtext{ for all } m \in \model
$$

- Why? Plug in $m(x) = 1$. That's a line. It's a horizontal line. Then do a little algebra.
$$
0 = \sum_{i=1}^n \qty{ Y_i - \hat\mu(X_i) } \times 1 \implies 
\veryfaint{\frac{1}{n}} \sum_{i=1}^n Y_i = \veryfaint{\frac{1}{n}} \sum_{i=1}^n \hat\mu(X_i) 
$$

- It tells us that our estimate $\hat\theta$ is really just the sample mean.
  - We calculated it in a strange way, but it's the same number.
  - And we know the sample mean is an unbiased estimator of the population mean.
- This is true for any regression model that includes the constant function $m(x)=1$.

$$
\begin{aligned}
\model &= \{ m(x) = a : a \in \mathbb{R} \} && \text{horizontal lines} \\
\model &= \{ \text{all functions} \ m(x) \} && \text{all functions} \\
\model &= \{ m(x) = a + bx : a,b \in \mathbb{R} \} && \text{lines} \\
\model &= \{ m(x) = \sum_{k=0}^p a_k x^k : a_k \in \mathbb{R} \} && \text{polynomials of order } p \\
\end{aligned}
$$


- One model it's not true for is *lines through the origin*. 
  - People don't like using that model and that's why. Averages are biased.
  - If you go back a slide and change `formula = y ~ 1+x` to `formula = y ~ 0+x`, you'll see it. Bias!

$$
\begin{aligned}
\model &= \{ m(x) = bx : b \in \mathbb{R} \} && \text{lines through the origin} 
\end{aligned}
$$

## *Population* Orthogonality and Perfect Cancellation

- Let's look at this a different way. Let's think about the orthogonality of *population least squares residuals*.

$$
\frac{1}{m} \sum_{j=1}^m \qty{ y_j - \tilde\mu(x_j) } \times m(x_j) = 0 \qqtext{ for all } m \in \model.
$$

- Again, plug in $m(x) = 1$. And do the same algebra as before.

$$
0 = \sum_{j=1}^m \qty{ y_j - \tilde\mu(x_j) } \times 1 \implies 
\veryfaint{\frac{1}{m}} \sum_{j=1}^m y_j = \underset{\tilde\theta}{\veryfaint{\frac{1}{m}} \sum_{j=1}^m \tilde\mu(x_j)} 
$$

- This tells us the population version of our estimator, $\tilde\theta$, is just the population mean. That's our target.
- And because we know that $\tilde\theta$ is the expectation of our estimator $\hat\theta$, that means our estimator is unbiased.

# California Income Data 

## Our Adjusted Difference $\hat\Delta_0$
 
```{webr}
#| envir: ca 
#| autorun: true
#| warning: false
#| fig-width: 12
formula = y ~ w*x
sam |> lsq.plot(formula)
```

- Let's look at our adjusted difference in means when we use the 'not necessarily parallel lines' model.
$$ 
\model = \{ m(w,x) = a(w) + b(w)x \ \text{ for functions} \ a,b \} 
$$

- We'll break it down into two parts. 
  - A [matched part]{.groupa} where we average the [red prediction function $\hat\mu(1,x)$]{.groupa} over the [red covariate distribution]{.groupa}.
  - A [mismatched part]{.groupb} where we average the [green prediction function $\hat\mu(0,x)$]{.groupb} over the [red covariate distribution]{.groupa}.
$$
\color{gray}
\begin{aligned}
\hat\Delta_0 
&= \ingroupa{\frac{1}{N_0}\sum_{i: W_i=0}} \left\{ \ingroupb{\hat\mu(1,X_i)} - \ingroupa{\hat\mu(0,X_i)} \right\} &&\qfor \ingroupa{N_0 = \sum_{i: W_i=0} 1} \\
&= 
\underset{\text{mismatched part}}{\ingroupa{\frac{1}{N_0}\sum_{i: W_i=0}}\ingroupb{\hat\mu(1,X_i)}} -   \underset{\text{matched part}}{\ingroupa{\frac{1}{N_0}\sum_{i: W_i=0}}\ingroupa{\hat\mu(0,X_i)}} 
\end{aligned}
$$

- Our target, of course, has the same parts.

$$
\color{gray}
\begin{aligned}
\Delta_0 
&= \ingroupa{\frac{1}{m_0}\sum_{j: w_j=0}} \left\{ \ingroupb{\mu(1,x_j)} - \ingroupa{\mu(0,x_j)} \right\} &&\qfor \ingroupa{m_0 = \sum_{j: w_j=0} 1} \\
&= 
\underset{\text{mismatched part}}{\ingroupa{\frac{1}{m_0}\sum_{j: w_j=0}}\ingroupb{\mu(1,x_j)}} -   \underset{\text{matched part}}{\ingroupa{\frac{1}{m_0}\sum_{j: w_j=0}}\ingroupa{\mu(0,x_j)}} 
\end{aligned}
$$

## The Matched Part 

```{webr}
#| envir: ca 
#| autorun: true
#| warning: false
#| fig-width: 12
target = function(muhat, sam) { 
  mean(muhat(0, sam$x[sam$w==0]))
}
pop |> plot.sampling.distribution(formula, target)
```

- Here's the sampling distribution of the [matched part]{.groupa}. 
- You can see it's unbiased, i.e., centered on the [matched part of our target.]{.groupa .target}

$$
\E\qty[ \ingroupa{\frac{1}{N_0}\sum_{i: W_i=0}}\ingroupa{\hat\mu(0,X_i)} ] = \ingroupa{\frac{1}{m_0} \sum_{j: w_j=0} \mu(0,x_j)}
$$

- Let's prove it. As usual, we'll use the orthogonality of least squares residuals. 

$$
0 = \sum_{i=1}^n \qty{ Y_i - \hat\mu(W_i,X_i) } \ m(W_i,X_i) 
\qqtext{ for all } m \in \model
$$

- What function $m$ should we plug in? Suppose we're using the 'not necessarily parallel lines' model.
- See the next slide for the answer.

::: fragment
$$
m(w,x) = 1_{=0}(w) = \begin{cases} 1 & \text{if } w=0 \\ 0 & \text{if } w=1 \end{cases}
$$

- That's in the model. It's $a(w) + b(w)x$ for $a(w)=1_{=0}(w)$ and $b(w)=0$.
- Let's plug it in and do our algebra.

$$
\begin{aligned}
0 
&\explain{=}{plugging in} \sum_{i=1}^n \qty{ Y_i - \hat\mu(W_i,X_i) } \times 1_{=0}(W_i) \\
&\explain{=}{using the indicator trick} \sum_{i=1}^n Y_i 1_{=0}(W_i) - \sum_{i=1}^n \hat\mu(0,X_i) 1_{=0}(W_i). 
\end{aligned}
$$

- Rearranging and dividing by the number $N_0$ of red dots gives us what we want.^[Remember that a sum of terms multiplied by an indicator is the sum of the terms where the indicator is 1.]
$$
\frac{1}{N_0}\sum_{i:W_i=0} Y_i  
= \frac{1}{N_0}\sum_{i:W_i=0} \hat\mu(1,X_i)
$$

:::

## The Mismatched Part 

```{webr}
#| envir: ca 
#| autorun: true
#| warning: false
#| fig-width: 12
target = function(muhat, sam) { 
  mean(muhat(1, sam$x[sam$w==0]))
}
pop |> plot.sampling.distribution(formula, target)
```

- Here's the sampling distribution of the [mismatched]{.groupa} [part]{.groupb}. You can see that it's biased, but not too badly.
$$
\E\qty[ \ingroupa{\frac{1}{N_0}\sum_{i: W_i=0}}\ingroupb{\hat\mu(1,X_i)} ] \neq \ingroupa{\frac{1}{m_0} \sum_{j: w_j=0}} \ingroupb{\mu(1,x_j)}
$$

::: {.panel-tabset}
### Our 'indicator trick' argument doesn't work 
- Let's think about why why we can't show that it's unbiased like we did for the matched part.
  - If you put a group indicator $m=1_{=0}$ or $m=1_{=1}$ in the orthogonality condition ... 
  - ... it's not going to work out like it did for the matched part.
  
$$
0 = \sum_{i=1}^n \qty{ Y_i - \hat\mu(W_i,X_i) } \ m(W_i,X_i) 
\qqtext{ for all } m \in \model
$$

- If you put in an indicator for $w=1$: 
  - you get the right function [$\hat\mu(1,x)$]{.groupb} 
  - averaged over the [wrong covariate distribution.]{.groupb}
- If you put in an indicator for $w=0$:
   - you get the wrong function [$\hat\mu(0,x)$]{.groupa}
   - averaged over the [right covariate distribution.]{.groupa}
- In short, putting in a group indicator tells us about matched things, i.e., 
  - averages of the least squares prediction for a group
  - averaged over the covariate distribution of *that same group*.

### The 'population residuals version'  
- You could, of course, use the population residuals' orthogonality property. 
$$
\begin{aligned}
0 &= \E\qty[ \qty{ Y_i - \tilde\mu(W_i, X_i) } \ m(W_i,X_i) ] && \qqtext{ for all } m \in \model \\
  &\explain{=}{By the law of iterated expectations conditioning on $(W_i,X_i)$} 
 \E\qty[ \qty{ \mu(W_i,X_i) - \tilde\mu(W_i,X_i) } \ m(W_i,X_i) ] \qqtext{ for all } m \in \model \\
  &\explain{=}{Writing out our expectation as an average over the population} 
  \frac{1}{m}\sum_{j=1}^m \qty{ \mu(w_j,x_j) - \tilde\mu(w_j,x_j) } \ m(w_j,x_j)
\end{aligned}
$$

- But that has the same problem. Matched stuff only.

### Why it's not *badly* biased

- Let's do what we just said wouldn't work: plug an indicator into our population orthogonality condition. 
- Using $m(w,x)=1_{=1}(w)$, we get the wrong average of the right function.

$$
\begin{aligned}
0 &= \frac{1}{m}\sum_{j=1}^m \qty{ \mu(w_j,x_j) - \tilde\mu(w_j,x_j) } \ 1_{=1}(w_j)
\end{aligned}
$$ {#eq-wrong-average}

- Using the indicator trick, rearranging, and multiplying by $m/m_1$, and gives us ...

$$
\ingroupb{\frac{1}{m_1}\sum_{j:w_j=1} \mu(1,x_j)} = \ingroupb{\frac{1}{m_1}\sum_{j:w_j=1} \tilde\mu(1,x_j)}
$$

- Which we can rewrite in 'histogram form'^[We'll write [$p_{x \mid 0}$]{.groupa} and [$p_{x \mid 1}$]{.groupb} for the height of the [red]{.groupa} and [green]{.groupb} bars at covariate level $x$ in our population histogram. That is, [$p_{x \mid 0}$]{.groupa} is the proportion of [male residents]{.groupa} in our population with education level $x$ and [$p_{x \mid 1}$]{.groupb} the same for female residents.]

$$
\sum_x \ingroupb{p_{x \mid 1} \ \tilde\mu(1,x)} 
= \sum_x \ingroupb{p_{x \mid 1} \ \mu(1,x)} \qfor p_{x \mid w} = \frac{\sum_{j:w_j=w,x_j=x} 1}{\sum_{j:w_j=w} 1}
$$

- What happens if our two histograms are almost the same? We can't be that far off.
$$
\qqtext{ therefore } \sum_x \ingroupa{p_{x \mid 0}} \ \ingroupb{\mu(1,x)} \approx \sum_x \ingroupa{p_{x \mid 0}} \ \ingroupb{\tilde\mu(1,x)} \qqtext{ if } \ingroupa{p_{x \mid 0}} \approx \ingroupb{p_{x \mid 0}} 
$$

- If our histograms were *exactly the same*, it wouldn't really matter what model we used here.
  - But they're not exactly the same. So it does matter.
  - Try changing your regression formula to `y ~ 1+w` to fit the 'horizontal lines model'
  - What happens to our estimator's bias? 

:::

# An Exercise {#sec-exercise}

- Do this to practice using the techniques we've been using to analyze our estimators. 
- And build some intuition about why misspecification doesn't always cause much bias.

## A Caricature of the California Data

```{webr}
#| envir: ca 
#| autorun: true
#| warning: false
#| fig-width: 12
formula = y ~ w*x
exercise.pop |> lsq.plot(formula)
```

- Let's dig in to why we do so much better with the *lines model* than with the *horizontal lines model*.
  - Above, there's a plot of a caricature of our California population data. 
  - And the population least squares predictor in the lines model.
- The covariate distributions [$p_{x \mid 0}$]{.groupa} and [$p_{x \mid 1}$]{.groupb} have are very simple.
  - [$p_{x \mid 1}$]{.groupa} is flat. At each of the 5 education levels, you have 1/5 of the [female residents]{.groupa}.
  - [$p_{x \mid 0}$]{.groupb} is linear. 
    - At the level $x=14$, you have 1/5 of the [male residents]{.groupb}. 
    - But the fraction decreases by $1/20=.05$ with every two years of education.

$$\color{gray}
\begin{aligned}
\ingroupb{p_{x \mid 1}} &= \frac{1}{5} \qqtext{ and } 
\ingroupa{p_{x \mid 0}} &= \frac{1}{5} - \frac{1}{20} \frac{x-14}{2} 
\end{aligned}
$$

- More importantly, they have a *linear relationship*.

$$
\color{gray}
\begin{aligned}
\ingroupa{p_{x \mid 0}} &= \ingroupb{p_{x \mid 1}} \times (ax + b) \qfor a=\frac{11}{4} \qand b=-1/8.
\end{aligned}
$$

## Exercise 

```{webr}
#| envir: ca 
#| autorun: true
#| warning: false
#| fig-width: 12
target = function(muhat, sam) { 
  mean(muhat(1, sam$x[sam$w==0]) - muhat(0, sam$x[sam$w==0]))
}
exercise.pop |> plot.sampling.distribution(formula, target)
```

- When we look at the sampling distribution of $\hat\Delta_0$, we see no bias at all.
- And it's not because our covariate distributions are close to the same in the two groups. They're not.
  - Something else is going on. It's about the relationship between our model and these covariate distributions.
  - If you change the model to the horizontal lines model, you'll get bias.^[Try it! Change the formula to `y ~ 1+w`]

- **Exercise**. Prove that the population version of our estimator, $\tilde\Delta_0$, is equal to the target, i.e., that
$$
\color{gray}
\begin{aligned}
\tilde\Delta_0 &= \sum_x \ingroupa{p_{x \mid 0}} \qty{\ingroupb{\tilde\mu(1,x)} - \ingroupa{\tilde\mu(0,x)}} \qfor \\ 
\tilde \mu &= \argmin_{m \in \model} \frac{1}{m}\sum_{j=1}^m \qty{ y_j - m(w_j,x_j) }^2 \qqtext{ with } \model = \{ a(w) + b(w) x \}. 
\end{aligned}
$$ 

- If you're not convinced that they're exactly equal, run this code to check.
```{webr}
#| envir: ca 

pop.fit = lm(formula, data=exercise.pop)
mutilde = function(w,x) { predict(pop.fit, newdata=data.frame(w=w,x=x)) }

pop.fit.allfunctions = lm(y ~ w*factor(x), data=exercise.pop)
mu = function(w,x) { predict(pop.fit.allfunctions, newdata=data.frame(w=w,x=x)) }

thetatilde  = target(mutilde, exercise.pop)
theta       = target(mu,      exercise.pop)
data.frame(thetatilde, theta)
```

## Hint 

- Think about the orthogonality of population least squares residuals to function $m \in \model$. 
- What happened when we plugged in $m(w,x)=1_{=1}(w)$ on @eq-wrong-average?
  - That didn't show the [mismatched]{.groupa} [term]{.groupb} was unbiased.
  - We were averaging over the wrong covariate distribution. 
- Can we show what we want by plugging in a different *m*?
  - Not $m(w,x)=1_{=1}(w)$, but perhaps $m(w,x)=1_{=1}(w) \times \text{something}$?



# IPW {#sec-ipw}
## A Caricature of the California Data

```{webr}
#| envir: ca 
#| autorun: true
#| warning: false
#| fig-width: 12
formula = y ~ w*x
exercise.pop |> lsq.plot(formula)
```

- Let's dig in to why we do so much better with the *lines model* than with the *horizontal lines model*.
  - Above, there's a plot of a caricature of our California population data. 
  - And the population least squares predictor in the lines model.
- The covariate distributions [$p_{x \mid 0}$]{.groupa} and [$p_{x \mid 1}$]{.groupb} have are very simple.
  - [$p_{x \mid 1}$]{.groupb} is flat. At each of the 5 education levels, you have 1/5 of the [female residents]{.groupa}.
  - [$p_{x \mid 0}$]{.groupa} is linear. 
    - At the level $x=14$, you have 1/5 of the [male residents]{.groupb}. 
    - But the fraction decreases by $1/20=.05$ with every two years of education.

$$\color{gray}
\begin{aligned}
\ingroupb{p_{x \mid 1}} &= \frac{1}{5} \qqtext{ and } 
\ingroupa{p_{x \mid 0}} &= \frac{1}{5} - \frac{1}{20} \frac{x-14}{2} 
\end{aligned}
$$

- More importantly, they have a *linear relationship*.

$$
\color{gray}
\begin{aligned}
\ingroupa{p_{x \mid 0}} &= \ingroupb{p_{x \mid 1}} \times (ax + b) \qfor a=\frac{11}{4} \qand b=-1/8.
\end{aligned}
$$

## Exercise 

```{webr}
#| envir: ca 
#| autorun: true
#| warning: false
#| fig-width: 12
target = function(muhat, sam) { 
  mean(muhat(1, sam$x[sam$w==0]) - muhat(0, sam$x[sam$w==0]))
}
exercise.pop |> plot.sampling.distribution(formula, target)
```

- When we look at the sampling distribution of $\hat\Delta_0$, we see no bias at all.
- And it's not because our covariate distributions are close to the same in the two groups. They're not.
  - Something else is going on. It's about the relationship between our model and these covariate distributions.
  - If you change the model to the horizontal lines model, you'll get bias.^[Try it! Change the formula to `y ~ 1+w`]

- **Exercise**. Prove that the population version of our estimator, $\tilde\Delta_0$, is equal to the target, i.e., that
$$
\color{gray}
\begin{aligned}
\tilde\Delta_0 &= \sum_x \ingroupa{p_{x \mid 0}} \qty{\ingroupb{\tilde\mu(1,x)} - \ingroupa{\tilde\mu(0,x)}} \qfor \\ 
\tilde \mu &= \argmin_{m \in \model} \frac{1}{m}\sum_{j=1}^m \qty{ y_j - m(w_j,x_j) }^2 \qqtext{ with } \model = \{ a(w) + b(w) x \}. 
\end{aligned}
$$ 

- If you're not convinced that they're exactly equal, run this code to check.
```{webr}
#| envir: ca 

pop.fit = lm(formula, data=exercise.pop)
mutilde = function(w,x) { predict(pop.fit, newdata=data.frame(w=w,x=x)) }

pop.fit.allfunctions = lm(y ~ w*factor(x), data=exercise.pop)
mu = function(w,x) { predict(pop.fit.allfunctions, newdata=data.frame(w=w,x=x)) }

thetatilde  = target(mutilde, exercise.pop)
theta       = target(mu,      exercise.pop)
data.frame(thetatilde, theta)
```

## Hint 

- Think about the orthogonality of population least squares residuals to function $m \in \model$. 
- What happened when we plugged in $m(w,x)=1_{=1}(w)$ on @eq-wrong-average?
  - That didn't show the [mismatched]{.groupa} [term]{.groupb} was unbiased.
  - We were averaging over the wrong covariate distribution. 
- Can we show what we want by plugging in a different *m*?
  - Not $m(w,x)=1_{=1}(w)$, but perhaps $m(w,x)=1_{=1}(w) \times \text{something}$?

# Appendix 

## Summing in Order {#sec-summing-in-order}

$$
\begin{aligned}
\frac{1}{m}\sum_{j=1}^m y_j 
&= \frac{1}{m} \ \sum_x \sum_{j:x_j=x} y_j \\ 
&= \frac{1}{m} \ \sum_x \mu(x) \times m_x  \qfor \mu(x) = \frac{1}{m_x} \sum_{j:x_j=x} y_j \qand m_x = \sum_{j:x_j=x} 1 \\
&= \frac{1}{m} \ \sum_x \mu(x) \sum_{j:x_j=x} 1 \\
&= \frac{1}{m} \ \sum_x \sum_{j:x_j=x} \mu(x) \\
&= \frac{1}{m} \ \sum_{j=1}^m m_x \mu(x)
\end{aligned}
$$

