---
title: "Lecture 12"
subtitle: "The Behavior of Least Squares Predictors"
---

# Introduction 

## Today's Topic

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}
{{< include shared-code.qmd >}}


```{r}
#| label: fake-data
x = rep(c(20,30,40), each=1000)

pi.pop = function(x) { case_when(x < 25 ~ .25, x < 35 ~ .5, TRUE ~ .75) } 
mu.pop = function(w,x) case_when(
  w==1 & x <  25  ~ 10, 
  w==1 & x <= 35  ~ 10,
  w==1            ~ 20, 
  w==0 & x <  25  ~ 5, 
  w==0 & x <= 35  ~ 10,
  w==0            ~ 10)

w = 0 + (runif(length(x)) < pi.pop(x))
y = rpois(length(x), mu.pop(w,x))
fake.pop = data.frame(w=w, x=x, y=y)
```

```{r}
pop = fake.pop 
m = nrow(pop)
n = 200
set.seed(5)
J = sample(1:m, size=n, replace=TRUE)
pop$jitter = runif(m, -1, 1)
sam = pop[J,]
```

```{r}
prop.scale = 40

xbars  = list(geom_bar(aes(x=x, y=prop.scale*after_stat(prop)), 
                       fill='purple', alpha=.1, linewidth=.05),
              scale_y_continuous(sec.axis = sec_axis(~./prop.scale, name='proportion')))

xmeans = stat_summary(aes(x=x, y=y), 
  geom='pointrange', fun.data=mean_sd, alpha=.7)

xfit = function(sam, formula, 
                color='blue', linetype='solid',
                shape='square', size=3, alpha=.7) {
  fitted.model = lm(formula, data=sam)
  muhat = function(x) predict(fitted.model, newdata=data.frame(x=x))
  unique.x = unique(sam$x)
  dense.x = seq(min(unique.x), max(unique.x), length.out=100)
  list( geom_line(aes(x=x, y=muhat), 
          data=data.frame(x=dense.x, muhat=muhat(dense.x)), 
          color=color, linetype=linetype, alpha=alpha),
    geom_point(aes(x=unique.x, y=muhat(unique.x)),
          data=data.frame(x=unique.x, muhat=muhat(unique.x)),
          color=color, shape=shape, alpha=alpha, size=size))
}

scales = list(
  scale_y_continuous(breaks=seq(0,40, by=10)),
  coord_cartesian(ylim=c(0,25)))

sam.plot=ggplot(sam[sam$w==0,]) + 
 geom_point(aes(x=x+jitter, y=y), color=groupa,  alpha=.2) +
 xmeans + scales
pop.plot=ggplot(pop[pop$w==0,]) + 
  geom_point(aes(x=x+jitter, y=y), color=groupa, alpha=.05, size=.5) +
  xmeans + scales
```

:::: r-stack
::: {.fragment .fade-out data-fragment-index="0"}
```{r}
#| fig.width: 7
#| layout-ncol: 2

sam.plot + xfit(sam[sam$w==0,], y~x, alpha=.7, linetype='dotted')
pop.plot
```
:::
::: {.fragment .current-visible data-fragment-index="0"}
```{r}
#| fig.width: 7
#| layout-ncol: 2

sam.plot + xfit(sam[sam$w==0,], y~x, alpha=.7, linetype='dotted')
pop.plot + xfit(pop[pop$w==0,], y~x, alpha=.7, linetype='dotted')
```

:::
::::


:::: {.columns}
::: {.column}
$$
\begin{aligned}
\inblue{\hat\mu} &= \argmin_{m \in \model}\sum_{i=1}^n \qty{ Y_i - m(X_i) }^2 \\
&\qfor \model = \{ m(x)= a+bx \ : \ a,x \in \mathbb{R} \}
\end{aligned}
$$

:::
::: {.column}

:::: r-stack
::: {.fragment .fade-out data-fragment-index="0"}
$$
\begin{aligned}
\mu(x) &= \frac{1}{m_x}\sum_{j:x_j=x} y_j 
\qfor m_x = \sum_{j:x_j=x} 1 \\
\ & \ 
\end{aligned}
$$
:::
::: {.fragment .current-visible data-fragment-index="0"}
$$
\begin{aligned}
\mu(x) &= \frac{1}{m_x}\sum_{j:x_j=x} y_j 
\qfor m_x = \sum_{j:x_j=x} 1 \\
\tilde\mu &= \argmin_{m \in \model}\sum_{i=1}^n \qty{ Y_i - m(X_i) }^2
\end{aligned}
$$

:::
::: 
::::

