<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>13&nbsp; Comparing Two Groups – Prediction, Inference, and Causality</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../exams/practice-midterm-1.html" rel="next">
<link href="../homework/week3-homework.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-88e56ac79f6d00081da8a857611ab47f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-7711608381c8608079b9fff5203bcc78.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/live-runtime/live-runtime.js" type="module"></script>
<link href="../site_libs/quarto-contrib/live-runtime/live-runtime.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script type="module" src="../site_libs/quarto-ojs/quarto-ojs-runtime.js"></script>
<link href="../site_libs/quarto-ojs/quarto-ojs.css" rel="stylesheet">
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable-1.1/js/pagedtable.js"></script>
<script>
  window.MathJax = {
    options : {
      menuOptions: {
        settings: {
          assistiveMml: false,
          collapsible: false,  
          explorer: false    
        }
      }
    },
    loader: {load: ['[tex]/physics', '[tex]/unicode']},
    tex: {packages: {'[+]': ['physics', 'unicode']}}
  }
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../part1.html">One and Two-Sample Problems</a></li><li class="breadcrumb-item"><a href="../lectures/Lecture6.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Comparing Two Groups</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Prediction, Inference, and Causality</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">One and Two-Sample Problems</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lab1-prose.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../homework/week0-homework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Homework: Review</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lecture2-prose.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Point and Interval Estimates</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lab2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Probability Background: Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../homework/week1-homework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Homework: The Idea of Calibration</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lecture3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Calibrating Interval Estimates with Binary Observations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../homework/week2-homework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Homework: Calibration with Binary Outcomes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lecture4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Calibrating Interval Estimates using the Bootstrap</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lecture5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Normal Approximation and Sample Size Calculation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lab4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Review: Conditional Expectations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../homework/week3-homework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Homework: Comparing Estimators</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lecture6.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Comparing Two Groups</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../exams/practice-midterm-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Practice Midterm 1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../homework/week5-homework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Homework: Loose Ends</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Regression with Saturated Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lecture7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Summarizing Trends involving Many Groups</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lecture9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multivariate Analysis and Adjustment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../homework/week7-homework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Homework: Covariate Shift</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lab5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">A Game of Telephone</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lecture8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Inference for Complicated Summaries</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../homework/week9-homework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Homework: Calibration for Complex Summaries</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lecture10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Potential Outcomes and Causality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../exams/practice-midterm-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Practice Midterm 2</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Regression with Arbitrary Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lecture11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Least Squares Regression in Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lab6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Least Squares in <strong>R</strong></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lecture12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">The Behavior of Least Squares Predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lecture13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Misspecification and Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lab7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Misspecification and Averaging</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lecture14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Inverse Probability Weighting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lectures/Lecture15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Application: Profit vs.&nbsp;Outcomes in Heart Attack Patients</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../exams/practice-final.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Practice Final</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="-1">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#examples-and-introduction" id="toc-examples-and-introduction" class="nav-link active" data-scroll-target="#examples-and-introduction">Examples and Introduction</a>
  <ul class="collapse">
  <li><a href="#black-vs.-non-black-voters-in-ga" id="toc-black-vs.-non-black-voters-in-ga" class="nav-link" data-scroll-target="#black-vs.-non-black-voters-in-ga"><span class="groupb">Black</span> vs.&nbsp;<span class="groupa">non-Black</span> Voters in GA</a></li>
  <li><a href="#recipients-of-threatening-letters-vs.-others-in-mi" id="toc-recipients-of-threatening-letters-vs.-others-in-mi" class="nav-link" data-scroll-target="#recipients-of-threatening-letters-vs.-others-in-mi"><span class="groupb">Recipients of Threatening Letters</span> vs.&nbsp;<span class="groupa">Others</span> in MI</a></li>
  <li><a href="#residents-with-vs.-without-4-year-degrees-in-ca" id="toc-residents-with-vs.-without-4-year-degrees-in-ca" class="nav-link" data-scroll-target="#residents-with-vs.-without-4-year-degrees-in-ca"><span class="groupb">Residents With</span> vs.&nbsp;<span class="groupa">Without</span> 4-Year Degrees in CA</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  <li><a href="#our-estimator-and-target" id="toc-our-estimator-and-target" class="nav-link" data-scroll-target="#our-estimator-and-target">Our Estimator and Target</a></li>
  <li><a href="#is-this-estimator-good" id="toc-is-this-estimator-good" class="nav-link" data-scroll-target="#is-this-estimator-good">Is This Estimator Good?</a></li>
  </ul></li>
  <li><a href="#probability-review" id="toc-probability-review" class="nav-link" data-scroll-target="#probability-review">Probability Review</a>
  <ul class="collapse">
  <li><a href="#population-means-and-variances-as-expectations" id="toc-population-means-and-variances-as-expectations" class="nav-link" data-scroll-target="#population-means-and-variances-as-expectations">Population Means and Variances as Expectations</a></li>
  <li><a href="#subpopulations-and-conditioning" id="toc-subpopulations-and-conditioning" class="nav-link" data-scroll-target="#subpopulations-and-conditioning">Subpopulations and Conditioning</a></li>
  <li><a href="#about-conditional-expectations-and-variances" id="toc-about-conditional-expectations-and-variances" class="nav-link" data-scroll-target="#about-conditional-expectations-and-variances">About Conditional Expectations and Variances</a></li>
  </ul></li>
  <li><a href="#working-with-expectations" id="toc-working-with-expectations" class="nav-link" data-scroll-target="#working-with-expectations">Working with Expectations</a>
  <ul class="collapse">
  <li><a href="#sec-linearity" id="toc-sec-linearity" class="nav-link" data-scroll-target="#sec-linearity">Linearity</a></li>
  <li><a href="#sec-factorization" id="toc-sec-factorization" class="nav-link" data-scroll-target="#sec-factorization">Expectations of Products Factor into Products of Expectations</a></li>
  <li><a href="#the-law-of-iterated-expectations" id="toc-the-law-of-iterated-expectations" class="nav-link" data-scroll-target="#the-law-of-iterated-expectations">The Law of Iterated Expectations</a></li>
  <li><a href="#sec-iterated-iterated" id="toc-sec-iterated-iterated" class="nav-link" data-scroll-target="#sec-iterated-iterated">The Law of Iterated Iterated Expectations</a></li>
  <li><a href="#sec-irrelevance" id="toc-sec-irrelevance" class="nav-link" data-scroll-target="#sec-irrelevance">Irrelevance of independent conditioning variables</a></li>
  <li><a href="#the-indicator-trick" id="toc-the-indicator-trick" class="nav-link" data-scroll-target="#the-indicator-trick">The Indicator Trick</a></li>
  </ul></li>
  <li><a href="#unbiasedness" id="toc-unbiasedness" class="nav-link" data-scroll-target="#unbiasedness">Unbiasedness</a>
  <ul class="collapse">
  <li><a href="#a-sample-mean-is-unbiased" id="toc-a-sample-mean-is-unbiased" class="nav-link" data-scroll-target="#a-sample-mean-is-unbiased">A Sample Mean is Unbiased</a></li>
  <li><a href="#a-subsample-mean-is-unbiased" id="toc-a-subsample-mean-is-unbiased" class="nav-link" data-scroll-target="#a-subsample-mean-is-unbiased">A Subsample Mean is Unbiased</a></li>
  <li><a href="#differences-in-subsample-means" id="toc-differences-in-subsample-means" class="nav-link" data-scroll-target="#differences-in-subsample-means">Differences in Subsample Means</a></li>
  <li><a href="#implications-of-unbiasedness" id="toc-implications-of-unbiasedness" class="nav-link" data-scroll-target="#implications-of-unbiasedness">Implications of Unbiasedness</a></li>
  </ul></li>
  <li><a href="#spread" id="toc-spread" class="nav-link" data-scroll-target="#spread">Spread</a>
  <ul class="collapse">
  <li><a href="#the-question" id="toc-the-question" class="nav-link" data-scroll-target="#the-question">The Question</a></li>
  <li><a href="#spread-within-and-between-groups" id="toc-spread-within-and-between-groups" class="nav-link" data-scroll-target="#spread-within-and-between-groups">Spread Within and Between Groups</a></li>
  <li><a href="#the-law-of-total-variance" id="toc-the-law-of-total-variance" class="nav-link" data-scroll-target="#the-law-of-total-variance">The Law of Total Variance</a></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding">Check Your Understanding</a></li>
  <li><a href="#the-variance-of-the-sample-mean" id="toc-the-variance-of-the-sample-mean" class="nav-link" data-scroll-target="#the-variance-of-the-sample-mean">The Variance of the Sample Mean</a></li>
  <li><a href="#sec-conditional-factorization" id="toc-sec-conditional-factorization" class="nav-link" data-scroll-target="#sec-conditional-factorization">Conditional Expectations of Products Factor</a></li>
  <li><a href="#the-variance-of-the-subsample-mean" id="toc-the-variance-of-the-subsample-mean" class="nav-link" data-scroll-target="#the-variance-of-the-subsample-mean">The Variance of the Subsample Mean</a></li>
  <li><a href="#step-1.-total-variance" id="toc-step-1.-total-variance" class="nav-link" data-scroll-target="#step-1.-total-variance">Step 1. Total Variance</a></li>
  <li><a href="#step-2.-centering-and-squaring" id="toc-step-2.-centering-and-squaring" class="nav-link" data-scroll-target="#step-2.-centering-and-squaring">Step 2. Centering and Squaring</a></li>
  <li><a href="#step-3.-taking-expectations-term-by-term" id="toc-step-3.-taking-expectations-term-by-term" class="nav-link" data-scroll-target="#step-3.-taking-expectations-term-by-term">Step 3. Taking Expectations Term-by-Term</a>
  <ul class="collapse">
  <li><a href="#squared-terms-ij" id="toc-squared-terms-ij" class="nav-link" data-scroll-target="#squared-terms-ij">Squared Terms (<span class="math inline">\(i=j\)</span>)</a></li>
  <li><a href="#cross-terms-ineq-j" id="toc-cross-terms-ineq-j" class="nav-link" data-scroll-target="#cross-terms-ineq-j">Cross-Terms (<span class="math inline">\(i\neq j\)</span>)</a></li>
  </ul></li>
  <li><a href="#step-4.-putting-the-pieces-together" id="toc-step-4.-putting-the-pieces-together" class="nav-link" data-scroll-target="#step-4.-putting-the-pieces-together">Step 4. Putting the Pieces Together</a></li>
  <li><a href="#the-variance-of-differences-in-means" id="toc-the-variance-of-differences-in-means" class="nav-link" data-scroll-target="#the-variance-of-differences-in-means">The Variance of <strong>Differences in Means</strong></a></li>
  <li><a href="#sec-estimating-variance" id="toc-sec-estimating-variance" class="nav-link" data-scroll-target="#sec-estimating-variance">Estimating the Variance</a></li>
  </ul></li>
  <li><a href="#case-study" id="toc-case-study" class="nav-link" data-scroll-target="#case-study">Case Study</a>
  <ul class="collapse">
  <li><a href="#code" id="toc-code" class="nav-link" data-scroll-target="#code">Code</a></li>
  <li><a href="#the-national-supported-work-demonstration" id="toc-the-national-supported-work-demonstration" class="nav-link" data-scroll-target="#the-national-supported-work-demonstration">The National Supported Work Demonstration</a></li>
  <li><a href="#activities" id="toc-activities" class="nav-link" data-scroll-target="#activities">Activities</a></li>
  </ul></li>
  <li><a href="#appendix-additional-figures" id="toc-appendix-additional-figures" class="nav-link" data-scroll-target="#appendix-additional-figures">Appendix: Additional Figures</a>
  <ul class="collapse">
  <li><a href="#the-social-pressure-letter" id="toc-the-social-pressure-letter" class="nav-link" data-scroll-target="#the-social-pressure-letter">The Social Pressure Letter</a></li>
  </ul></li>
  <li><a href="#sec-proving-total-variance" id="toc-sec-proving-total-variance" class="nav-link" data-scroll-target="#sec-proving-total-variance">Appendix: Proving the Law of Total Variance</a>
  <ul class="collapse">
  <li><a href="#starting-point-interpreting-variance-as-excess" id="toc-starting-point-interpreting-variance-as-excess" class="nav-link" data-scroll-target="#starting-point-interpreting-variance-as-excess">Starting Point: Interpreting Variance as Excess</a></li>
  <li><a href="#equivalence-proof" id="toc-equivalence-proof" class="nav-link" data-scroll-target="#equivalence-proof">Equivalence Proof</a></li>
  <li><a href="#conditional-variance-as-excess" id="toc-conditional-variance-as-excess" class="nav-link" data-scroll-target="#conditional-variance-as-excess">Conditional Variance as Excess</a></li>
  <li><a href="#proof-1" id="toc-proof-1" class="nav-link" data-scroll-target="#proof-1">Proof</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../part1.html">One and Two-Sample Problems</a></li><li class="breadcrumb-item"><a href="../lectures/Lecture6.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Comparing Two Groups</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Comparing Two Groups</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="examples-and-introduction" class="level1 page-columns page-full">
<h1>Examples and Introduction</h1>
<section id="black-vs.-non-black-voters-in-ga" class="level2">
<h2 class="anchored" data-anchor-id="black-vs.-non-black-voters-in-ga"><span class="groupb">Black</span> vs.&nbsp;<span class="groupa">non-Black</span> Voters in GA</h2>
<div class="hidden">
$$ \newcommand{X}{} \newcommand{Y}{}
<p>$$</p>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-2-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><span class="math display">\[
\small{
\begin{array}{r|rr|rr|r|rr|rrrrr}
\text{call} &amp;  1  &amp; &amp; 2  &amp; &amp; \dots &amp; 625  &amp; &amp; &amp; &amp; &amp; &amp; \\
\text{question}  &amp; X_1 &amp; Y_1 &amp;  X_2 &amp; Y_2 &amp; \dots &amp;  X_{625} &amp; Y_{625} &amp; \overline{X}_{625} &amp; \overline{Y}_{625} &amp;\frac{\sum_{i:X_i=0} Y_i}{\sum_{i:X_i=0} 1} &amp; \frac{\sum_{i:X_i=1} Y_i}{\sum_{i:X_i=1} 1} &amp; \text{difference} \\
\text{outcome}    &amp;  \underset{\textcolor{gray}{x_{869369}}}{\textcolor[RGB]{248,118,109}{0}} &amp; \underset{\textcolor{gray}{y_{869369}}}{\textcolor[RGB]{248,118,109}{1}}
                  &amp; \underset{\textcolor{gray}{x_{4428455}}}{\textcolor[RGB]{0,191,196}{1}} &amp; \underset{\textcolor{gray}{y_{4428455}}}{\textcolor[RGB]{0,191,196}{1}}
                  &amp; \dots
                  &amp; \underset{\textcolor{gray}{x_{1268868}}}{\textcolor[RGB]{248,118,109}{0}} &amp; \underset{\textcolor{gray}{y_{1268868}}}{\textcolor[RGB]{248,118,109}{1}}
                  &amp; 0.28 &amp; 0.68 &amp; \textcolor[RGB]{248,118,109}{0.68} &amp; \textcolor[RGB]{0,191,196}{0.69}
                  &amp; 0.01 \\
\end{array}
}
\]</span></p>
</section>
<section id="recipients-of-threatening-letters-vs.-others-in-mi" class="level2">
<h2 class="anchored" data-anchor-id="recipients-of-threatening-letters-vs.-others-in-mi"><span class="groupb">Recipients of Threatening Letters</span> vs.&nbsp;<span class="groupa">Others</span> in MI</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-social-pressure" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-social-pressure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lecture6_files/figure-html/fig-social-pressure-1.svg" id="fig-social-pressure" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-social-pressure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.1
</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>The green dots are people who received a letter pressuring them to vote. <a href="#fig-social-pressure-letter" class="quarto-xref">Figure&nbsp;<span>20.1</span></a>.</li>
<li>The red dots are people who didn’t.</li>
</ul>
</section>
<section id="residents-with-vs.-without-4-year-degrees-in-ca" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="residents-with-vs.-without-4-year-degrees-in-ca"><span class="groupb">Residents With</span> vs.&nbsp;<span class="groupa">Without</span> 4-Year Degrees in CA</h2>
<div class="columns">
<div class="column">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture6_files/figure-html/map-sample-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</div><div class="column">
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">income</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">education</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">county</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; background-color: rgba(248, 118, 109, 255) !important;">1</td>
<td style="text-align: left; background-color: rgba(248, 118, 109, 255) !important;">$55k</td>
<td style="text-align: right; background-color: rgba(248, 118, 109, 255) !important;">13</td>
<td style="text-align: left; background-color: rgba(248, 118, 109, 255) !important;">orange</td>
</tr>
<tr class="even">
<td style="text-align: left; background-color: rgba(248, 118, 109, 255) !important;">2</td>
<td style="text-align: left; background-color: rgba(248, 118, 109, 255) !important;">$25k</td>
<td style="text-align: right; background-color: rgba(248, 118, 109, 255) !important;">13</td>
<td style="text-align: left; background-color: rgba(248, 118, 109, 255) !important;">LA</td>
</tr>
<tr class="odd">
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">3</td>
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">$44k</td>
<td style="text-align: right; background-color: rgba(0, 191, 196, 255) !important;">16</td>
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">san joaquin</td>
</tr>
<tr class="even">
<td style="text-align: left; background-color: rgba(248, 118, 109, 255) !important;">4</td>
<td style="text-align: left; background-color: rgba(248, 118, 109, 255) !important;">$22k</td>
<td style="text-align: right; background-color: rgba(248, 118, 109, 255) !important;">14</td>
<td style="text-align: left; background-color: rgba(248, 118, 109, 255) !important;">orange</td>
</tr>
<tr class="odd">
<td style="text-align: left;">⋮</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">2271</td>
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">$150k</td>
<td style="text-align: right; background-color: rgba(0, 191, 196, 255) !important;">16</td>
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">stanislaus</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</div>
<ul>
<li>In these examples, our sample was drawn with replacement from some population. Or we’re pretending it was.</li>
<li>In this one, it’s the population of all California residents between 25 and 35 with at least an 8th grade education.</li>
</ul>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>The locations shown on the map are made up. They’re not the actual locations of the people in the sample.<br>
The survey includes some location information for some people, but as you can see in the table, not for everyone.</p>
</div></div></section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-5-1.svg" class="img-fluid"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-5-2.svg" class="img-fluid"></p>
</div>
</div>
</div>
<div class="columns">
<div class="column">
<section id="population" class="level3">
<h3 class="anchored" data-anchor-id="population">Population</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">income</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">education</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">county</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">1</td>
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">$22k</td>
<td style="text-align: right; background-color: rgba(0, 191, 196, 255) !important;">18</td>
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">unknown</td>
</tr>
<tr class="even">
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">2</td>
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">$0k</td>
<td style="text-align: right; background-color: rgba(0, 191, 196, 255) !important;">16</td>
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">solano</td>
</tr>
<tr class="odd">
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">3</td>
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">$98k</td>
<td style="text-align: right; background-color: rgba(0, 191, 196, 255) !important;">16</td>
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">LA</td>
</tr>
<tr class="even">
<td style="text-align: left;">⋮</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">5677500</td>
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">$116k</td>
<td style="text-align: right; background-color: rgba(0, 191, 196, 255) !important;">18</td>
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">unknown</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
</div><div class="column">
<section id="sample" class="level3">
<h3 class="anchored" data-anchor-id="sample">Sample</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">income</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">education</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">county</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; background-color: rgba(248, 118, 109, 255) !important;">1</td>
<td style="text-align: left; background-color: rgba(248, 118, 109, 255) !important;">$55k</td>
<td style="text-align: right; background-color: rgba(248, 118, 109, 255) !important;">13</td>
<td style="text-align: left; background-color: rgba(248, 118, 109, 255) !important;">orange</td>
</tr>
<tr class="even">
<td style="text-align: left; background-color: rgba(248, 118, 109, 255) !important;">2</td>
<td style="text-align: left; background-color: rgba(248, 118, 109, 255) !important;">$25k</td>
<td style="text-align: right; background-color: rgba(248, 118, 109, 255) !important;">13</td>
<td style="text-align: left; background-color: rgba(248, 118, 109, 255) !important;">LA</td>
</tr>
<tr class="odd">
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">3</td>
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">$44k</td>
<td style="text-align: right; background-color: rgba(0, 191, 196, 255) !important;">16</td>
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">san joaquin</td>
</tr>
<tr class="even">
<td style="text-align: left;">⋮</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">2271</td>
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">$150k</td>
<td style="text-align: right; background-color: rgba(0, 191, 196, 255) !important;">16</td>
<td style="text-align: left; background-color: rgba(0, 191, 196, 255) !important;">stanislaus</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
</div>
</div>
<p>For illustration, I’ve made up a fake population that looks like a bigger version of the sample.</p>
</section>
<section id="our-estimator-and-target" class="level2">
<h2 class="anchored" data-anchor-id="our-estimator-and-target">Our Estimator and Target</h2>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-8-1.svg" class="img-fluid"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-8-2.svg" class="img-fluid"></p>
</div>
</div>
</div>
<div class="columns">
<div class="column">
<section id="estimation-target" class="level3">
<h3 class="anchored" data-anchor-id="estimation-target">Estimation Target</h3>
<p><span class="math display">\[
\begin{aligned}
\mu(1) - \mu(0) \qfor \mu(x)
&amp;= \frac{1}{m_x}\sum_{j:x_j = x } y_j \\
\qqtext{ where } \quad m_x &amp;= \sum_{j:x_j=x} 1
\end{aligned}
\]</span></p>
</section>
</div><div class="column">
<section id="estimator" class="level3">
<h3 class="anchored" data-anchor-id="estimator">Estimator</h3>
<p><span class="math display">\[
\begin{aligned}
\hat\mu(1) - \hat\mu(0)
\qfor \hat\mu(x) &amp;= \frac{1}{N_x}\sum_{i:X_i=x} Y_i \\
\qqtext{ where } \quad N_x &amp;= \sum_{i:X_i=x} 1.
\end{aligned}
\]</span></p>
</section>
</div>
</div>
</section>
<section id="is-this-estimator-good" class="level2">
<h2 class="anchored" data-anchor-id="is-this-estimator-good">Is This Estimator Good?</h2>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-10-1.svg" class="img-fluid figure-img"></p>
<figcaption>An Unbiased Estimator’s Sampling Distribution</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-10-2.svg" class="img-fluid figure-img"></p>
<figcaption>A Biased Estimator’s Sampling Distribution</figcaption>
</figure>
</div>
</div>
</div>
</div>
<ul>
<li>We want to know about our estimator’s …
<ul>
<li>bias. That’s the location of the sampling distribution relative to the <span class="target">estimation target</span>.</li>
<li>standard deviation. Roughly speaking, that determines the width of our 95% confidence intervals.</li>
</ul></li>
</ul>
</section>
</section>
<section id="probability-review" class="level1">
<h1>Probability Review</h1>
<section id="population-means-and-variances-as-expectations" class="level2">
<h2 class="anchored" data-anchor-id="population-means-and-variances-as-expectations">Population Means and Variances as Expectations</h2>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-11-1.svg" class="img-fluid"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-11-2.svg" class="img-fluid"></p>
</div>
</div>
</div>
<ul>
<li>If a random variable <span class="math inline">\(Y\)</span> is <em>equally likely</em> to be any member of a population <span class="math inline">\(y_1 \ldots y_m\)</span>, …</li>
<li>… then its expectation is the population mean <span class="math inline">\(\mu=\frac{1}{m}\sum_{j=1}^m y_j\)</span>.</li>
<li>… and its variance is the population variance <span class="math inline">\(\sigma^2 = \frac{1}{m}\sum_{j=1}^m (y_j - \mu)^2\)</span>.</li>
<li><em>Terminology.</em> When each of our observations <span class="math inline">\(Y_i\)</span> is like this, we’re <em>sampling uniformly-at-random</em>.</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
\mathop{\mathrm{E}}[Y]
&amp;= \sum_{j=1}^m \underset{\text{response}}{y_j} \times \underset{\text{probability}}{\frac{1}{m}} = \frac{1}{m}\sum_{j=1}^m y_j = \mu \\
\mathop{\mathrm{E}}[(Y-\mathop{\mathrm{E}}[Y])^2]  
&amp;= \sum_{j=1}^m \underset{\text{deviation}^2}{(y_j - \mu)^2} \times \underset{\text{probability}}{\frac{1}{m}} = \frac{1}{m}\sum_{j=1}^m (y_j - \mu)^2 = \sigma^2
\end{aligned}
\]</span></p>
</section>
<section id="subpopulations-and-conditioning" class="level2">
<h2 class="anchored" data-anchor-id="subpopulations-and-conditioning">Subpopulations and Conditioning</h2>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-12-1.svg" class="img-fluid"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-12-2.svg" class="img-fluid"></p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">Conditioning</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Conditional Probability</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">Conditional Expectation</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false">Conditional Variance</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<ul>
<li><strong>Conditioning</strong> is, in effect, a way of thinking about sampling as a two-stage process.
<ul>
<li>First, we choose the color of our dot, i.e., the value of <span class="math inline">\(X_i\)</span>, according to it frequency in the population.</li>
<li>Then, we choose a specific one of those dots, i.e.&nbsp;<span class="math inline">\(J_i\)</span>, from those with that color—with equal probability.</li>
</ul></li>
<li>Because this is just a way of thinking, each person still gets chosen with probability <span class="math inline">\(1/m\)</span>.</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
P(J_i=j) =
\begin{cases}
   \frac{m_{green}}{m} \ \times \frac{1}{m_{green}}  \ = \ \frac{1}{m} &amp; \text{if the $j$th dot is green  ($x_j=1$) } \\
    \frac{m_{red}}{m} \ \times \frac{1}{m_{red}}  \  = \ \frac{1}{m} &amp; \text{otherwise}
\end{cases}
\end{aligned}
\]</span></p>
<ul>
<li>The first stage is ‘a coin flip’ that decides whether we roll the ‘red die’ or the ‘green die’ in the second.</li>
</ul>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<ul>
<li>The <strong>Conditional Probability</strong> of <span class="math inline">\(Y_i\)</span> is the probability resulting from the second stage.
<ul>
<li><span class="math inline">\(P(Y_i=y \mid X_i=1)\)</span> is the probability distribution of <span class="math inline">\(Y_i\)</span> when we’re ‘rolling the green die’.</li>
<li><span class="math inline">\(P(Y_i=y \mid X_i=0)\)</span> is the probability distribution of <span class="math inline">\(Y_i\)</span> when we’re ‘rolling the red die’.</li>
</ul></li>
</ul>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<ul>
<li>The <strong>Conditional Expectation</strong> of <span class="math inline">\(Y_i\)</span> is the ‘second stage expected value’ in the same sense.
<ul>
<li><span class="math inline">\(\mathop{\mathrm{E}}[Y_i \mid X_i=1]\)</span> is the expected value of <span class="math inline">\(Y_i\)</span> when we’re ‘rolling the green die’.</li>
<li>It’s the mean value <span class="math inline">\(\mu(1)\)</span> of <span class="math inline">\(y_j\)</span> in the subpopulation drawn as little green dots.</li>
<li><span class="math inline">\(\mathop{\mathrm{E}}[Y_i \mid X_i=0]\)</span> is the expected value of <span class="math inline">\(Y_i\)</span> when we’re ‘rolling the red die’.</li>
<li>It’s the mean value <span class="math inline">\(\mu(0)\)</span> of <span class="math inline">\(y_j\)</span> in the subpopulation drawn as little red dots.</li>
</ul></li>
</ul>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<ul>
<li>The <strong>Conditional Variance</strong> of <span class="math inline">\(Y_i\)</span> is like this too. It’s the ‘second stage variance.’
<ul>
<li><span class="math inline">\(\mathop{\mathrm{\mathop{\mathrm{V}}}}[Y_i \mid X_i=1]\)</span> is the variance of <span class="math inline">\(Y_i\)</span> when we’re ‘rolling the green die’.</li>
<li>It’s the variance <span class="math inline">\(\sigma^2(1)\)</span> of <span class="math inline">\(y_j\)</span> in the subpopulation drawn as little green dots.</li>
<li><span class="math inline">\(\mathop{\mathrm{\mathop{\mathrm{V}}}}[Y_i \mid X_i=0]\)</span> is the variance of <span class="math inline">\(Y_i\)</span> when we’re ‘rolling the red die’.</li>
<li>It’s the variance <span class="math inline">\(\sigma^2(0)\)</span> of <span class="math inline">\(y_j\)</span> in the subpopulation drawn as little red dots.</li>
</ul></li>
</ul>
</div>
</div>
</div>
</section>
<section id="about-conditional-expectations-and-variances" class="level2">
<h2 class="anchored" data-anchor-id="about-conditional-expectations-and-variances">About Conditional Expectations and Variances</h2>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-13-1.svg" class="img-fluid"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-13-2.svg" class="img-fluid"></p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">Conditional Expectations</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Conditional Variance</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false">Conditional Variance as a Conditional Expectation</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<ol type="1">
<li>The <strong>conditional expectation function</strong> <span class="math inline">\(\mu(x)=E[Y \mid X=x]\)</span>.
<ul>
<li><span class="math inline">\(\mu\)</span> is a function; evaluated at <span class="math inline">\(x\)</span>, it’s a number. It’s not random.</li>
<li>It’s the mean of the subpopulation of people with <span class="math inline">\(X=x\)</span>.</li>
</ul></li>
<li>The conditional expectation <span class="math inline">\(\mu(X)=E[Y \mid X]\)</span>.
<ul>
<li><span class="math inline">\(\mu(X)\)</span> is the mean of a <strong>random subpopulation</strong> of people.</li>
<li>It’s the conditional expectation function <strong>evaluated at</strong> the random variable <span class="math inline">\(X\)</span>.</li>
</ul></li>
</ol>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<ol type="1">
<li>The <strong>conditional variance function</strong> <span class="math inline">\(\sigma^2(x)=E[\{Y - \mu(x)\}^2 \mid X=x]\)</span>.
<ul>
<li><span class="math inline">\(\sigma^2\)</span> is a function; evaluated at <span class="math inline">\(x\)</span>, it’s a number. It’s not random.</li>
<li>It’s the variance of the subpopulation of people with <span class="math inline">\(X=x\)</span>.</li>
</ul></li>
<li>The conditional variance <span class="math inline">\(\sigma^2(X)=E[\{Y - \mu(X)\}^2 \mid X]\)</span>.
<ul>
<li><span class="math inline">\(\sigma^2(X)\)</span> is the variance of a <strong>random subpopulation</strong> of people.</li>
<li>It’s the conditional variance function <strong>evaluated at</strong> the random variable <span class="math inline">\(X\)</span>.</li>
</ul></li>
</ol>
<ul>
<li>This is like what happens with conditional expectations because it is one.</li>
<li>It’s the conditional expectation of some random variable. What random variable?</li>
</ul>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<ul>
<li>It’s the conditional expectation of the square of <span class="math inline">\(\textcolor[RGB]{0,0,255}{Y-\mu(X)}\)</span>, a <em>conditionally centered</em> version of <span class="math inline">\(Y\)</span>.</li>
</ul>
<p><span class="math display">\[
\mathop{\mathrm{\mathop{\mathrm{V}}}}[Y \mid X] = \mathop{\mathrm{E}}[\textcolor[RGB]{0,0,255}{\{Y-\mu(X)\}}^2 \mid X] \qfor \mu(X) = \mathop{\mathrm{E}}[Y \mid X]
\]</span></p>
</div>
</div>
</div>
</section>
</section>
<section id="working-with-expectations" class="level1">
<h1>Working with Expectations</h1>
<section id="sec-linearity" class="level2">
<h2 class="anchored" data-anchor-id="sec-linearity">Linearity</h2>
<p><span class="math display">\[
\begin{aligned}
E ( a Y + b Z )
&amp;= E (aY) + E (bZ)
= aE(Y) + bE(Z) \\
&amp;\text{ for random variables $Y, Z$ and numbers $a,b$ }
\end{aligned}
\]</span></p>
<p><strong>Application</strong>. When we sample uniformly-at-random, the sample mean is unbiased.</p>
<p><span class="math display">\[
\begin{aligned}
\mathop{\mathrm{E}}[\hat\mu]
&amp;= \mathop{\mathrm{E}}\qty[\frac1n\sum_{i=1}^n Y_i] \\
&amp;= \frac1n\sum_{i=1}^n \mathop{\mathrm{E}}[Y_i]  \\
&amp;= \frac1n\sum_{i=1}^n \mu     \\
&amp;= \frac1n \times n \times \mu = \mu.
\end{aligned}
\]</span></p>
<p><strong>Conditional Version</strong>. <span class="math display">\[
\begin{aligned}
E\{ a(X) Y + b(X) Z \mid X \}
&amp;= E\{a(X)Y \mid X\} + E\{ b(X)Z \mid X\} \\
&amp;= a(X)E(Y \mid X) + b(X)E(Z \mid X) \\
&amp; \text{ for random variables $X, Y, Z$ and functions $a,b$ }
\end{aligned}
\]</span></p>
</section>
<section id="sec-factorization" class="level2">
<h2 class="anchored" data-anchor-id="sec-factorization">Expectations of Products Factor into Products of Expectations</h2>
<p><span class="math display">\[
\color{gray}
\mathop{\mathrm{E}}[\textcolor[RGB]{239,71,111}{Y}\textcolor[RGB]{17,138,178}{Z}] = \textcolor[RGB]{239,71,111}{\mathop{\mathrm{E}}[Y]}\textcolor[RGB]{17,138,178}{\mathop{\mathrm{E}}[Z]} \qqtext{when $\textcolor[RGB]{239,71,111}{Y}$ and $\textcolor[RGB]{17,138,178}{Z}$ are independent}
\]</span></p>
<p><strong>Application</strong>. When we sample with replacement, the sample mean’s variance is the population variance divided by <span class="math inline">\(n\)</span>.</p>
<p><span class="math display">\[
\color{gray}
\begin{aligned}
\mathop{\mathrm{\mathop{\mathrm{V}}}}[\hat\mu]
&amp;= \mathop{\mathrm{E}}\qty[ \qty{ \frac{1}{n}\sum_{i=1}^n Y_i - \mathop{\mathrm{E}}\qty[ \frac{1}{n}\sum_{i=1}^n Y_i ] }^2 ] \\
&amp;= \mathop{\mathrm{E}}\qty[ \qty{ \frac{1}{n}\sum_{i=1}^n (Y_i - \mathop{\mathrm{E}}[Y_i]) }^2 ]  \\
&amp;= \mathop{\mathrm{E}}\qty[ \qty{ \frac{1}{n}\sum_{i=1}^n Z_i }^2 ]
&amp;&amp; \text{ for } \ Z_i = Y_i - \mathop{\mathrm{E}}[Y_i] \\
&amp;= \mathop{\mathrm{E}}\qty[ \qty{ \textcolor[RGB]{239,71,111}{\frac{1}{n}\sum_{i=1}^n Z_i }} \times \qty{\textcolor[RGB]{17,138,178}{\frac{1}{n}\sum_{j=1}^n Z_j}} ]
&amp;&amp;\text{ with }  \mathop{\mathrm{E}}[ Z_i  ] =  \mathop{\mathrm{E}}[ Y_i  ] - \mathop{\mathrm{E}}[Y_i] = \mu - \mu = 0 \\
&amp;= \mathop{\mathrm{E}}\qty[ \frac{1}{n^2}\textcolor[RGB]{239,71,111}{\sum_{i=1}^n} \textcolor[RGB]{17,138,178}{\sum_{j=1}^n} \textcolor[RGB]{239,71,111}{Z_i} \textcolor[RGB]{17,138,178}{Z_j} ]    
&amp;&amp;\text{ and } \ \mathop{\mathrm{E}}[ Z_i^2] = \mathop{\mathrm{E}}[ \{ Y_i - \mathop{\mathrm{E}}[Y_i] \}^2 ] = \mathop{\mathrm{\mathop{\mathrm{V}}}}[Y_i] = \sigma^2 \\
&amp;= \frac{1}{n^2} \textcolor[RGB]{239,71,111}{\sum_{i=1}^n} \textcolor[RGB]{17,138,178}{\sum_{j=1}^n} \mathop{\mathrm{E}}\qty[\textcolor[RGB]{239,71,111}{Z_i} \textcolor[RGB]{17,138,178}{Z_j} ]  \\
&amp;= \frac{1}{n^2} \textcolor[RGB]{239,71,111}{\sum_{i=1}^n} \textcolor[RGB]{17,138,178}{\sum_{j=1}^n} \begin{cases}
\mathop{\mathrm{E}}[Z_i^2]=\sigma^2 &amp; \text{if } j=i \\
\textcolor[RGB]{239,71,111}{\mathop{\mathrm{E}}[Z_i]}\textcolor[RGB]{17,138,178}{\mathop{\mathrm{E}}[Z_j]} = 0 \times 0  &amp; \text{if } j\neq i \end{cases} \\
&amp;= \frac{1}{n^2} \textcolor[RGB]{239,71,111}{\sum_{i=1}^n} \sigma^2 =  \frac{1}{n^2} \times n \times \sigma^2 = \frac{\sigma^2}{n}
\end{aligned}
\]</span></p>
</section>
<section id="the-law-of-iterated-expectations" class="level2">
<h2 class="anchored" data-anchor-id="the-law-of-iterated-expectations">The Law of Iterated Expectations</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">A Tiny Example</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">A Realistic Example</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-15-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-16-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p><span class="math display">\[
\mathop{\mathrm{E}}[Y] = \mathop{\mathrm{E}}\qty[ \mathop{\mathrm{E}}( Y \mid X ) ] \quad \text{ for any random variables $X, Y$}
\]</span></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">A Tiny Example</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">A Realistic Example</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="columns">
<div class="column">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(p\)</span></th>
<th><span class="math inline">\(X_i\)</span></th>
<th><span class="math inline">\(\mathop{\mathrm{E}}[Y_i \mid X_i]\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\frac{3}{6}\)</span></td>
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(1\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\frac{3}{6}\)</span></td>
<td><span class="math inline">\(1\)</span></td>
<td><span class="math inline">\(1.25\)</span></td>
</tr>
</tbody>
</table>
</div><div class="column">
<p>What is <span class="math inline">\(\mathop{\mathrm{E}}[Y_i]\)</span>?</p>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="columns">
<div class="column">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(p\)</span></th>
<th><span class="math inline">\(X_i\)</span></th>
<th><span class="math inline">\(\mathop{\mathrm{E}}[Y_i \mid X_i]\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(0.58\)</span></td>
<td>0</td>
<td><span class="math inline">\(31.22K\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(0.42\)</span></td>
<td>1</td>
<td><span class="math inline">\(72.35K\)</span></td>
</tr>
</tbody>
</table>
</div><div class="column">
<p>What is <span class="math inline">\(\mathop{\mathrm{E}}[Y_i]\)</span>?</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-iterated-iterated" class="level2">
<h2 class="anchored" data-anchor-id="sec-iterated-iterated">The Law of Iterated Iterated Expectations<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true">A Tiny Example</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false">Annotated</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-18-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-19-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p><span class="math display">\[
\mathop{\mathrm{E}}\qty[Y \mid X] = \mathop{\mathrm{E}}\qty[ \ \mathop{\mathrm{E}}[Y \mid W, X] \ \mid X] \quad \text{ for any random variables $W, X, Y$}
\]</span></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true">What It Is</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false">What It Says</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-3" role="tab" aria-controls="tabset-6-3" aria-selected="false">An Exercise</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-4" role="tab" aria-controls="tabset-6-4" aria-selected="false">Solution</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<ul>
<li>This says the law of iterated expectations works when we’re one stage into ‘3 stage sampling’.</li>
<li>It’s the law of iterated expectations for the probability distribution we get when …
<ul>
<li>We’ve flipped ‘color coin’ to choose <span class="math inline">\(X\)</span>.</li>
<li>But we haven’t flipped the ‘shape coin’ to choose <span class="math inline">\(W\)</span>.</li>
</ul></li>
</ul>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<ul>
<li>It says that if we want to calculate the expectation of <span class="math inline">\(Y\)</span> given a column <span class="math inline">\(X\)</span>, we can …
<ul>
<li>First average over <span class="math inline">\(Y\)</span> given a column <span class="math inline">\(X\)</span> <em>and</em> a shape <span class="math inline">\(W\)</span> to get a random variable taking on <span class="math inline">\(4\)</span> values.</li>
<li>Then average that over the shape <span class="math inline">\(W\)</span> to get a random variable taking on only <span class="math inline">\(2\)</span> values.</li>
</ul></li>
</ul>
</div>
<div id="tabset-6-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-3-tab">
<ul>
<li>Suppose we’re sampling with replacement from the tiny population above.</li>
</ul>
<ol type="1">
<li>Annotate the plot to show the function versions of <span class="math inline">\(\mathop{\mathrm{E}}[Y\mid W, X]\)</span> and <span class="math inline">\(\mathop{\mathrm{E}}[Y\mid X]\)</span>.</li>
<li>Make a table describing the random variable <span class="math inline">\(\mathop{\mathrm{E}}[Y\mid W, X]\)</span></li>
<li>Marginalize to get a table describing <span class="math inline">\(\mathop{\mathrm{E}}[Y\mid X]\)</span>.</li>
<li>Marginalize again to get the number <span class="math inline">\(\mathop{\mathrm{E}}[Y]\)</span>.</li>
</ol>
</div>
<div id="tabset-6-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-4-tab">
<div class="columns">
<div class="column" style="width:40%;">
<section id="mathopmathrmey-mid-w-x" class="level3">
<h3 class="anchored" data-anchor-id="mathopmathrmey-mid-w-x"><span class="math inline">\(\mathop{\mathrm{E}}[Y \mid W, X]\)</span></h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(p\)</span></th>
<th><span class="math inline">\(W\)</span></th>
<th><span class="math inline">\(X\)</span></th>
<th><span class="math inline">\(\mathop{\mathrm{E}}[Y \mid W, X]\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\frac{3}{12}\)</span></td>
<td>●</td>
<td><span class="groupa">0</span></td>
<td><span class="math inline">\(1\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\frac{3}{12}\)</span></td>
<td>▲</td>
<td><span class="groupa">0</span></td>
<td><span class="math inline">\(1.75\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\frac{3}{12}\)</span></td>
<td>●</td>
<td><span class="groupb">1</span></td>
<td><span class="math inline">\(1.25\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\frac{3}{12}\)</span></td>
<td>▲</td>
<td><span class="groupb">1</span></td>
<td><span class="math inline">\(2\)</span></td>
</tr>
</tbody>
</table>
<p>The function is the gray ● and ▲ in the plot.</p>
</section>
</div><div class="column" style="width:40%;">
<section id="mathopmathrmey-mid-x" class="level3">
<h3 class="anchored" data-anchor-id="mathopmathrmey-mid-x"><span class="math inline">\(\mathop{\mathrm{E}}[Y \mid X]\)</span></h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(p\)</span></th>
<th><span class="math inline">\(X\)</span></th>
<th><span class="math inline">\(\mathop{\mathrm{E}}[Y \mid X]\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\frac{6}{12}\)</span></td>
<td><span class="groupa">0</span></td>
<td><span class="math inline">\(1.375\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\frac{6}{12}\)</span></td>
<td><span class="groupb">1</span></td>
<td><span class="math inline">\(1.625\)</span></td>
</tr>
</tbody>
</table>
<p>The function is the gray ◆ in the plot.</p>
</section>
</div><div class="column" style="width:20%;">
<section id="mathopmathrmey" class="level3">
<h3 class="anchored" data-anchor-id="mathopmathrmey"><span class="math inline">\(\mathop{\mathrm{E}}[Y]\)</span></h3>
<p>1.5</p>
<p>That’s midway<br>
between the<br>
two diamonds.</p>
</section>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-irrelevance" class="level2">
<h2 class="anchored" data-anchor-id="sec-irrelevance">Irrelevance of independent conditioning variables</h2>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-20-1.svg" class="img-fluid"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-20-2.svg" class="img-fluid"></p>
</div>
</div>
</div>
<p><span class="math display">\[ \mathop{\mathrm{E}}[ \textcolor[RGB]{17,138,178}{Y} \mid \textcolor[RGB]{17,138,178}{X}, \textcolor[RGB]{239,71,111}{X'} ] = \textcolor[RGB]{17,138,178}{\mathop{\mathrm{E}}[ Y \mid X ]} \quad \text{ when $X'$ is independent of $X,Y$ } \]</span></p>
<p><strong>Application.</strong> When we sample with replacement, the conditional expectation of <span class="math inline">\(Y_i\)</span> given <span class="math inline">\(X_1 \ldots X_n\)</span> is the conditional mean of <span class="math inline">\(Y_i\)</span> given <span class="math inline">\(X_i\)</span> alone.</p>
<p><span class="math display">\[
\mathop{\mathrm{E}}[Y_i \mid X_1 \ldots X_n] = \mathop{\mathrm{E}}[Y_i \mid X_i] = \mu(X_i) \qqtext{ when $(X_1, Y_1) \ldots (X_n, Y_n)$ are independent.}
\]</span></p>
</section>
<section id="the-indicator-trick" class="level2">
<h2 class="anchored" data-anchor-id="the-indicator-trick">The Indicator Trick</h2>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-21-1.svg" class="img-fluid"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-21-2.svg" class="img-fluid"></p>
</div>
</div>
</div>
<p><span class="math display">\[
1_{=x}(X)\mu(X) =
\begin{cases}
1 \times \mu(X)  &amp; \text{ when } X=x \\
0 \times \mu(X)  &amp; \text{ when } X \neq x
\end{cases}
=
\begin{cases}
1 \times \mu(x) &amp; \text{ when } X=x \\
0 \times \mu(x) &amp; \text{ when } X \neq x
\end{cases}
=
1_{=x}(X)\mu(x)
\]</span></p>
<p><strong>Application.</strong></p>
<p><span class="math display">\[
\mathop{\mathrm{E}}[1_{=x}(X)\mu(X)] = \mathop{\mathrm{E}}[ 1_{X=x} \mu(x) ] = \mu(x) \mathop{\mathrm{E}}[1_{=x}(X)] = \mu(x) \times P(X=x)
\]</span></p>
</section>
</section>
<section id="unbiasedness" class="level1">
<h1>Unbiasedness</h1>
<section id="a-sample-mean-is-unbiased" class="level2">
<h2 class="anchored" data-anchor-id="a-sample-mean-is-unbiased">A Sample Mean is Unbiased</h2>
<p><strong>Claim.</strong> When we sample uniformly-at-random, the sample mean is an unbiased estimator of the population mean. <span class="math display">\[ \mathop{\mathrm{E}}[\hat\mu] = \mu \]</span></p>
<p>We proved this earlier today using linearity of expectations. See <a href="#sec-linearity" class="quarto-xref"><span>Section 16.1</span></a>.</p>
</section>
<section id="a-subsample-mean-is-unbiased" class="level2">
<h2 class="anchored" data-anchor-id="a-subsample-mean-is-unbiased">A Subsample Mean is Unbiased</h2>
<p><strong>Claim.</strong> When we sample with replacement, a subsample mean is an unbiased estimator of the corresponding subpopulation mean. <span class="math display">\[ \mathop{\mathrm{E}}[\hat\mu(1)] = \mu(1) \]</span></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true">Proof Sketch</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false">How to Write Subsample Means</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-3" role="tab" aria-controls="tabset-7-3" aria-selected="false">Proof</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<ul>
<li>Use the Law of Iterated Expectations, conditioning on <span class="math inline">\(X_1 \ldots X_n\)</span>.</li>
<li>Then the linearity of conditional expectations to push the conditional expectation into the sum.</li>
<li>Then irrelevance of independent conditioning variables to write things in terms of the <em>random variable</em> <span class="math inline">\(\mu(X_i)\)</span><br>
</li>
<li>Then the <strong>indicator trick</strong>. What’s <span class="math inline">\(1_{=1}(X_i) \mu(X_i)\)</span>? How is it related to <span class="math inline">\(\mu(1)\)</span>?</li>
</ul>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<p><span class="math display">\[
\hat\mu(1) = \frac{\sum_{i:X_i=1} Y_i}{\sum_{i:X_i=1} 1} = \frac{\sum_{i=1}^{n} 1_{=1}(X_i) Y_{i}}{\sum_{i=1}^{n} 1_{=1}(X_i)}
\]</span></p>
<ul>
<li>It’s easy to make mistakes using <em>linearity of expectations</em> when we’re summing over a subsample.
<ul>
<li>Can we or can we not ‘push’ or ‘pull’ and expectation through a sum …</li>
<li>… when the terms in that sum depend on the value of a random variable?</li>
</ul></li>
<li>To make this a lot more obvious, we can rewrite these as sums over the whole sample.
<ul>
<li>Instead of ‘excluding’ the terms where <span class="math inline">\(X_i=0\)</span>, we ‘make them zero’ by multiplying in the indicator <span class="math inline">\(1_{=1}(X_i)\)</span>.</li>
<li>Then, of course we can distribute expectations through the sum.</li>
<li>The question becomes whether we can ‘pull out’ the indicator.</li>
<li>And we have a rule for that. We can do it if we’re conditioning on <span class="math inline">\(X_i\)</span>.</li>
</ul></li>
<li>When we write a subsample mean, we can do that …
<ul>
<li>in the numerator, the sum of observations in the subsample.</li>
<li>in the denominator, the number of those terms, which is a <em>sum of ones</em> over the subsample.</li>
</ul></li>
</ul>
</div>
<div id="tabset-7-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-3-tab">
<ul>
<li>We’re actually going to show something stronger.
<ul>
<li>We’ll show that it’s unbiased <em>conditional on</em> the covariates <span class="math inline">\(X_1 \ldots X_n\)</span>.</li>
<li>This implies unbiasedness in the usual sense via the law of iterated expectations.</li>
</ul></li>
</ul>
<p><span class="math display">\[
\begin{aligned}
\mathop{\mathrm{E}}[\hat\mu(1) \mid X_1 \ldots X_n]
&amp;=\mathop{\mathrm{E}}\qty[\frac{\sum_{i=1}^{n} 1_{=1}(X_i) Y_{i}}{\sum_{i=1}^{n} 1_{=1}(X_i)} \mid X_1 \ldots X_n] \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{via linearity. All the indicators (and their sum) are functions of $X_1\ldots X_n$.}}{=}
\frac{\sum_{i=1}^{n} 1_{=1}(X_i) \mathop{\mathrm{E}}\qty{ Y_{i} \mid X_1 \ldots X_n}}{\sum_{i=1}^{n}1_{=1}(X_i)} \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{via irrelevance of independent conditioning variables. $(X_i,Y_i)$ are independent of the other $X$s.}}{=}
\frac{\sum_{i=1}^{n} 1_{=1}(X_i) \mathop{\mathrm{E}}\qty{ Y_{i} \mid X_i}}{\sum_{i=1}^{n}1_{=1}(X_i)} \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{This is just a change of notation, as $\mu(X_i)=\mathop{\mathrm{E}}[Y_i \mid X_i]$, but it makes it easier to understand what happens next.}}{=}
\frac{\sum_{i=1}^{n} 1_{=1}(X_i) \mu(X_i)}{\sum_{i=1}^{n}1_{=1}(X_i)} \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{via the indicator trick.}}{=}\frac{\sum_{i=1}^{n}1_{=1}(X_i) \mu(1)}{\sum_{i=1}^{n}1_{=1}(X_{i})} \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{via linearity}}{=} \mu(1) \ \frac{\sum_{i=1}^{n} 1_{=1}(X_i) }{\sum_{i=1}^{n}1_{=1}(X_{i})} = \mu(1)
\end{aligned}
\]</span></p>
<p>and therefore, using the law of iterated expectations,</p>
<p><span class="math display">\[
\mathop{\mathrm{E}}[\hat\mu(1)] = \mathop{\mathrm{E}}\qty[\mathop{\mathrm{E}}\qty[\hat\mu(1) \mid X_1 \ldots X_n]] = \mathop{\mathrm{E}}[\mu(1)] = \mu(1)
\]</span></p>
</div>
</div>
</div>
</section>
<section id="differences-in-subsample-means" class="level2">
<h2 class="anchored" data-anchor-id="differences-in-subsample-means">Differences in Subsample Means</h2>
<p><strong>Claim.</strong> A difference in subsample means is unbiased for the corresponding difference in subpopulation means.</p>
<p><span class="math display">\[
\mathop{\mathrm{E}}[\hat\mu(1) - \hat\mu(0)] = \mu(1) - \mu(0)
\]</span></p>
<p><strong>Why?</strong></p>
<div class="fragment">
<p>This follows from the linearity of expectations and unbiasedness of the subsample means.</p>
<p><span class="math display">\[
\mathop{\mathrm{E}}[\hat\mu(1) - \hat\mu(0)] = \mathop{\mathrm{E}}[\hat\mu(1)] - \mathop{\mathrm{E}}[\hat\mu(0)] =  \mu(1) - \mu(0)
\]</span></p>
</div>
<p><strong>Is it conditionally unbiased?</strong></p>
<div class="fragment">
<p>It is. That follows from linearity of conditional expectations and conditional unbiasedness of the subsample means.</p>
<p><span class="math display">\[
\mathop{\mathrm{E}}[\hat\mu(1) - \hat\mu(0) \mid X_1 \ldots X_n] = \mathop{\mathrm{E}}[\hat\mu(1) \mid X_1 \ldots X_n] - \mathop{\mathrm{E}}[\hat\mu(0) \mid X_1 \ldots X_n] =  \mu(1) - \mu(0)
\]</span></p>
</div>
</section>
<section id="implications-of-unbiasedness" class="level2">
<h2 class="anchored" data-anchor-id="implications-of-unbiasedness">Implications of Unbiasedness</h2>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-22-1.svg" class="img-fluid figure-img"></p>
<figcaption>Like this.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-22-2.svg" class="img-fluid figure-img"></p>
<figcaption>Not like this.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<ul>
<li>If we can estimate the width of its sampling distribution, we can get interval estimates with the coverage we want.</li>
<li>The question that remains is whether those interval estimates are narrow enough to be useful.</li>
</ul>
</section>
</section>
<section id="spread" class="level1">
<h1>Spread</h1>
<section id="the-question" class="level2">
<h2 class="anchored" data-anchor-id="the-question">The Question</h2>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-23-1.svg" class="img-fluid figure-img"></p>
<figcaption>Is it like this?</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-23-2.svg" class="img-fluid figure-img"></p>
<figcaption>Or like this?</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="spread-within-and-between-groups" class="level2">
<h2 class="anchored" data-anchor-id="spread-within-and-between-groups">Spread Within and Between Groups</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-24-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>You can think of there being two kinds of variation in a population.</li>
</ul>
<ol type="1">
<li>Within-group variation.
<ul>
<li>That’s illustrated above by the ‘arms’ on our subpopulation means in the plot above.</li>
<li>The arm length is, in fact, the <em>subpopulation standard deviation</em>.</li>
<li>That’s the square root of the <em>conditional variance function</em> <span class="math inline">\(\sigma^2(x) = \mathop{\mathrm{\mathop{\mathrm{V}}}}[Y \mid X=x]\)</span>.</li>
</ul></li>
<li>Between-group variation.
<ul>
<li>That’s about the difference <em>between</em> those subsample means.</li>
<li>One reasonable summary is the <em>standard deviation</em> of the subpopulation means <span class="math inline">\(\mu(x) = \mathop{\mathrm{E}}[Y \mid X=x]\)</span>.</li>
</ul></li>
</ol>
</section>
<section id="the-law-of-total-variance" class="level2">
<h2 class="anchored" data-anchor-id="the-law-of-total-variance">The Law of Total Variance</h2>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-25-1.svg" class="img-fluid"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-25-2.svg" class="img-fluid"></p>
</div>
</div>
</div>
<p><span class="math display">\[
\mathop{\mathrm{\mathop{\mathrm{V}}}}[Y] = \mathop{\mathrm{E}}\qty{\mathop{\mathrm{\mathop{\mathrm{V}}}}( Y \mid X ) } + \mathop{\mathrm{\mathop{\mathrm{V}}}}\qty{\mathop{\mathrm{E}}( Y \mid X ) }  
\]</span></p>
<ul>
<li>The Law of Total Variance breaks Variance into within-group and between-group terms.</li>
<li>It’s like the Law of Iterated Expectations, but for Variance.</li>
<li>It’s a useful way to decompose the variance of a random variable.</li>
<li>Think about where most of the variance in <span class="math inline">\(Y\)</span> is coming from in the two populations shown above.</li>
</ul>
<p>We won’t prove this, but it’s in the slides if you’re interested. See <a href="#sec-proving-total-variance" class="quarto-xref"><span>Chapter 21</span></a>.</p>
</section>
<section id="check-your-understanding" class="level2">
<h2 class="anchored" data-anchor-id="check-your-understanding">Check Your Understanding</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-26-1.svg" height="250" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Try to put the three terms into words.
<ul>
<li><span class="math inline">\(\mathop{\mathrm{\mathop{\mathrm{V}}}}[Y]\)</span> is the …</li>
<li><span class="math inline">\(\mathop{\mathrm{E}}\qty{ \mathop{\mathrm{\mathop{\mathrm{V}}}}(Y \mid X) }\)</span> is the …</li>
<li><span class="math inline">\(\mathop{\mathrm{\mathop{\mathrm{V}}}}\qty{\mathop{\mathrm{E}}( Y \mid X)}\)</span> is the …</li>
</ul></li>
<li>Do this in two ways.
<ol type="1">
<li>Using ‘Random Variables Language’,
<ul>
<li>e.g.&nbsp;‘the expected value of the conditional variance of Y given X’</li>
</ul></li>
<li>Using ‘Population Language’
<ul>
<li>e.g.&nbsp;‘the variance of income (Y) within the random subpopulation with degree status X’</li>
</ul></li>
</ol></li>
</ul>
</section>
<section id="the-variance-of-the-sample-mean" class="level2">
<h2 class="anchored" data-anchor-id="the-variance-of-the-sample-mean">The Variance of the Sample Mean</h2>
<p><strong>Claim.</strong> When we sample w/ replacement, the variance of the sample mean<br>
is the population variance divided by the number of people in the sample.</p>
<p><span class="math display">\[
\mathop{\mathrm{\mathop{\mathrm{V}}}}[\hat\mu] = \frac{\sigma^2}{n}  
\]</span></p>
<ul>
<li>We proved this earlier today using. See <a href="#sec-factorization" class="quarto-xref"><span>Section 16.2</span></a>.</li>
<li>We used, among other things, the property that expectations of products factor into products of expectations.</li>
<li>Our proof for the subsample mean will be similar with more conditioning.
<ul>
<li>We’ll use a conditional version of that we can derive using the ‘law of iterated iterated expectations’.</li>
</ul></li>
</ul>
</section>
<section id="sec-conditional-factorization" class="level2 small">
<h2 class="small anchored" data-anchor-id="sec-conditional-factorization">Conditional Expectations of Products Factor</h2>
<p>When we sample with replacement, the conditional expectation of products factors into a product of conditional expectations.</p>
<p><span class="math display">\[
\mathop{\mathrm{E}}[Y_i \ Y_j \mid X_1 \ldots X_n] = \mathop{\mathrm{E}}[Y_i \mid X_i]\mathop{\mathrm{E}}[Y_j \mid X_j] = \mu(X_i)\mu(X_j) \qqtext{ when $(X_1, Y_1) \ldots (X_n, Y_n)$ are independent.}
\]</span></p>
<p>This is a subtle application of two of our ‘laws’. <span class="math display">\[
\begin{aligned}
&amp;\mathop{\mathrm{E}}[Y \mid X] = \mathop{\mathrm{E}}[ \mathop{\mathrm{E}}\qty[Y \mid W, X] \mid X] \quad \text{ for any random variables $W, X, Y$}  
&amp;&amp; \text{Law of Iterated Iterated Expectations} \\
&amp;\mathop{\mathrm{E}}[ \textcolor[RGB]{17,138,178}{Y} \mid \textcolor[RGB]{17,138,178}{X}, \textcolor[RGB]{239,71,111}{X'} ] = \textcolor[RGB]{17,138,178}{\mathop{\mathrm{E}}[ Y \mid X ]} \quad \text{ when $X'$ is independent of $X,Y$ }
&amp;&amp; \text{Irrelevance of Independent Conditioning Variables}
\end{aligned}
\]</span></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-8-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-1" role="tab" aria-controls="tabset-8-1" aria-selected="true">The Proof</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-2" role="tab" aria-controls="tabset-8-2" aria-selected="false">The Idea Behind the Proof</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-3" role="tab" aria-controls="tabset-8-3" aria-selected="false">It’s an Odd Idea, But It Works</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-8-1-tab">
<p><span class="math display">\[
\color{gray}
\begin{aligned}
\mathop{\mathrm{E}}[ \textcolor[RGB]{239,71,111}{Y_i} \ \textcolor[RGB]{17,138,178}{Y_j} \mid X_1 \ldots X_n]
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Here's use the law of iterated iterated expectations to 'break the second stage into a second and third'}}{=}
\mathop{\mathrm{E}}[\mathop{\mathrm{E}}[\textcolor[RGB]{239,71,111}{Y_i} \ \textcolor[RGB]{17,138,178}{Y_j} \mid \textcolor[RGB]{239,71,111}{Y_i}, X_1 \ldots X_n] \mid X_1 \ldots X_n] \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Here we pull $Y_i$ out of the inner expectation (stage 3). That's justified by linearity of conditional expectations because it's a function of $\textcolor[RGB]{239,71,111}{Y_i}, X_1 \ldots X_n$, the stuff we chose in stages 1 and 2.}}{=}
\mathop{\mathrm{E}}[ \textcolor[RGB]{239,71,111}{Y_i} \ \mathop{\mathrm{E}}[\textcolor[RGB]{17,138,178}{Y_j} \mid \textcolor[RGB]{239,71,111}{Y_i}, X_1 \ldots X_n] \mid X_1 \ldots X_n] \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Here we drop the irrelevant conditioning variables from the inner expectation. In the notation above, $Y=Y_j$, $X=X_j$, and $X'=(Y_i, X_1 \ldots X_n \text{ except } X_j)$, which describes other 'calls', is independent of $(X,Y)=(X_j, Y_j)$.}}{=}
\mathop{\mathrm{E}}[\textcolor[RGB]{239,71,111}{Y_i} \ \mathop{\mathrm{E}}[\textcolor[RGB]{17,138,178}{Y_j} \mid X_j] \mid X_1 \ldots X_n] \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Here we pull $\textcolor[RGB]{17,138,178}{Y_j}$ out of the outer expectation (stage 2). That's justified by linearity of conditional expectations because it's a function of $X_1 \ldots X_n$, the stuff we chose in stage 1.}}{=}
\textcolor[RGB]{17,138,178}{\mathop{\mathrm{E}}[Y_j \mid X_j]} \ \mathop{\mathrm{E}}[\textcolor[RGB]{239,71,111}{Y_i} \mid X_1 \ldots X_n] \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Here we drop the irrelevant conditioning variables from expectation involving $\textcolor[RGB]{239,71,111}{Y_i}$. In the notation above, $Y=Y_i$, $X=X_i$, and $X'=(Y_j, X_1 \ldots X_n \text{ except } X_i)$, which describes other 'calls', is independent of $(X,Y)=(X_i, Y_i)$.}}{=}
\textcolor[RGB]{17,138,178}{\mathop{\mathrm{E}}[Y_j \mid X_j]} \ \textcolor[RGB]{239,71,111}{\mathop{\mathrm{E}}[Y_i \mid X_i]} \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{This is the same thing in different notation.}}{=}
\textcolor[RGB]{17,138,178}{\mu(X_j)} \ \textcolor[RGB]{239,71,111}{\mu(X_i)}
\end{aligned}
\]</span></p>
</div>
<div id="tabset-8-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-2-tab">
<ul>
<li>This proof is a bit stranger conceptually than it is as a matter of pushing symbols around.
<ul>
<li>You don’t have to get it conceptually if you don’t want to.</li>
<li>Sometimes it’s not worth it. But if you do want to, here’s what’s going on.</li>
</ul></li>
<li>We start out thinking about a ‘two stage’ sampling process.
<ol type="1">
<li>We flip our ‘color coin’ <span class="math inline">\(n\)</span> times to choose <span class="math inline">\(X_1 \ldots X_n\)</span>.</li>
</ol>
<ul>
<li>Those flips together are <span class="math inline">\(X\)</span> in our iterated expectations formula.</li>
</ul>
<ol start="2" type="1">
<li>We roll n times to choose <span class="math inline">\(Y_1 \ldots Y_n\)</span>.</li>
</ol>
<ul>
<li>For <span class="math inline">\(Y_i\)</span>, we roll the ‘red die’ if <span class="math inline">\(X_i=0\)</span> and the ‘green die’ if <span class="math inline">\(X_i=1\)</span>.</li>
<li>You can think of the product <span class="math inline">\(Y_i Y_j\)</span> as <span class="math inline">\(Y\)</span> in our iterated expectations formula.</li>
</ul></li>
<li>Then we use the ‘law of iterated iterated expectations’ to break that second stage into two.
<ol type="a">
<li>We roll once to choose <span class="math inline">\(Y_i\)</span>. That’s <span class="math inline">\(W\)</span> in our iterated expectations formula.</li>
<li>We roll <span class="math inline">\(n-1\)</span> times to choose the rest of <span class="math inline">\(Y_1 \ldots Y_n\)</span>.</li>
</ol></li>
<li>After that, we simplify using linearity and the irrelevance of independent conditioning variables.</li>
</ul>
</div>
<div id="tabset-8-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-3-tab">
<ul>
<li>It sound a little odd because our ‘3 stage sampling’ scheme depends on the pair <span class="math inline">\(Y_i, Y_j\)</span> we’re thinking about.
<ul>
<li>When we think about the pairs <span class="math inline">\(Y_1 Y_3\)</span> and <span class="math inline">\(Y_2 Y_3\)</span>, we’re thinking about two different ways of drawing <span class="math inline">\(Y_3\)</span>.</li>
<li>And we can’t really do both. It’s just one thing. We can’t draw it twice.</li>
</ul></li>
<li>That’s ok because we don’t really have to sample this way. It’s just a way of thinking about doing a calculation.
<ul>
<li>This is a bit like how we can think of any pair <span class="math inline">\(Y_i,Y_j\)</span> as distributed like <span class="math inline">\(Y_1,Y_2\)</span> when<br>
<a href="https://qtm285-1.github.io/assets/homework/week3-homework.html#exr-covariance-with-replacement">calculating about variance after sampling without replacement</a> in this week’s homework.</li>
<li>Ultimately, it’s about linearity. When we’re calculating the expectation of a sum,<br>
we only care about the marginal distribution of each term.</li>
<li>When that term involves only two observations, like we see in variance calculations,<br>
we can think about the random mechanism that gives us each pair separately.</li>
</ul></li>
</ul>
</div>
</div>
</div>
</section>
<section id="the-variance-of-the-subsample-mean" class="level2">
<h2 class="anchored" data-anchor-id="the-variance-of-the-subsample-mean">The Variance of the Subsample Mean</h2>
<p><strong>Claim.</strong> When we sample with replacement, the variance of a subsample mean is the<br>
<strong>expected value</strong> of the subpopulation variance divided by the number of people in the subsample. <span class="math display">\[
\mathop{\mathrm{\mathop{\mathrm{V}}}}[\hat\mu(1)] = \mathop{\mathrm{E}}\qty[ \frac{\sigma^2(1)}{N_1} ] \quad \text{ for } \quad N_1 = \sum_{i=1}^n 1_{=1}(X_i)  
\]</span></p>
<ul>
<li>This is like what we saw in the unconditional case, but with a twist.</li>
<li>The number of people in the subsample is random, so instead of <span class="math inline">\(1/n\)</span>, we have <span class="math inline">\(\mathop{\mathrm{E}}[ \frac{1}{N_1} ]\)</span>.</li>
</ul>
</section>
<section id="step-1.-total-variance" class="level2">
<h2 class="anchored" data-anchor-id="step-1.-total-variance">Step 1. Total Variance</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-27-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>We’ll start by using the Law of Total Variance, conditioning on <span class="math inline">\(X_1 \ldots X_n\)</span>.</li>
<li>And then we’ll have to calculate two terms.
<ol type="1">
<li>The expected value of the conditional variance</li>
<li>The variance of the conditional expectation <span class="math display">\[
\begin{aligned}
\mathop{\mathrm{\mathop{\mathrm{V}}}}\qty[ \hat \mu(1) ] &amp;= \underset{\color[RGB]{64,64,64}\text{within-groups term}}{\mathop{\mathrm{E}}\qty[ \mathop{\mathrm{\mathop{\mathrm{V}}}}\qty{ \hat \mu(1) \mid X_1 \ldots X_n }] } + \underset{\color[RGB]{64,64,64}\text{between-groups term}}{\mathop{\mathrm{\mathop{\mathrm{V}}}}\qty[ \mathop{\mathrm{E}}\qty{\hat \mu(1) \mid X_1 \ldots X_n} ] } \\
\end{aligned}
\]</span></li>
</ol></li>
<li>This is one place it helps to know our estimator is <em>conditionally unbiased</em>.
<ul>
<li>That conditional expectation is the constant <span class="math inline">\(\mu(1)\)</span>.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></li>
<li>So the ‘between-groups’ variance term is zero.</li>
</ul></li>
</ul>
</section>
<section id="step-2.-centering-and-squaring" class="level2">
<h2 class="anchored" data-anchor-id="step-2.-centering-and-squaring">Step 2. Centering and Squaring</h2>
<p><span class="math display">\[
\begin{aligned}
\mathop{\mathrm{\mathop{\mathrm{V}}}}\qty[ \hat \mu(1) \mid X_1 \ldots X_n ]
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Definitionally.}}{=}
\mathop{\mathrm{E}}\qty[ \qty{\hat \mu(1) - \mu(1) }^2 \mid X_1 \ldots X_n ] \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Also definitionally.}}{=}
\mathop{\mathrm{E}}\qty[ \qty{\frac{\sum_{i=1}^n 1_{=1}(X_i)Y_{i}}{\sum_{i=1}^n 1_{=1}(X_i)} - \mu(1)}^2 \mid X_1 \ldots X_n ] \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Multiplying $\mu(1)$ by $N_1/N_1$ to get a common denominator}}{=}
\mathop{\mathrm{E}}\qty[ \qty{ \frac{\sum_{i=1}^n 1_{=1}(X_i){\textcolor[RGB]{0,0,255}{\qty{Y_{i} - \mu(1)}}}}{\sum_{i=1}^n 1_{=1}(X_i)}}^2  \mid X_1 \ldots X_n ] \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{The indicator trick tells us the factors we've highlighted in \textcolor[RGB]{0,0,255}{blue} are the same.}}{=}
\mathop{\mathrm{E}}\qty[ \qty{ \frac{\sum_{i=1}^n 1_{=1}(X_i)\textcolor[RGB]{0,0,255}{Z_i}}{\sum_{i=1}^n 1_{=1}(X_i)}}^2  \mid X_1 \ldots X_n ] \qfor \textcolor[RGB]{0,0,255}{Z_i = Y_{i} - \mu(X_i)} \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Expanding the square.}}{=}
\mathop{\mathrm{E}}\qty[ \frac{\textcolor[RGB]{239,71,111}{\sum_{i=1}^n}\textcolor[RGB]{17,138,178}{\sum_{j=1}^n} \textcolor[RGB]{239,71,111}{1_{=1}(X_i)Z_i} \ \textcolor[RGB]{17,138,178}{1_{=1}(X_j)Z_j}}{\qty{\sum_{i=1}^n 1_{=1}(X_i) }^2} \mid X_1 \ldots X_n ] \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Distributing the expectation. We can pull out the denominator and the indicator in each term because they're functions of $X_1 \ldots X_n$.}}{=}
\frac{\textcolor[RGB]{239,71,111}{\sum_{i=1}^n}\textcolor[RGB]{17,138,178}{\sum_{j=1}^n} \textcolor[RGB]{239,71,111}{1_{=1}(X_i)} \textcolor[RGB]{17,138,178}{1_{=1}(X_j)}\mathop{\mathrm{E}}\qty[\textcolor[RGB]{239,71,111}{Z_i} \textcolor[RGB]{17,138,178}{Z_j} \mid X_1 \ldots X_n]  }{\qty{\sum_{i=1}^n 1_{=1}(X_i) }^2}
\end{aligned}
\]</span></p>
<p>This random variable <span class="math inline">\(Z_i\)</span> is like the one we have in the unconditional case, but conditionally.</p>
<p><span class="math display">\[
\begin{aligned}
\mathop{\mathrm{E}}[ Z_i \mid X_i ] &amp;= \mathop{\mathrm{E}}[ Y_i - \mu(X_i) \mid X_i ] = \mathop{\mathrm{E}}[ Y_i \mid X_i ] - \mu(X_i) = \mu(X_i) - \mu(X_i) &amp;&amp; \overset{\texttip{\small{\unicode{x2753}}}{It has conditional expectation zero. }}{\ } \\
\mathop{\mathrm{E}}[ Z_i^2 \mid X_i] &amp;= \mathop{\mathrm{E}}[ \{ Y_i - \mathop{\mathrm{E}}[Y_i \mid X_i] \}^2 \mid X_i] = \mathop{\mathrm{\mathop{\mathrm{V}}}}[Y_i \mid X_i]   &amp;&amp; \overset{\texttip{\small{\unicode{x2753}}}{The conditional expectation of its square is the conditional variance of $Y_i$ }}{\ }
\end{aligned}
\]</span></p>
</section>
<section id="step-3.-taking-expectations-term-by-term" class="level2">
<h2 class="anchored" data-anchor-id="step-3.-taking-expectations-term-by-term">Step 3. Taking Expectations Term-by-Term</h2>
<section id="squared-terms-ij" class="level3">
<h3 class="anchored" data-anchor-id="squared-terms-ij">Squared Terms (<span class="math inline">\(i=j\)</span>)</h3>
<p><span class="math display">\[
\begin{aligned}
\mathop{\mathrm{E}}\qty[\textcolor[RGB]{239,71,111}{Z_i}\textcolor[RGB]{17,138,178}{Z_j} \mid X_1 \ldots X_n]
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Because $i=j$}}{=}
\mathop{\mathrm{E}}\qty[ Z_i^2  \mid X_1 \ldots X_n]  \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Because $X' = (X_1 \ldots X_n \text{except} X_i)$ is independent of $X_i$ and $Y_i$.}}{=}
\mathop{\mathrm{E}}\qty[ Z_i^2  \mid X_i]  \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Definitionally}}{=}\mathop{\mathrm{\mathop{\mathrm{V}}}}[Y_i \mid X_i] = \sigma^2(X_i)
\end{aligned}
\]</span></p>
</section>
<section id="cross-terms-ineq-j" class="level3">
<h3 class="anchored" data-anchor-id="cross-terms-ineq-j">Cross-Terms (<span class="math inline">\(i\neq j\)</span>)</h3>
<p><span class="math display">\[
\begin{aligned}
\mathop{\mathrm{E}}\qty[\textcolor[RGB]{239,71,111}{Z_i} \textcolor[RGB]{17,138,178}{Z_j} \mid X_1 \ldots X_n]
&amp;\overset{\texttip{\small{\unicode{x2753}}}{This is the factorization identity we proved a few slides back.}}{=}\textcolor[RGB]{239,71,111}{\mathop{\mathrm{E}}\qty[Z_i \mid X_i]} \textcolor[RGB]{17,138,178}{\mathop{\mathrm{E}}\qty[Z_j \mid X_j]} \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Definitionally}}{=} 0 \times 0
\end{aligned}
\]</span></p>
</section>
</section>
<section id="step-4.-putting-the-pieces-together" class="level2">
<h2 class="anchored" data-anchor-id="step-4.-putting-the-pieces-together">Step 4. Putting the Pieces Together</h2>
<p><span class="math display">\[
\begin{aligned}
\mathop{\mathrm{\mathop{\mathrm{V}}}}\qty[ \hat \mu(1) \mid X_1 \ldots X_n ]
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Step 1}}{=}
\underset{\color[RGB]{64,64,64}\text{within-groups term}}{\mathop{\mathrm{E}}\qty[ \mathop{\mathrm{\mathop{\mathrm{V}}}}\qty{ \hat \mu(1) \mid X_1 \ldots X_n }] } + \underset{\color[RGB]{64,64,64}\text{between-groups term}}{ 0 } \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Step 2}}{=}
\mathop{\mathrm{E}}\qty[\frac{\textcolor[RGB]{239,71,111}{\sum_{i=1}^n}\textcolor[RGB]{17,138,178}{\sum_{j=1}^n} \textcolor[RGB]{239,71,111}{1_{=1}(X_i)} \textcolor[RGB]{17,138,178}{1_{=1}(X_j)}\mathop{\mathrm{E}}\qty[\textcolor[RGB]{239,71,111}{Z_i} \textcolor[RGB]{17,138,178}{Z_j} \mid X_1 \ldots X_n]  }{\qty{\sum_{i=1}^n 1_{=1}(X_i) }^2}] + 0 \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Step 3}}{=}
\mathop{\mathrm{E}}\qty[\frac{\textcolor[RGB]{239,71,111}{\sum_{i=1}^n 1_{=1}(X_i)} \ \sigma^2(X_i) }{\qty{\sum_{i=1}^n 1_{=1}(X_i) }^2}] \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{The indicator trick again.}}{=}
\mathop{\mathrm{E}}\qty[\frac{\textcolor[RGB]{239,71,111}{\sum_{i=1}^n 1_{=1}(X_i)} \ \sigma^2(1) }{\qty{\sum_{i=1}^n 1_{=1}(X_i) }^2}] \\
&amp;\overset{\texttip{\small{\unicode{x2753}}}{Cancelling a common factor of $N_1$ in the numerator and denominator.}}{=}
\mathop{\mathrm{E}}\qty[\frac{\sigma^2(1)}{\sum_{i=1}^n 1_{=1}(X_i) } ]
\end{aligned}
\]</span></p>
</section>
<section id="the-variance-of-differences-in-means" class="level2">
<h2 class="anchored" data-anchor-id="the-variance-of-differences-in-means">The Variance of <strong>Differences in Means</strong></h2>
<p><strong>Claim.</strong> The variance of the difference in subsample means is the <strong>sum</strong> of the variances of the subsample means. <span class="math display">\[
\mathop{\mathrm{\mathop{\mathrm{V}}}}[\hat\mu(1) - \hat\mu(0)] = \mathop{\mathrm{E}}\qty[ \frac{\sigma^2(1)}{N_1} +
\frac{\sigma^2(0)}{N_0}] \quad \text{ for } \quad N_x = \sum_{i=1}^n 1_{=x}(X_i)
\]</span></p>
<p>This’ll be a Homework Exercise.</p>
</section>
<section id="sec-estimating-variance" class="level2">
<h2 class="anchored" data-anchor-id="sec-estimating-variance">Estimating the Variance</h2>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-28-1.svg" class="img-fluid figure-img"></p>
<figcaption>The population.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-28-2.svg" class="img-fluid figure-img"></p>
<figcaption>The sample.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><span class="math display">\[
\mathop{\mathrm{\mathop{\mathrm{V}}}}[\hat\mu(1) - \hat\mu(0)] = \mathop{\mathrm{E}}\qty[ \frac{\sigma^2(1)}{N_1} +
\frac{\sigma^2(0)}{N_0}] \quad \text{ for } \quad N_x = \sum_{i=1}^n 1_{=x}(X_i)
\]</span></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-9-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-1" role="tab" aria-controls="tabset-9-1" aria-selected="true">What We Don’t Know</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-9-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-2" role="tab" aria-controls="tabset-9-2" aria-selected="false">Getting By With What We Have</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-9-1-tab">
<ul>
<li>This formula includes a few things we don’t know.</li>
<li>We don’t know the subpopulation standard deviations <span class="groupa"><span class="math inline">\(\sigma(0)\)</span></span> or <span class="groupb"><span class="math inline">\(\sigma(1)\)</span></span>.
<ul>
<li>Those are drawn in as ‘arms’ on the subpopulation means in the plot on the left.</li>
<li>That’s a fake-data plot. It’s an illustration of data we don’t really get to see.</li>
</ul></li>
<li>We also don’t know the expected values of <span class="math inline">\(1/N_1\)</span> or <span class="math inline">\(1/N_0\)</span>.
<ul>
<li>We’d need to know some things about the population to calculate those, too.</li>
<li>In particular, we’d need to know the frequency that <span class="math inline">\(x_j=1\)</span> in our population.</li>
</ul></li>
</ul>
</div>
<div id="tabset-9-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-9-2-tab">
<ul>
<li>What we can do is use our sample to estimate all of those tings.</li>
<li>We can use the <em>subsample standard deviations</em> <span class="groupa"><span class="math inline">\(\hat\sigma(0)\)</span></span> or <span class="groupb"><span class="math inline">\(\hat\sigma(1)\)</span></span>.
<ul>
<li>Those are drawn in as ‘arms’ on the subsample means in the plot on the right.</li>
<li>That’s a plot of the data we have. Our sample. And they’re about the same length.</li>
</ul></li>
<li>We can use the <span class="math inline">\(1/N_1\)</span> and <span class="math inline">\(1/N_0\)</span> themselves to estimate their expected values.</li>
<li>And we can plug those into our variance formula to get an estimate of this variance.</li>
</ul>
</div>
</div>
</div>
<p><span class="math display">\[
\widehat{\mathop{\mathrm{\mathop{\mathrm{V}}}}}[\hat\mu(1) - \hat\mu(0)] = \frac{\hat{\sigma}^2(1)}{N_1} + \frac{\hat{\sigma}^2(0)}{N_0}
\qfor \hat \sigma^2(x) = \frac{1}{N_x} \sum_{i:X_i=x} (Y_i - \hat \mu(x))^2
\]</span></p>
</section>
</section>
<section id="case-study" class="level1">
<h1>Case Study</h1>
<p>The NSW Experiment</p>
<section id="code" class="level2">
<h2 class="anchored" data-anchor-id="code">Code</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-10-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-1" role="tab" aria-controls="tabset-10-1" aria-selected="true">Load the Data</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-10-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-2" role="tab" aria-controls="tabset-10-2" aria-selected="false">Bootstrap the Difference in Means</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-10-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-3" role="tab" aria-controls="tabset-10-3" aria-selected="false">Calculate Width</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-10-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-4" role="tab" aria-controls="tabset-10-4" aria-selected="false">Visualization</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-10-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>nsw.data <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">'../data/nsw.csv'</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>nsw <span class="ot">=</span> nsw.data <span class="sc">|&gt;</span> </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(dataset<span class="sc">==</span><span class="st">'nsw'</span>) </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>X <span class="ot">=</span> <span class="fu">as.numeric</span>(nsw<span class="sc">$</span>treated)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> <span class="fu">as.numeric</span>(nsw<span class="sc">$</span>income78)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">length</span>(Y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-10-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-10-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>difference <span class="ot">=</span> <span class="fu">mean</span>(Y[X<span class="sc">==</span><span class="dv">1</span>]) <span class="sc">-</span> <span class="fu">mean</span>(Y[X<span class="sc">==</span><span class="dv">0</span>])</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>difference.bootstrap.samples <span class="ot">=</span> <span class="fu">map_vec</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>, <span class="cf">function</span>(.) {</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    I <span class="ot">=</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, n, <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    Xstar <span class="ot">=</span> X[I]</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    Ystar <span class="ot">=</span> Y[I]</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>(Ystar[Xstar<span class="sc">==</span><span class="dv">1</span>]) <span class="sc">-</span> <span class="fu">mean</span>(Ystar[Xstar<span class="sc">==</span><span class="dv">0</span>])</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-10-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-10-3-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>w95.boot <span class="ot">=</span> <span class="fu">width</span>(difference.bootstrap.samples, <span class="at">alpha=</span>.<span class="dv">05</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>nsw.interval <span class="ot">=</span> difference <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span>w95.boot<span class="sc">/</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-10-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-10-4-tab">

</div>
</div>
</div>
</section>
<section id="the-national-supported-work-demonstration" class="level2">
<h2 class="anchored" data-anchor-id="the-national-supported-work-demonstration">The National Supported Work Demonstration</h2>
<div class="columns">
<div class="column">
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-33-1.svg" class="img-fluid figure-img"></p>
<figcaption>The Bootstrap Sampling Distribution of the Difference in Means</figcaption>
</figure>
</div>
</div>
</div>
</div><div class="column">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th><span class="math inline">\(N_x\)</span></th>
<th><span class="math inline">\(\hat \mu(x)\)</span></th>
<th><span class="math inline">\(\hat \sigma(x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>260</td>
<td>4600</td>
<td>5500</td>
</tr>
<tr class="even">
<td>1</td>
<td>185</td>
<td>6300</td>
<td>7900</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-11-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-1" role="tab" aria-controls="tabset-11-1" aria-selected="true">The Program</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-11-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-2" role="tab" aria-controls="tabset-11-2" aria-selected="false">The Result</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-11-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-3" role="tab" aria-controls="tabset-11-3" aria-selected="false">Interpretation: Inconclusive</a></li></ul>
<div class="tab-content">
<div id="tabset-11-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-11-1-tab">
<ul>
<li>The National Supported Work Demonstration was an experimental program in the 1970s that provided job training and other services.</li>
<li>Here ‘experimental’ doesn’t just mean untested. It was run as a big experiment.</li>
<li>From a population of eligible people, they drew a sample of size 445 to participate.</li>
<li>To help estimate the impact of the program, participants were randomized into two groups.
<ul>
<li>The ‘treated’ group received the training and services.</li>
<li>The ‘control’ group did not.</li>
</ul></li>
</ul>
</div>
<div id="tabset-11-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-11-2-tab">
<ul>
<li>A year or two after the program ended, they compared the incomes of the two groups.
<ul>
<li>And the difference within the sample was about $1800 per year. In 1978 dollars.</li>
<li>That’s pretty good. A dollar in 1978 was worth about what $4.80 is today.</li>
<li>So adjusting for inflation, that’s an in-sample difference of about $8600. Huge impact.</li>
</ul></li>
<li>But there’s problem. It’s not clear that this describes a real population-level difference.</li>
<li>The sample was relatively small. And, as a result, their interval estimate was pretty wide.</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
\mu(1)-\mu(0)
&amp;\in 1800 \pm 1300 \approx [500, \ 3100]
&amp;&amp;\qqtext{is a 95\% confidence interval in 1978 dollars} \\
&amp;\in 8600 \pm 6300 \approx [2300, \ 14900]
&amp;&amp;\qqtext{adjusted for inflation}
\end{aligned}
\]</span></p>
</div>
<div id="tabset-11-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-11-3-tab">
<ul>
<li>This was an expensive program to run.
<ul>
<li>If the population difference were at the low end of the interval, at 500 1978 dollars, it wouldn’t be cost-effective.</li>
<li>If the population difference were at the high end of the interval, at 3100 1978 dollars, it would be.</li>
</ul></li>
<li>To figure out if it’s worth running, we need a more conclusive result.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="activities" class="level2">
<h2 class="anchored" data-anchor-id="activities">Activities</h2>
<div class="columns">
<div class="column">
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-34-1.svg" class="img-fluid figure-img"></p>
<figcaption>The Bootstrap Sampling Distribution of the Difference in Means</figcaption>
</figure>
</div>
</div>
</div>
</div><div class="column">
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th><span class="math inline">\(N_x\)</span></th>
<th><span class="math inline">\(\hat \mu(x)\)</span></th>
<th><span class="math inline">\(\hat \sigma(x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>260</td>
<td>4600</td>
<td>5500</td>
</tr>
<tr class="even">
<td>1</td>
<td>185</td>
<td>6300</td>
<td>7900</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-12-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-1" role="tab" aria-controls="tabset-12-1" aria-selected="true">Warm-Up</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-12-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-2" role="tab" aria-controls="tabset-12-2" aria-selected="false">Resizing</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-12-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-3" role="tab" aria-controls="tabset-12-3" aria-selected="false">About Dilution</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-12-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-4" role="tab" aria-controls="tabset-12-4" aria-selected="false">Solutions and Discussion</a></li></ul>
<div class="tab-content">
<div id="tabset-12-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-12-1-tab">
<ul>
<li>Use the information in this table to calculate a 95% interval based on normal approximation.</li>
<li>Compare it to the interval we got using the bootstrap sampling distribution for calibration.</li>
</ul>
</div>
<div id="tabset-12-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-12-2-tab">
<ul>
<li>Suppose we want to know the population difference to within $500 (1978 dollars).</li>
<li>How can we resize our experiment to make that happen?</li>
</ul>
<ol type="1">
<li>We could restart the experiment, running it exactly as before, to get a larger sample like the one we have.
<ul>
<li>In particular, one with the same proportion of participants assigned to treated and control units.</li>
<li>What sample size would we need to be able to get a 95% confidence interval this accurate?</li>
</ul></li>
<li>It’d be cheaper to increase the size of our control group without actually treating anyone.
<ul>
<li>Suppose you can analyze the resulting ‘diluted’ version of our experiment exactly like the original.</li>
<li>Same variance formula, same <span class="math inline">\(N_1\)</span>, but larger <span class="math inline">\(N_0\)</span>.</li>
<li>How big do we need to make <span class="math inline">\(N_0\)</span> to get the desired level of precision?</li>
<li>Is it even possible without increasing <span class="math inline">\(N_1\)</span>? How precise can we get keeping <span class="math inline">\(N_1\)</span> as-is?</li>
</ul></li>
</ol>
</div>
<div id="tabset-12-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-12-3-tab">
<ul>
<li>You can use a ‘two stage sampling’ argument to think of the ‘diluted’ version of our experiment …</li>
<li>… as being like the one we ran orginally, but with a different coin to assign treatment.</li>
<li>In essence, getting assigned treatment in the diluated version requires you to flip heads twice.
<ol type="1">
<li>Once to be in the first part of this larger sample—our original sample.</li>
<li>Once to be in the part of that sample assigned to treatment.</li>
</ol></li>
<li>We can boil those two flips down to one flip of an appropriately weighted coin.</li>
</ul>
</div>
<div id="tabset-12-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-12-4-tab">
<p><strong>Warm-Up.</strong></p>
<p>Our interval based on normal approximation should be <span class="math inline">\(\hat\theta \pm 1.96 \times \hat\sigma_{\hat\theta}\)</span> where <span class="math inline">\(\hat\theta=\hat\mu(1) - \hat\mu(0)\)</span> is our point estimate and <span class="math inline">\(\hat\sigma_{\hat\theta}\)</span> is an estimate of its standard deviation. That’s roughly <span class="math inline">\(\hat\theta \pm 2 \times 670\)</span>. Pretty similar to our bootstrap interval. Using the formula from <a href="#sec-estimating-variance" class="quarto-xref"><span>Section 18.13</span></a>, we calculate it like this.</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\mathop{\mathrm{\mathop{\mathrm{V}}}}}[\hat\mu(1) - \hat\mu(0)]
&amp;= \frac{\hat\sigma^2(1)}{N_1} + \frac{\hat\sigma^2(0)}{N_0} \\
&amp;\approx \frac{61.90M}{185} + \frac{30.07M}{260} \\
&amp;\approx 450.24K \approx \hat\sigma_{\hat\theta}^2 \qfor \hat\sigma_{\hat\theta} \approx 670
\end{aligned}
\]</span></p>
<p><strong>Resizing Part 1.</strong></p>
<p>If we’re resizing our experiment but running as before, we can think of the new subsample sizes as being roughly proportional to the old ones. That is, if our new sample size is <span class="math inline">\(\alpha n\)</span>, then our subsample sizes will be <span class="math inline">\(\alpha N_1\)</span> and <span class="math inline">\(\alpha N_0\)</span>. Plugging these new sample sizes in our variance formula, we get a simple formula for our our estimator’s standard deviation in this new experiment relative to the old one. It’s just <span class="math inline">\(\sigma_{\hat\theta}/\sqrt{\alpha}\)</span> where <span class="math inline">\(\sigma_{\hat\theta}\)</span> is the standard deviation of our estimator in our original experiment.</p>
<p><span class="math display">\[
\begin{aligned}
\mathop{\mathrm{\mathop{\mathrm{V}}}}[\hat\mu(1) - \hat\mu(0)]
&amp;= \frac{\sigma^2(1)}{\alpha N_1} + \frac{\sigma^2(0)}{\alpha N_0}  
= \frac{1}{\alpha} \sigma_{\hat\theta}^2 = \qty(\frac{\sigma_{\hat\theta}}{\sqrt{\alpha}})^2
\end{aligned}
\]</span></p>
<p>That is, it’s <span class="math inline">\(1/\sqrt{\alpha}\)</span> times the quantity we just estimated to be <span class="math inline">\(\hat\sigma_{\hat\theta} \approx 670\)</span>, so it’s sensible to estimate it by <span class="math inline">\(\hat\sigma_{\hat\theta}/\sqrt{\alpha}\)</span>. We want our new interval <span class="math inline">\(\hat\theta \pm 1.96\hat\sigma_{\hat\theta}/\sqrt{\alpha}\)</span> to be <span class="math inline">\(\hat\theta \pm 500\)</span>. The old one, <span class="math inline">\(\hat\theta \pm 1.96\hat\sigma_{\hat\theta} \approx \hat\theta \pm 1320\)</span>, was about 3 times wider than this, so we want <span class="math inline">\(\sqrt{\alpha} \approx 3\)</span> and therefore <span class="math inline">\(\alpha \approx 9\)</span>. Since we’ve already got a sample of size <span class="math inline">\(n\)</span>, we can run a ‘second wave’ of size <span class="math inline">\((\alpha-1)n \approx 8n\)</span> to get a big enough sample.</p>
<p>That’s a back-of-the-envelope calculation. If we want to be a bit more precise, we can actually solve for <span class="math inline">\(\alpha\)</span> that equates these two interval widths. <span class="math display">\[
\begin{aligned}
\frac{1.96\hat\sigma_{\hat\theta}}{\sqrt{\alpha}} = 500 \qfor
\alpha = \qty(\frac{1.96\hat\sigma_{\hat\theta}}{500})^2 \approx 6.92
\end{aligned}
\]</span></p>
<p>That’s a bit better than 9. It pays to be precise sometimes.</p>
<p><strong>Resizing Part 2.</strong> If it’s free to include more participants in our control group, we may as we’ll make <span class="math inline">\(N_0\)</span> arbitrarily large. If we did, we’d have this variance.</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\mathop{\mathrm{\mathop{\mathrm{V}}}}}[\hat\mu(1) - \hat\mu(0)]
&amp;= \frac{\hat\sigma^2(1)}{N_1} + \frac{\hat\sigma^2(0)}{\infty}
= \qty(\frac{\hat\sigma(1)}{\sqrt{N_1}})^2 \approx 580^2
\end{aligned}
\]</span></p>
<p>The resulting interval would be <span class="math inline">\(\pm 1.96 \times 580 \approx \pm 1130\)</span>. Roughly twice as wide as we want. So we’re not getting the precision we want for free. Thinking back to Part 1, that means we’d want <span class="math inline">\(N_1\)</span> to be roughly <span class="math inline">\(\alpha = 4\)</span> times larger. And that’d mean treating roughly <span class="math inline">\((\alpha-1) = 3\)</span> more people. That’s a lot cheaper than treating <span class="math inline">\(8\)</span> (or really <span class="math inline">\(5.92\)</span>) times as many people, as we would if we ran our second wave as a scaled-up version of the first.</p>
</div>
</div>
</div>
</section>
</section>
<section id="appendix-additional-figures" class="level1">
<h1>Appendix: Additional Figures</h1>
<section id="the-social-pressure-letter" class="level2">
<h2 class="anchored" data-anchor-id="the-social-pressure-letter">The Social Pressure Letter</h2>
<div id="fig-social-pressure-letter" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-social-pressure-letter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/gerber-green-larimer-neighbors.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-social-pressure-letter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.1
</figcaption>
</figure>
</div>
</section>
</section>
<section id="sec-proving-total-variance" class="level1">
<h1>Appendix: Proving the Law of Total Variance</h1>
<section id="starting-point-interpreting-variance-as-excess" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="starting-point-interpreting-variance-as-excess">Starting Point: Interpreting Variance as Excess</h2>
<p><span class="math display">\[
\small{
\begin{aligned}
\mathop{\mathrm{\mathop{\mathrm{V}}}}(Y) &amp;= \mathop{\mathrm{E}}\qty[ \qty{ Y - \mathop{\mathrm{E}}(Y) }^2 ] &amp;&amp; \text{ the \emph{spread} idea: the mean square of a \emph{centered version} of $Y$ } \\
&amp;= \mathop{\mathrm{E}}\qty(Y^2) - \qty{\mathop{\mathrm{E}}\qty(Y)}^2         &amp;&amp; \text{ the \emph{excess} idea: the average amount $Y^2$ \emph{exceeds} the square of its mean}.
\end{aligned}
}
\]</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-37-1.svg" height="250" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Let’s think, in terms of the plot, about why there is excess in the square.</p>
<ul>
<li>Suppose <span class="math inline">\(Y\)</span> takes on three values — the dots —with equal probability.
<ul>
<li>Its expectation is the average height of the black dots.</li>
<li>And its expectation, squared, is the square of this.</li>
</ul></li>
<li>Its square <span class="math inline">\(Y^2\)</span> takes on the the square of those values—the squares — with equal probability.
<ul>
<li>Its expectation is the average height of the squares.</li>
</ul></li>
<li>Why is the second one bigger?
<ul>
<li>Because squaring <em>increases big draws of Y</em> more than it <em>decreases small ones</em>.</li>
<li>Visually, the line from <span class="math inline">\(Y\)</span> to <span class="math inline">\(Y^2\)</span> is longer when <span class="math inline">\(Y\)</span> is bigger than when it’s smaller.</li>
</ul></li>
<li>We’ll mostly think about variance in terms of spread, but the ‘excess’ formula comes up in calculations.</li>
</ul>
</section>
<section id="equivalence-proof" class="level2">
<h2 class="anchored" data-anchor-id="equivalence-proof">Equivalence Proof</h2>
<p><strong>Claim.</strong> The spread and excess formulas for variance are equivalent. <span class="math display">\[  
\mathop{\mathrm{E}}\qty[ \qty{ Y - \mathop{\mathrm{E}}(Y) }^2 ] =\mathop{\mathrm{E}}[ Y^2] - \qty{\mathop{\mathrm{E}}(Y)}^2
\]</span></p>
<p><span class="math display">\[
\small{
\begin{aligned}
\mathop{\mathrm{E}}\qty[ \qty{ Y - \mathop{\mathrm{E}}(Y) }^2 ]
&amp;= \mathop{\mathrm{E}}\qty[ Y^2 - 2 Y \mathop{\mathrm{E}}(Y) + \qty{\mathop{\mathrm{E}}(Y)}^2 ] &amp;&amp; \text{ FOIL } \\
&amp;= \mathop{\mathrm{E}}[ Y^2] - \mathop{\mathrm{E}}\qty[2 Y \mathop{\mathrm{E}}(Y)] + \mathop{\mathrm{E}}\qty[\qty{\mathop{\mathrm{E}}(Y)}^2] &amp;&amp; \text{Distributing expectations (linearity)} \\
&amp;= \mathop{\mathrm{E}}[ Y^2] - 2\mathop{\mathrm{E}}(Y)\mathop{\mathrm{E}}\qty[Y] + \qty{\mathop{\mathrm{E}}(Y)}^2\mathop{\mathrm{E}}[1] &amp;&amp; \text{Pulling constants out of expectations (linearity)} \\
&amp;= \mathop{\mathrm{E}}[ Y^2] - 2\qty{\mathop{\mathrm{E}}(Y)}^2 + \qty{\mathop{\mathrm{E}}(Y)}^2] &amp;&amp; \text{Recognizing a product of something with itself as a square} \\
&amp;= \mathop{\mathrm{E}}[ Y^2] - \cancel{2}\qty{\mathop{\mathrm{E}}(Y)}^2 + \cancel{\qty{\mathop{\mathrm{E}}(Y)}^2}] &amp;&amp; \text{Subtracting}
\end{aligned}
}
\]</span></p>
</section>
<section id="conditional-variance-as-excess" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="conditional-variance-as-excess">Conditional Variance as Excess</h2>
<p><span class="math display">\[
\small{
\begin{aligned}
\mathop{\mathrm{\mathop{\mathrm{V}}}}(Y \mid X) &amp;= \mathop{\mathrm{E}}\qty[ \qty{ Y - \mathop{\mathrm{E}}(Y\mid X)}^2 \mid X ] &amp;&amp; \text{ the \emph{spread} idea: the mean square of a conditionally centered version of $Y$ } \\
&amp;= \mathop{\mathrm{E}}\qty(Y^2 \mid X) - \qty{\mathop{\mathrm{E}}\qty(Y \mid X)}^2              &amp;&amp; \text{ the \emph{excess} idea: the average amount $Y^2$ exceeds the square of its cond. mean}
\end{aligned}
}
\]</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture6_files/figure-html/unnamed-chunk-38-1.svg" height="500" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>We can think of the Conditional Variance as excess, too.</li>
<li>It’s the same as the unconditional case, but <em>within subpopulations</em>.</li>
</ul>
</section>
<section id="proof-1" class="level2">
<h2 class="anchored" data-anchor-id="proof-1">Proof</h2>
<p><strong>Claim.</strong> <span class="math display">\[
\mathop{\mathrm{\mathop{\mathrm{V}}}}[Y] = \textcolor{blue}{\mathop{\mathrm{E}}\qty[\mathop{\mathrm{\mathop{\mathrm{V}}}}(Y \mid X)]} + \textcolor{green}{\mathop{\mathrm{\mathop{\mathrm{V}}}}\qty[\mathop{\mathrm{E}}(Y \mid X)]}
\]</span></p>
<ol type="1">
<li>Rewrite the variances, conditional and unconditional, in <em>excess</em> form.</li>
</ol>
<div class="fragment">
<p><span class="math display">\[
\mathop{\mathrm{\mathop{\mathrm{V}}}}[Y]  = \textcolor{blue}{\mathop{\mathrm{E}}\qty[ \mathop{\mathrm{E}}(Y^2 \mid X) - \qty{\mathop{\mathrm{E}}\qty(Y \mid X)}^2]}
                       + \textcolor{green}{\mathop{\mathrm{E}}\qty{ \mathop{\mathrm{E}}(Y \mid X)^2}  - \qty(\mathop{\mathrm{E}}\qty{\mathop{\mathrm{E}}\qty(Y \mid X)})^2}
\]</span></p>
</div>
<ol start="2" type="1">
<li>Distribute the outer expectations in the first term.</li>
</ol>
<div class="fragment">
<p><span class="math display">\[
\mathop{\mathrm{\mathop{\mathrm{V}}}}[Y] = \textcolor{blue}{\mathop{\mathrm{E}}\qty[ \mathop{\mathrm{E}}(Y^2 \mid X)] - \mathop{\mathrm{E}}\qty[\qty{\mathop{\mathrm{E}}\qty(Y \mid X)}^2]}
                       + \textcolor{green}{\mathop{\mathrm{E}}\qty[ \qty{\mathop{\mathrm{E}}(Y \mid X)^2} ] - \qty(\mathop{\mathrm{E}}\qty{\mathop{\mathrm{E}}\qty(Y \mid X)})^2}
\]</span></p>
</div>
<ol start="3" type="1">
<li>Cancel matching terms</li>
</ol>
<div class="fragment">
<p><span class="math display">\[
\mathop{\mathrm{\mathop{\mathrm{V}}}}[Y]  = \textcolor{blue}{\mathop{\mathrm{E}}\qty[ \mathop{\mathrm{E}}(Y^2 \mid X)] \cancel{- \mathop{\mathrm{E}}\qty[\qty{\mathop{\mathrm{E}}\qty(Y \mid X)}^2]}}  
                       + \textcolor{green}{\cancel{\mathop{\mathrm{E}}\qty[ \qty{\mathop{\mathrm{E}}(Y \mid X)^2} ]} -  \qty(\mathop{\mathrm{E}}\qty{\mathop{\mathrm{E}}\qty(Y \mid X)})^2}
\]</span></p>
</div>
<ol start="4" type="1">
<li>Use the law of iterated expectations to simplify the remaining terms.</li>
</ol>
<div class="fragment">
<p><span class="math display">\[
\mathop{\mathrm{\mathop{\mathrm{V}}}}[Y]  = \textcolor{blue}{E[Y^2]  \cancel{- \mathop{\mathrm{E}}\qty[\qty{\mathop{\mathrm{E}}\qty(Y \mid X)}^2]}}
                       + \textcolor{green}{\cancel{\mathop{\mathrm{E}}\qty[ \qty{\mathop{\mathrm{E}}(Y \mid X)^2} ]} - (\mathop{\mathrm{E}}\qty{Y})^2}
\]</span></p>
</div>


<script type="ojs-module-contents">
eyJjb250ZW50cyI6W119
</script>
<div id="exercise-loading-indicator" class="exercise-loading-indicator d-none d-flex align-items-center gap-2">
<div id="exercise-loading-status" class="d-flex gap-2">

</div>
<div class="spinner-grow spinner-grow-sm">

</div>
</div>
<script type="vfs-file">
W10=
</script>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>This is really still called the law of iterated expectations.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>We showed that on <a href="#sec-linearity" class="quarto-xref"><span>Section 16.1</span></a>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script type="ojs-module-contents">
eyJjb250ZW50cyI6W119
</script>
<script type="module">
if (window.location.protocol === "file:") { alert("The OJS runtime does not work with file:// URLs. Please use a web server to view this document."); }
window._ojs.paths.runtimeToDoc = "../../lectures";
window._ojs.paths.runtimeToRoot = "../..";
window._ojs.paths.docToRoot = "..";
window._ojs.selfContained = false;
window._ojs.runtime.interpretFromScriptTags();
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../homework/week3-homework.html" class="pagination-link" aria-label="Homework: Comparing Estimators">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Homework: Comparing Estimators</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../exams/practice-midterm-1.html" class="pagination-link" aria-label="Practice Midterm 1">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Practice Midterm 1</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>