```{r}
#| label: load-libraries
#| include: false
library(tidyverse)
library(htmltools)
library(kableExtra)
library(scales)
library(knitr)

default.seed = 0
percent = label_percent(accuracy=1)
approx  = function(x,accuracy=.01) { 
    label_number(accuracy=accuracy, scale_cut=cut_short_scale())(x) 
}
```


```{r}
#| label: ggplot-themes
class.theme = theme(plot.background = element_rect(fill = "transparent", colour = NA),
        panel.background = element_rect(fill = "transparent", colour = NA),
                    legend.background = element_rect(fill="transparent", colour = NA),
                    legend.box.background = element_rect(fill="transparent", colour = NA),
                    legend.key = element_rect(fill="transparent", colour = NA),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x  = element_text(colour = "#aaaaaa"),
        axis.text.y  = element_text(colour = "#aaaaaa"),
        axis.title.x  = element_text(colour = "#aaaaaa"),
        axis.title.y  = element_text(colour = "#aaaaaa", angle=90)
)

theme_set(class.theme)
theme_update(axis.title.x  = element_blank(),
             axis.title.y  = element_blank())
simplified.theme = theme_get()

theme_update(axis.text.x   = element_blank(), 
              axis.text.y   = element_blank())
blank.theme = theme_get()

theme_update(panel.grid.major=element_line(color=rgb(1,0,0,.1,  maxColorValue=1)),
           panel.grid.minor=element_line(color=rgb(0,1,0,.1, maxColorValue=1)))
grid.theme = theme_get()

theme_set(simplified.theme)
```


```{r}
#| label: define-colors
twocolor.red   = rgb(248,118,109, maxColorValue=255)
twocolor.green = rgb(0,191,196,   maxColorValue=255)

pink     = '#ef476f'  # rgb(239,71,111)
mustard  = '#ffd166'  # rgb(255,209,102)
green    = '#06d6a0'  # rgb(6, 214,160)
teal     = '#118ab2'  # rgb(17,138,178)
midnight = '#073b4c'  # rgb(7,59,76)
# fwiw, col2rgb is a function that converts a color to its RGB values

map.background = green
polla  = midnight
pollb  = pink
pollc  = teal
polld  = green
# THESE COLORS ARE DEFINED IN class.scss, TOO. IF YOU CHANGE THEM HERE, CHANGE THEM THERE.
```

::: hidden
$$
\DeclareMathOperator{\E}{E}
\DeclareMathOperator{\V}{V}
\DeclareMathOperator{\Var}{\V}
\DeclareMathOperator{\Cov}{Cov}
\DeclareMathOperator*{\argmin}{argmin}
\newcommand{\ind}[1]{1_{\{#1\}}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\model}{\mathcal{M}}

\newcommand{\mapbg}{\color[RGB]{6,214,160}}
\newcommand{\polla}{\color[RGB]{7,59,76}}
\newcommand{\pollb}{\color[RGB]{239,71,111}}
\newcommand{\pollc}{\color[RGB]{17,138,178}}
\newcommand{\polld}{\color[RGB]{6,214,160}}
\newcommand{\groupa}{\color[RGB]{248,118,109}}
\newcommand{\groupb}{\color[RGB]{0,191,196}}

\newcommand{\inmapbg}[1]{\textcolor[RGB]{6,214,160}{#1}}
\newcommand{\inpolla}[1]{\textcolor[RGB]{7,59,76}{#1}}
\newcommand{\inpollb}[1]{\textcolor[RGB]{239,71,111}{#1}}
\newcommand{\inpollc}[1]{\textcolor[RGB]{17,138,178}{#1}}
\newcommand{\inpolld}[1]{\textcolor[RGB]{6,214,160}{#1}}
\newcommand{\ingroupa}[1]{\textcolor[RGB]{248,118,109}{#1}}
\newcommand{\ingroupb}[1]{\textcolor[RGB]{0,191,196}{#1}}
\newcommand{\inred}[1]{\ingroupa{#1}}
\newcommand{\ingreen}[1]{\ingroupb{#1}}
\newcommand{\inblue}[1]{\textcolor[RGB]{0,0,255}{#1}}

\newcommand{\alert}[1]{\textcolor[RGB]{255,0,0}{#1}}
\newcommand{\faint}[1]{\textcolor{lightgray}{#1}}

\newcommand{\with}{\ingroupb{\text{degree}}}
\newcommand{\without}{\ingroupa{\text{no degree}}}
$$
:::


```{r}
#| label: table-styling
ellipsis = function(df, nhead=5L, ntail=2) {
    rownames(df) = as.character(1:nrow(df))
    stopifnot("data.frame" %in% class(df))
    els = rep(NA, ncol(df)) |>
        matrix(nrow=1, dimnames=list(NULL, names(df))) |>
        data.frame(stringsAsFactors=FALSE) |>
        as_tibble()
    rownames(els) = "⋮"
    dplyr::bind_rows(head(df, nhead), els, tail(df, ntail))
}
options(knitr.kable.NA = '')
```

```{r}
#| label: with-seed
with_seed = function(thunk, seed) {
    current.seed = .Random.seed
    set.seed(seed)
    result = thunk()
    set.seed(current.seed)
    result
}
```

```{r}
#| label: test-with-seed
#| eval: false
set.seed(1)
sample(1:5)
sample(1:5)

set.seed(1)
sample(1:5)
(\() sample(1:5) ) |> with_seed(1)
sample(1:5)
```

```{r}
#| label: ggplot-utils
mean_sd = function(x, mult = 1) { mean_se(x, mult = mult*sqrt(length(stats::na.omit(x)))) }
```

```{r}
#| label: coarsen
coarsen = function(x, group, seed=0) {
  with_seed(function(seed) { 
    x.coarsened = rep(NA, length(x))
    for(gg in unique(group)) {
        x.coarsened[group==gg] = runif(sum(group==gg), min(x[group==gg]), max(x[group==gg]))
    }
    x.coarsened 
  }, seed=seed)
} 
```


```{r}
#| label: calibrated-width
width = function(samples, center=mean(samples), alpha=.05) { 
    limits = c(0, 2*max(abs(samples-center)))
    covg_dif = function(w) { 
      actual = mean(center - w/2 <= samples & samples <= center + w/2)
      nominal = 1-alpha 
      actual - nominal  
  }
  uniroot(covg_dif, interval=limits)$root
}

width_cdf = function(cdf, center, limits, alpha=.05) {
  covg_dif = function(w) { 
    actual = cdf(center + w/2) - cdf(center - w/2) 
    nominal = 1-alpha 
    actual - nominal  
  }
  uniroot(covg_dif, interval=limits)$root
}
```

```{r}
#| label: distribution-plot-annotations

default.dot.size = 2
default.highlight.colors = c(polla, pollb, pollc, polld)
default_height = function(samples) { dnorm(0, mean=0, sd=sd(samples)) }

# fussy code to make sure the heights of the highlighted 
# dots don't change when the total number of dots changes
annotation_dot_heights = function(dots, highlight.dots, height, seed=default.seed) {
    heights = (\(){ 
        highlight.dot.heights = sample(1:highlight.dots)/(highlight.dots + 1)
        unhighlighted.dot.heights = setdiff(sample(1:dots), 1:highlight.dots)/(dots + 1)
        height*c(highlight.dot.heights[1:min(dots,highlight.dots)], 
                 unhighlighted.dot.heights) 
        }) |> with_seed(seed)
    heights
}

with_annotations = function(samples,
                            estimand = NA,
                            shade.width = NA, shade.color='green', shade.alpha=.15,
                            dots=100, interval.width=NA, 
                                      dot.size = default.dot.size,
                                      highlight.dots=3, 
                                      highlighted.dot.alpha=1, 
                                      unhighlighted.dot.alpha=.15,
                                      height=default_height(samples), 
                            seed=default.seed) { 
    highlight.colors = if(highlight.dots) default.highlight.colors[1:min(dots,highlight.dots)] else c()
    summary.data = data.frame(
        mu=mean(samples), 
        w66 = width(samples, alpha=1/3),
        w95 = width(samples, alpha=.05),
        shade.width=shade.width,
        estimand=estimand)

    estimand.geom = if(is.na(summary.data$estimand)) geom_blank() else 
        geom_vline(aes(xintercept=estimand), 
                   color='green', size=3, alpha=.8, 
                   data=summary.data)
    shade.geom = if(is.na(summary.data$shade.width)) geom_blank() else 
        geom_rect(aes(xmin=mu-shade.width/2, 
                      xmax=mu+shade.width/2, ymin=0, ymax=Inf), 
                  fill=shade.color, alpha=shade.alpha, 
                  data=summary.data)
    dot.geom = if(dots == 0) geom_blank() else {
        heights = annotation_dot_heights(dots, highlight.dots, height, seed)
        dot.data = data.frame(
            x=samples[1:dots], 
            y=heights, 
            w=interval.width,
            color=c(highlight.colors, 
                    rep('purple', dots-length(highlight.colors))),
            alpha=c(rep(highlighted.dot.alpha,   length(highlight.colors)), 
                    rep(unhighlighted.dot.alpha, dots-length(highlight.colors))))       
        if(is.na(interval.width))
                geom_point(aes(y=y, x=x, color=I(color), alpha=I(alpha)), 
                           size=dot.size, data=dot.data)
        else 
            geom_pointrange(aes(y=y, x=x, xmin=x-w/2, xmax=x+w/2, color=I(color), alpha=I(alpha)), 
                            size=dot.size/4, linewidth=dot.size/4, data=dot.data)
    }
    
    geoms = list(estimand.geom, shade.geom, dot.geom,
         geom_vline(aes(xintercept=mu), color="blue", data=summary.data),
         geom_vline(aes(xintercept=mu-w66/2), color="blue", linetype='dashed', data=summary.data),
         geom_vline(aes(xintercept=mu+w66/2), color="blue", linetype='dashed', data=summary.data), 
         geom_vline(aes(xintercept=mu-w95/2), color="blue", linetype='dotted', data=summary.data),
         geom_vline(aes(xintercept=mu+w95/2), color="blue", linetype='dotted', data=summary.data))
    geoms
}
```

```{r}
#| label: last-shared-code-chunk
```