---
title: "QTM 220: Lecture 3"
subtitle: "Population Inference for Means"
format: 
  beamer:
     header-includes: |
       \setbeamertemplate{navigation symbols}{}
       \setbeamertemplate{footline}[page number]
editor: visual
---

## Review

```{=tex}
\begin{itemize}
\item Last lecture, we discussed learning about population proportions based on a random sample (with replacement) from the population. \pause
\item We saw that for large enough sample sizes, our sample proportion was likely to be close to the population proportion. \pause
\item We also demonstrated that we could predict how close we might by using confidence intervals. \pause
\item We explored a bootstrapping approach to producing confidence intervals.  
\end{itemize}
```
## In this lecture

```{=tex}
\begin{itemize}
\item In this lecture, we consider variables that are not binary and our goal is to learn about the population mean (not just a proportion) from a random sample (with replacement) from the population. \pause
\item Because the variables we will consider may take on many values, we will not know the type of probability distribution underlying our data (e.g., the Bernoulli distribution in the binary variable case).  \pause
\item Not knowing the distribution isn't a problem when the sample is large enough, but understanding why it isn't a problem is subtle. 
\end{itemize}
```
## The Current Population Survey

Something about the CPS sampling here...

Recall that our sample mean based on 2,258 working age Californians is \$135,406

## Two Questions

Unlike the turnout example, we will never know the true population income mean, which we will denote with $\mu$. \pause 

We will also never know the population income standard deviation, which we will denote $\sigma$, or the population variance which we denote with $\sigma^2$. \pause 

We also will not be able to generate a sampling distribution. \pause But we still want to answer the two questions. \pause

```{=tex}
\begin{enumerate}
\item Is \$135,406 likely to be close to the population mean $\mu$?  
\item What can we say about how close? 
\end{enumerate}
```
## Sampling Distribution for the Sample Mean

```{=tex}
\begin{table}[h]
\begin{center}
{\scriptsize
\begin{tabular}{r|r|r|r|r|r} %cc
$i$ & \multicolumn{1}{r|}{1} & \multicolumn{1}{r|}{2}   & $\dots$ & \multicolumn{1}{r|}{2258} & \\ % & \multicolumn{1}{c}{$MoE$}& \multicolumn{1}{c}{95\% CI}  \\
$s$  & $Y_1$  & $Y_2$   & $\dots$  & $Y_{2258}$  & $\overline{Y}_{2258}$ \\ % & $2\cdot\sqrt{\frac{\overline{Y}_{625}(1-\overline{Y}_{625})}{625}}$ & $\overline{Y}_{625} \pm MoE$ \\
\hline
1 & 37,006 & 108,811   & $\dots$  &  49,001  & 135,406   \\ %& \visible<2->{.037} & \visible<3->{[.643,.717]}\\
\visible<2->{2} & \visible<2->{?} & \visible<2->{?}   & \visible<2->{$\dots$}  & \visible<2->{?} & \visible<2->{?} \\ %& \visible<2->{.037}  & \visible<3->{[.663,.737]}\\
\visible<2->{3} & \visible<2->{?} & \visible<2->{?}  & \visible<2->{$\dots$}  & \visible<2->{?} & \visible<2->{?} \\ %& \visible<2->{.035} & \visible<3->{[.715,.785]}\\
\visible<2->{4} & \visible<2->{$\vdots$} & \visible<2->{$\vdots$} & \visible<2->{$\dots$}  & \visible<2->{$\vdots$} & \visible<2->{$\vdots$} \\ %& \visible<2->{.036} & \visible<3->{[.694,.766]}\\
\visible<2->{5} & \visible<2->{$\vdots$} & \visible<2->{$\vdots$}  & \visible<2->{$\dots$}  & \visible<2->{$\vdots$} & \visible<2->{$\vdots$} \\ %& \visible<2->{.037} & \visible<3->{[.653,.727]}\\
\visible<2->{$\vdots$} & \visible<2->{$\vdots$}  & \visible<2->{$\vdots$} & \visible<2->{$\vdots$} & \visible<2->{$\vdots$}  & \visible<2->{$\vdots$} \\ % & \visible<2->{$\vdots$} & \visible<3->{$\vdots$}  \\
\visible<2->{1 mil}  & \visible<2->{?} & \visible<2->{?} & \visible<2->{$\dots$}  & \visible<2->{?} & \visible<2->{?} \\ %& \visible<2->{.035}& \visible<3->{[.705,.775]}\\
 \visible<2->{$\vdots$}  & \visible<2->{$\vdots$}  & \visible<2->{$\vdots$} & \visible<2->{$\vdots$} & \visible<2->{$\vdots$}  & \visible<2->{$\vdots$} \\ % & \visible<2->{$\vdots$} & \visible<3->{$\vdots$}\\
\hline
\visible<1->{$f_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{?}} & \multicolumn{1}{r|}{\visible<1->{?}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{?}} & \visible<1->{?} \\
\visible<1->{$E_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{$\mu$}} & \multicolumn{1}{r|}{\visible<1->{$\mu$}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{$\mu$}} & \visible<1->{?} \\
\visible<1->{$V_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}} & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}} & \visible<1->{?} \\
\end{tabular}}
\end{center}
\end{table}
```
```{=tex}
\begin{itemize}
\item Recall that we can think of $Y_1,...,Y_n$ as $i.i.d.$ RVs.
\item Although we don't know the distribution $f_Y(y)$ of these RVs, their expected value $E[Y]$ is the population mean $\mu$ and their variance $V[Y]$ is the population variance $\sigma^2$.
\end{itemize}
```
## What can we learn?

```{=tex}
\begin{table}[h]
\begin{center}
{\scriptsize
\begin{tabular}{r|r|r|r|r|r} %cc
$i$ & \multicolumn{1}{r|}{1} & \multicolumn{1}{r|}{2}   & $\dots$ & \multicolumn{1}{r|}{2258} & \\ % & \multicolumn{1}{c}{$MoE$}& \multicolumn{1}{c}{95\% CI}  \\
$s$  & $Y_1$  & $Y_2$   & $\dots$  & $Y_{2258}$  & $\overline{Y}_{2258}$ \\ % & $2\cdot\sqrt{\frac{\overline{Y}_{625}(1-\overline{Y}_{625})}{625}}$ & $\overline{Y}_{625} \pm MoE$ \\
\hline
1 & 37,006 & 108,811   & $\dots$  &  49,001  & 135,406   \\ %& \visible<2->{.037} & \visible<3->{[.643,.717]}\\
\visible<1->{2} & \visible<1->{?} & \visible<1->{?}   & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.037}  & \visible<3->{[.663,.737]}\\
\visible<1->{3} & \visible<1->{?} & \visible<1->{?}  & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.035} & \visible<3->{[.715,.785]}\\
\visible<1->{4} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\dots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} \\ %& \visible<2->{.036} & \visible<3->{[.694,.766]}\\
\visible<1->{5} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\dots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} \\ %& \visible<2->{.037} & \visible<3->{[.653,.727]}\\
\visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} \\ % & \visible<2->{$\vdots$} & \visible<3->{$\vdots$}  \\
\visible<1->{1 mil}  & \visible<1->{?} & \visible<1->{?} & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.035}& \visible<3->{[.705,.775]}\\
 \visible<1->{$\vdots$}  & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} \\ % & \visible<2->{$\vdots$} & \visible<3->{$\vdots$}\\
\hline
\visible<1->{$f_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{?}} & \multicolumn{1}{r|}{\visible<1->{?}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{?}} & \visible<1->{\textcolor{red}{?}} \\
\visible<1->{$E_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{$\mu$}} & \multicolumn{1}{r|}{\visible<1->{$\mu$}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{$\mu$}} & \visible<1->{\textcolor{red}{?}} \\
\visible<1->{$V_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}} & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}} & \visible<1->{\textcolor{red}{?}} \\
\end{tabular}}
\end{center}
\end{table}
```
```{=tex}
\begin{itemize}
\item Although we can't observe the population or the sampling distribution, we can mathematically derive certain facts about the sampling distribution. 
\item We will focus on the three red question marks.
\end{itemize}
```
## The Type of Distribution

```{=tex}
\begin{table}[h]
\begin{center}
{\scriptsize
\begin{tabular}{r|r|r|r|r|r} %cc
$i$ & \multicolumn{1}{r|}{1} & \multicolumn{1}{r|}{2}   & $\dots$ & \multicolumn{1}{r|}{2258} & \\ % & \multicolumn{1}{c}{$MoE$}& \multicolumn{1}{c}{95\% CI}  \\
$s$  & $Y_1$  & $Y_2$   & $\dots$  & $Y_{2258}$  & $\overline{Y}_{2258}$ \\ % & $2\cdot\sqrt{\frac{\overline{Y}_{625}(1-\overline{Y}_{625})}{625}}$ & $\overline{Y}_{625} \pm MoE$ \\
\hline
1 & 37,006 & 108,811   & $\dots$  &  49,001  & 135,406   \\ %& \visible<2->{.037} & \visible<3->{[.643,.717]}\\
\visible<1->{2} & \visible<1->{?} & \visible<1->{?}   & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.037}  & \visible<3->{[.663,.737]}\\
\visible<1->{3} & \visible<1->{?} & \visible<1->{?}  & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.035} & \visible<3->{[.715,.785]}\\
\visible<1->{4} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\dots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} \\ %& \visible<2->{.036} & \visible<3->{[.694,.766]}\\
\visible<1->{5} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\dots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} \\ %& \visible<2->{.037} & \visible<3->{[.653,.727]}\\
\visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} \\ % & \visible<2->{$\vdots$} & \visible<3->{$\vdots$}  \\
\visible<1->{1 mil}  & \visible<1->{?} & \visible<1->{?} & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.035}& \visible<3->{[.705,.775]}\\
 \visible<1->{$\vdots$}  & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} \\ % & \visible<2->{$\vdots$} & \visible<3->{$\vdots$}\\
\hline
\visible<1->{$f_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{?}} & \multicolumn{1}{r|}{\visible<1->{?}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{?}} & \visible<1->{\textcolor{red}{N(?,?)}} \\
\visible<1->{$E_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{$\mu$}} & \multicolumn{1}{r|}{\visible<1->{$\mu$}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{$\mu$}} & \visible<1->{\textcolor{red}{?}} \\
\visible<1->{$V_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}} & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}} & \visible<1->{\textcolor{red}{?}} \\
\end{tabular}}
\end{center}
\end{table}
```
```{=tex}
\begin{itemize}
\item The central limit theorem says the sampling distribution for the sample mean will be normally distributed. 
\item We know that $\overline{Y}_{2258} \sim N(?,?)$, but still don't know the mean or the variance of this distribution. 
\end{itemize}
```
## What is the $E[\overline{Y}_{n}]$?

```{=tex}
\begin{table}[h]
\begin{center}
{\scriptsize
\begin{tabular}{r|r|r|r|r|r} %cc
$i$ & \multicolumn{1}{r|}{1} & \multicolumn{1}{r|}{2}   & $\dots$ & \multicolumn{1}{r|}{2258} & \\ % & \multicolumn{1}{c}{$MoE$}& \multicolumn{1}{c}{95\% CI}  \\
$s$  & $Y_1$  & $Y_2$   & $\dots$  & $Y_{2258}$  & $\overline{Y}_{2258}$ \\ % & $2\cdot\sqrt{\frac{\overline{Y}_{625}(1-\overline{Y}_{625})}{625}}$ & $\overline{Y}_{625} \pm MoE$ \\
\hline
1 & 37,006 & 108,811   & $\dots$  &  49,001  & 135,406   \\ %& \visible<2->{.037} & \visible<3->{[.643,.717]}\\
\visible<1->{2} & \visible<1->{?} & \visible<1->{?}   & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.037}  & \visible<3->{[.663,.737]}\\
\visible<1->{3} & \visible<1->{?} & \visible<1->{?}  & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.035} & \visible<3->{[.715,.785]}\\
\visible<1->{4} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\dots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} \\ %& \visible<2->{.036} & \visible<3->{[.694,.766]}\\
\visible<1->{5} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\dots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} \\ %& \visible<2->{.037} & \visible<3->{[.653,.727]}\\
\visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} \\ % & \visible<2->{$\vdots$} & \visible<3->{$\vdots$}  \\
\visible<1->{1 mil}  & \visible<1->{?} & \visible<1->{?} & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.035}& \visible<3->{[.705,.775]}\\
 \visible<1->{$\vdots$}  & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} \\ % & \visible<2->{$\vdots$} & \visible<3->{$\vdots$}\\
\hline
\visible<1->{$f_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{?}} & \multicolumn{1}{r|}{\visible<1->{?}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{?}} & \visible<1->{$N(\textcolor{red}{?},?)$} \\
\visible<1->{$E_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{$\mu$}} & \multicolumn{1}{r|}{\visible<1->{$\mu$}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{$\mu$}} & \visible<1-1>{?}\hspace{-.17cm}\visible<2->{\textcolor{red}{?}} \\
\visible<1->{$V_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}} & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}} & \visible<1->{?} \\
\end{tabular}}
\end{center}
\end{table}
```
## Sample Means

Property #1: \textit{The sample mean is unbiased for the population mean.} The expected value of the sample mean, $\text{E}[\overline Y] = \mu$.

Proof: \begin{align*}
\text{E}[\overline Y] &= \text{E} \left[ \frac{1}{n} \left( Y_1 + ... + Y_n \right) \right] \\
& =  \frac{1}{n} \text{E} \left[ Y_1 + ... + Y_n  \right] \\
& =  \frac{1}{n} \left( \text{E} [ Y_1] + ... + \text{E} [Y_n]  \right) \\
& =  \frac{1}{n} \left( \text{E} [ Y] + ... + \text{E} [Y]  \right) \\
& =  \frac{1}{n} n \text{E} [ Y] \\
& = \mu.
\end{align*}

## Sample mean is unbiased for the population mean

```{=tex}
\begin{table}[h]
\begin{center}
{\scriptsize
\begin{tabular}{r|r|r|r|r|r} %cc
$i$ & \multicolumn{1}{r|}{1} & \multicolumn{1}{r|}{2}   & $\dots$ & \multicolumn{1}{r|}{2258} & \\ % & \multicolumn{1}{c}{$MoE$}& \multicolumn{1}{c}{95\% CI}  \\
$s$  & $Y_1$  & $Y_2$   & $\dots$  & $Y_{2258}$  & $\overline{Y}_{2258}$ \\ % & $2\cdot\sqrt{\frac{\overline{Y}_{625}(1-\overline{Y}_{625})}{625}}$ & $\overline{Y}_{625} \pm MoE$ \\
\hline
1 & 37,006 & 108,811   & $\dots$  &  49,001  & 135,406   \\ %& \visible<2->{.037} & \visible<3->{[.643,.717]}\\
\visible<1->{2} & \visible<1->{?} & \visible<1->{?}   & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.037}  & \visible<3->{[.663,.737]}\\
\visible<1->{3} & \visible<1->{?} & \visible<1->{?}  & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.035} & \visible<3->{[.715,.785]}\\
\visible<1->{4} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\dots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} \\ %& \visible<2->{.036} & \visible<3->{[.694,.766]}\\
\visible<1->{5} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\dots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} \\ %& \visible<2->{.037} & \visible<3->{[.653,.727]}\\
\visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} \\ % & \visible<2->{$\vdots$} & \visible<3->{$\vdots$}  \\
\visible<1->{1 mil}  & \visible<1->{?} & \visible<1->{?} & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.035}& \visible<3->{[.705,.775]}\\
 \visible<1->{$\vdots$}  & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} \\ % & \visible<2->{$\vdots$} & \visible<3->{$\vdots$}\\
\hline
\visible<1->{$f_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{?}} & \multicolumn{1}{r|}{\visible<1->{?}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{?}} & \visible<1->{$N(\textcolor{red}{\mu},?)$} \\
\visible<1->{$E_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{$\mu$}} & \multicolumn{1}{r|}{\visible<1->{$\mu$}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{$\mu$}} & \visible<1->{\textcolor{red}{$\mu$}} \\
\visible<1->{$V_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}} & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}} & \visible<1->{?} \\
\end{tabular}}
\end{center}
\end{table}
```
## What is the $V[\overline{Y}_{n}]$?

```{=tex}
\begin{table}[h]
\begin{center}
{\scriptsize
\begin{tabular}{r|r|r|r|r|r} %cc
$i$ & \multicolumn{1}{r|}{1} & \multicolumn{1}{r|}{2}   & $\dots$ & \multicolumn{1}{r|}{2258} & \\ % & \multicolumn{1}{c}{$MoE$}& \multicolumn{1}{c}{95\% CI}  \\
$s$  & $Y_1$  & $Y_2$   & $\dots$  & $Y_{2258}$  & $\overline{Y}_{2258}$ \\ % & $2\cdot\sqrt{\frac{\overline{Y}_{625}(1-\overline{Y}_{625})}{625}}$ & $\overline{Y}_{625} \pm MoE$ \\
\hline
1 & 37,006 & 108,811   & $\dots$  &  49,001  & 135,406   \\ %& \visible<2->{.037} & \visible<3->{[.643,.717]}\\
\visible<1->{2} & \visible<1->{?} & \visible<1->{?}   & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.037}  & \visible<3->{[.663,.737]}\\
\visible<1->{3} & \visible<1->{?} & \visible<1->{?}  & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.035} & \visible<3->{[.715,.785]}\\
\visible<1->{4} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\dots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} \\ %& \visible<2->{.036} & \visible<3->{[.694,.766]}\\
\visible<1->{5} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\dots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} \\ %& \visible<2->{.037} & \visible<3->{[.653,.727]}\\
\visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} \\ % & \visible<2->{$\vdots$} & \visible<3->{$\vdots$}  \\
\visible<1->{1 mil}  & \visible<1->{?} & \visible<1->{?} & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.035}& \visible<3->{[.705,.775]}\\
 \visible<1->{$\vdots$}  & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} \\ % & \visible<2->{$\vdots$} & \visible<3->{$\vdots$}\\
\hline
\visible<1->{$f_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{?}} & \multicolumn{1}{r|}{\visible<1->{?}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{?}} & N(\textcolor{black}{$\mu$},\textcolor{red}{?}) \\
\visible<1->{$E_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{$\mu$}} & \multicolumn{1}{r|}{\visible<1->{$\mu$}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{$\mu$}} & $\mu$ \\
\visible<1->{$V_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}} & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}} & \visible<1->{\textcolor{red}{?}} \\
\end{tabular}}
\end{center}
\end{table}
```
## 

Property #2: The \textit{sampling variance} of the sample mean, $$V[\overline Y] = \frac{\sigma^2}{n}$$

Proof: \begin{align*}
V[\overline Y] &= V \left[ \left(  \frac{1}{n} Y_1 + ...  + \frac{1}{n} Y_n \right) \right] \\
&= \frac{1}{n^2}  V \left[ Y_1 + ...  + Y_n \right] \\
& =  \frac{1}{n^2}   \left( V[Y_1] + ...  + V[Y_n] \right) \\
& =  \frac{1}{n^2}   \left( V[Y] + ...  + V[Y] \right) \\
& =  \frac{1}{n^2}   n V[Y] \\
& =  \frac{\sigma^2}{n}  .
\end{align*}

## How much does $\overline{Y}_{2258}$ vary from sample to sample?

```{=tex}
\begin{table}[h]
\begin{center}
{\scriptsize
\begin{tabular}{r|r|r|r|r|r} %cc
$i$ & \multicolumn{1}{r|}{1} & \multicolumn{1}{r|}{2}   & $\dots$ & \multicolumn{1}{r|}{2258} & \\ % & \multicolumn{1}{c}{$MoE$}& \multicolumn{1}{c}{95\% CI}  \\
$s$  & $Y_1$  & $Y_2$   & $\dots$  & $Y_{2258}$  & $\overline{Y}_{2258}$ \\ % & $2\cdot\sqrt{\frac{\overline{Y}_{625}(1-\overline{Y}_{625})}{625}}$ & $\overline{Y}_{625} \pm MoE$ \\
\hline
1 & 37,006 & 108,811   & $\dots$  &  49,001  & 135,406   \\ %& \visible<2->{.037} & \visible<3->{[.643,.717]}\\
\visible<1->{2} & \visible<1->{?} & \visible<1->{?}   & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.037}  & \visible<3->{[.663,.737]}\\
\visible<1->{3} & \visible<1->{?} & \visible<1->{?}  & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.035} & \visible<3->{[.715,.785]}\\
\visible<1->{4} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\dots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} \\ %& \visible<2->{.036} & \visible<3->{[.694,.766]}\\
\visible<1->{5} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\dots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} \\ %& \visible<2->{.037} & \visible<3->{[.653,.727]}\\
\visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} \\ % & \visible<2->{$\vdots$} & \visible<3->{$\vdots$}  \\
\visible<1->{1 mil}  & \visible<1->{?} & \visible<1->{?} & \visible<1->{$\dots$}  & \visible<1->{?} & \visible<1->{?} \\ %& \visible<2->{.035}& \visible<3->{[.705,.775]}\\
 \visible<1->{$\vdots$}  & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} & \visible<1->{$\vdots$} & \visible<1->{$\vdots$}  & \visible<1->{$\vdots$} \\ % & \visible<2->{$\vdots$} & \visible<3->{$\vdots$}\\
\hline
\visible<1->{$f_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{?}} & \multicolumn{1}{r|}{\visible<1->{?}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{?}} &N(\textcolor{black}{$\mu$},\textcolor{red}{$\frac{\sigma^2}{n}$}) \\
\visible<1->{$E_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{$\mu$}} & \multicolumn{1}{r|}{\visible<1->{$\mu$}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{$\mu$}} & \visible<1->{$\mu$} \\
\visible<1->{$V_{\cdot}(\cdot)$} & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}} & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}}  &$\dots$ & \multicolumn{1}{r|}{\visible<1->{$\sigma^2$}} & \visible<1->{\textcolor{red}{$\frac{\sigma^2}{n}$}} \\
\end{tabular}}
\end{center}
\end{table}
```
## Facts about the sampling distribution of $\overline{Y}_n$

What we know about the sampling distribution of $\overline{Y}_n$:

```{=tex}
\begin{enumerate}
\item Approxiamtely normally distributed
\item Centered at $\mu$.
\item Variance of $\frac{\sigma^2}{n}$
\end{enumerate}
\bigskip
```
These facts imply that the middle 95% of the distribution lies approximately between $\mu - 1.96 \cdot \frac{\sigma}{\sqrt{n}}$ and $\mu + 1.96 \cdot \frac{\sigma}{\sqrt{n}}$. As long as $\sqrt{n}$ is big in relation to $\sigma$, $\overline{Y}_n$ will likely be close to $\mu$. \bigskip 

We still don't know:

```{=tex}
\begin{enumerate}
\item The value of $\mu$.
\item The value of $\sigma$.
\end{enumerate}
```
## Two Questions

```{=tex}
\begin{enumerate}
\item Is \$135,406 close to the population mean $\mu$? \pause Yes! \pause
\item Can we say something about how close? \pause Let's use a confidence interval
\end{enumerate}
```
