$$
\begin{aligned} 
\bar Y_{\with} &= \frac{1}{7} \sum_{i=1}^n 1(X_i=\with) Y_i \\
\bar Y_{\without} &= \frac{1}{3} \sum_{i=1}^n 1(X_i=\without) Y_i 
\end{aligned}
$$

## Iterated Means 
If we like, we can calculate means in two steps.
1. We can calculate means *within groups*.
2. We take a *group-size-weighted average* of them *across groups*.
This goes for both sample and population means.

:::: {.r-stack}



::: {.fragment .fade-out data-fragment-index="0"}
Suppose that in a sample of ten people and 7 have 4-year degrees. 
1. We calculate the mean income of our subsamples people with and without degrees.
$$
\begin{aligned} 
\bar Y_{\with} &= \frac{1}{7} \sum_{i=1}^n 1(X_i=\with) Y_i \\
\bar Y_{\without} &= \frac{1}{3} \sum_{i=1}^n 1(X_i=\without) Y_i 
\end{aligned}
$$
2. We take a weighted mean of these two averages.
$$
\begin{aligned} 
\bar Y &= \frac{7}{10} \bar Y_{\with} + \frac{3}{10} \bar Y_{\without} \\
       &= \frac{7}{10}\frac{1}{7}\sum_{i=1}^n 1_\with(X_i) Y_i + \frac{3}{10}\frac{1}{3}\sum_{i=1}^n 1_\without(X_i) Y_i \\
       &= \frac{1}{10} \sum_{i=1}^n 1_\with(X_i) Y_i + \frac{1}{10} 1_\without(X_i) Y_i \\
       &= \frac{1}{10} \sum_{i=1}^n \qty{ 1_\with(X_i) + 1_\without(X_i)} Y_i \\
       &= \frac{1}{10} \sum_{i=1}^n Y_i \\
\end{aligned}
$$
This gives us the mean of our whole sample.
:::

::: {.fragment .current-visible data-fragment-index="0"}
Suppose that in an infinite population, the probability of a person having a 4-year degree is 7/10.
1. We calculate the mean income of people with and without degrees.
$$
\begin{aligned} 
\mu_\with = \E[ Y \mid X_i=\with]    &= \\frac{1}{7} \sum_{i=1}^n 1(X_i=\with) Y_i \\
\mu_\without = \E[ Y \mid X_i=\without] &= \frac{1}{3} \sum_{i=1}^n 1(X_i=\without) Y_i 
\end{aligned}
$$



## The Indicator Trick

 - When we want to calculate the expectation of means in terms of *conditional means* use the law of iterated expectations, 
 the conditional expectation we get is a random variable. Like $\mu(X)=\E[Y \mid X]$.
   shows up. The random variable.
 - How do we make the *conditional expectation* for a fixed subpopulation,
    $\mu(x)=\E[Y \mid X=x]$, appear?
 - There's a trick to it. We multiply the conditional expectation by an indicator.
    - Let $1_x(X_i)$ be a random variable that's one when $X_i=x$ and zero otherwise.
    - If $\mu$ appears multiplied by this, it doesn't matter whether it's evaluated
      at the random variable $X_i$ or the constant $x$.

 $$
\mu(X_i)1_x(X_i) = \mu(x)1_x(X_i)
 $$
 


## The Indicator Trick

- When we're doing calculations, we often want to write *random values* of a function in terms of fixed values.
- There's a trick to it. To illustrate it, let's start with a dice analogy.
- Which do you prefer?
  1. Every time I roll a $5$, I pay you what I've rolled --- that many dollars. Otherwise, I pay you nothing.
  2. Every time I roll a $5$, I pay you five dollars. Otherwise, I pay you nothing.
- 
::: fragment
- They're the same. But they correspond to different mathematical formulas.
  1. The first is  $X_i 1_{x}(X_i)$.
  2. The second is 
  
   = x 1_{x}(X_i)$
2. $f(x)

It's the same.

:::
  

::: {.notes}

  - $\ind{x}(X_i)$ is an *indicator* that is 1 if $X_i=x$ and 0 otherwise.
  - More generally, $1_A(X_i)$ is in indicator that $X_i$ is in the set $A$.
  - In this case, we're talking about the set containing the single element $x$ 

:::