---
title: "QTM 220 Final Practice Problems"
format: pdf
editor: visual
---

\subsection*{Problem 1}

Suppose you have a sample $Y_1,Y_2...,Y_n$ drawn with replacement from a population with mean $\mu$ and standard deviation $\sigma$.

Consider the following estimator for $\mu$: $\tilde{Y} = \frac{1}{n+2}\sum_{i=1}^n Y_i$

\subsubsection*{Part A}

What is $E[\tilde{Y}]$?

\bigskip 

\color{red}

$$E[\tilde{Y}] = E[\frac{1}{n+2}\sum_{i=1}^n Y_i]$$
$$= \frac{1}{n+2} E[\sum_{i=1}^n Y_i]$$ 

$$= \frac{1}{n+2} \sum_{i=1}^n E[Y_i]$$ by linearity of expectations 

$$= \frac{1}{n+2} \sum_{i=1}^n E[Y]$$ by IID  

$$= \frac{1}{n+2} \sum_{i=1}^n \mu$$ by definition 

$$= \frac{1}{n+2} n \mu$$

$$= \frac{n}{n+2} \mu$$
\color{black}
\subsubsection*{Part B}

How does $E[\tilde{Y}]$ compare to $E[\bar{Y}]$? (where $\bar{Y} = \frac{1}{n}\sum_{i=1}^n Y_i$)

\bigskip 

\color{red} similar steps show that $E[\bar{Y}] = \mu$. $\bar{Y}$ is unbiased, $\tilde{Y}$ is biased, but $\lim_{n \rightarrow \infty} \frac{n}{n+2} =1$ so bias will decrease as $n$ increases. 

\color{black}

\subsubsection*{Part C}

Showing your work, calculate $Var[\tilde{Y}]$.

\bigskip 

\color{red}

$$Var[\tilde{Y}] = V[\frac{1}{n+2}\sum_{i=1}^n Y_i]$$

$$ = (\frac{1}{n+2})^2 V[\sum_{i=1}^n Y_i]$$

$$ = (\frac{1}{n+2})^2 \sum_{i=1}^n V[Y]$$ because IID, covariances are 0 

$$ = (\frac{1}{n+2})^2 \sum_{i=1}^n \sigma^2$$ by definition 

$$ = (\frac{1}{n+2})^2 n \sigma^2$$ 

$$ = \frac{n}{(n+2)^2} \sigma^2$$ 

\color{black}
\subsubsection*{Part D}

How does $Var[\tilde{Y}]$ compare to $Var[\bar{Y}]$?

\bigskip

\color{red}

Similar steps show that $V[\bar{Y}] = \frac{\sigma^2}{n}$

$\frac{1}{n} > \frac{n}{(n+2)^2}$ so our $\tilde{Y}$ estimator has a lower variance than the mean. But the estimator is biased, so we probably wouldn't want to use it over the mean. 

\color{black}

