---
title: "Problem Set 1"
subtitle: "QTM 220"
format: pdf
editor: visual

---


## Supreme Court Justices 
Load the provided dataset "EMdata.csv"
\begin{itemize}
\item This data is on 27 justices from the Warren (`53 - `69), Burger (`69 - `86), and Rehnquist (`86 - `05) courts
\item The data can be interpreted as a census for the 1953 - 2005 era.  
\item Variables: 
\begin{itemize}
    \item Justice: last name of Supreme Court Justice 
    \item CLlib: Percentage of votes in liberal direction for each justice in civil liberties cases
  \item party: Political party that nominated the justice (Republican =0, Democrat=1)
  \item ur: Justice is a member of an under-represented group, such as a racial or gender minority (under-represented group=1, not in under-represented group=0)
\end{itemize}
\end{itemize}


(a) Create a histogram of the percentage of liberal votes, visually identifying the mean and median. 
 

(b) Describe what the mean and median represent in the context of the CLlib variable for these justices. Which is larger? What does that imply in this context? 


(c) Write your own function to calculate the standard deviation of CLlib (i.e. not using "sd") and report it. Add a visual identification of a standard deviation on each side of the mean. 


(d) Calculate the mean of 'ur', whether a justice is a member of an under-represented group. What is the substantive interpretation of this mean? 


(e) Calculate the conditional means and medians of CLlib conditioning on nominating party. Create two histograms of CLlib, one for Republican-nominated justices, one for Democratic-nominated justices. What do the mean and median represent in the context of the CLib variable for the justices of each party? Which is larger, the mean among Republican justices or Democratic justices? Give a substantive interpretation of this.  Which is larger, the median among Republican justices or Democratic justices? Give a substantive interpreation of this. Which difference is larger? What does that mean? 


(f) Create a scatter plot of CLlib with the nominating party as the x-axis. Visually indicate the conditional means (conditioning on party) on the plot. 


(g) Using R's lm() function, regress CLlib on party. Using abline(), add the regression line to your scatterplot. What is substantive interpretation of the intercept and slope of the line in terms of justices for each party? 


(h) Calculate the conditional standard deviations of CLlib, conditioning on party. Add a visual represenatation of the conditional standard deviations to your scatterplot. 


(i) Create a scatterplot of justices with under-represented group membership as the y-axis and party as the x-axis. Add the conditional means and standard deviations to the plot (conditioning on party). Using lm(), regress under-represented group membership on party and add the regression line to your plot using abline(). What is the substantive interpretation of the intercept and slope of the line in terms of justices for each party?

## Matrix Algebra and Least Squares 

(a) Let $Y$ be the $n$x1 vector of our outcome variable and $X$ be the $n$x2 matrix that concatenates our independent variable of interest with a row of 1s. $\hat{\beta}$ is a 2x1 vector. 

$Y = \begin{bmatrix}
y_1 \\
y_2 \\
y_3 \\
 \vdots\\
 y_n
\end{bmatrix}$

$X = 
\begin{bmatrix}
1 & x_1 \\
1 & x_2 \\
1 & x_3 \\
\vdots &  \vdots\\
 1& x_n
\end{bmatrix}$

$\hat{\beta} = \begin{bmatrix}
\hat{\beta_0}\\
\hat{\beta_1}
\end{bmatrix}$


Define $r$ as the $n$x1 vector of residuals as given by $Y - X \hat{\beta}$

Using matrix algebra, show that $(Y-X\hat{\beta})' (Y-X\hat{\beta})$ yields the sum of squared residuals. 

\bigskip 

(b) Using matrix algebra and $\frac{\partial}{\partial \hat{\beta}}$, show that $\hat{\beta} = (X'X)^{-1}X'Y$ minimizes the sum of squared residuals (assuming that $X'X$ is invertible.)

(c) Let $Y = \begin{bmatrix}
1 \\
1 \\
0 \\
1
\end{bmatrix}$ 
and $X = 
\begin{bmatrix}
1 & 1 \\
1 & 0 \\
1 &0\\
 1& 1
\end{bmatrix}$

Using matrix algebra, calculate $(X'X)^{-1}X'Y$. 

\bigskip

(d) In R, create a dataframe $y= c(1,1,0,1)$ and $x = c(1,0,0,1)$. Calculate the conditional means of $y$ when $x=1$ and when $x=0$


(e) Using R's lm() function, regress $y$ on $x$. 