---
title: "Problem Set 5 "
subtitle: "QTM 220"
format: pdf
editor: visual
---

Due 3 November at 2:00pm ET on Canvas. Questions about submission requirements should be directed to your TA.

## Gerber, Green, and Larimer Michigan Voter Experiment

Prior to the August 2006 primary election in Michigan, political scientists Gerber, Green, and Larimer conducted a large field experiment in which different mailers were sent to registered voters across Michigan. Because whether or not someone votes (though not who they vote for) is public record, the researchers then accessed the public voting information to measure their outcome-- whether an individual voted in the August 2006 primary. The different treatments are as follows:

```{=tex}
\begin{itemize}
\item Civic Duty: do your civic duty and vote! 
\item Hawthorne: you are being studied + do your civic duty and vote! 
\item Self: who votes is public information, here is your recent voting record + do your civic duty and vote! 
\item Neighbors: what if your neighbors knew whether you voted? here is your recent voting record + your neighbors' recent voting record + do your civic duty and vote! 
\item Control: no mailer 
\end{itemize}
```
Households were randomized to receive a mailer (or not) and which type, but voting records are by individual.

The attached data from their experiment has the following variables:

```{=tex}
\begin{itemize}
\item hh\textunderscore id : the household id number 
\item hh\textunderscore size : number of adults in household 
\item sex : individual's sex according to voter record 
\item yob: individual's year of birth 
\item g2000 : whether or not the individual voted in the general election in 2000 
\item g2002 : whether or not the individual voted in the general election in 2002 
\item g2004 : whether or not the individual voted in the general election in 2004
\item p2000 : whether or not the individual voted in the primary election in 2000 
\item p2002 : whether or not the individual voted in the primary election in 2002 
\item p2004 : whether or not the individual voted in the primary election in 2004
\item treatment : the mailer that the household received (or Control for no mailer)
\item voted : whether the individual voted in the 2006 primary (outcome)
\end{itemize}
```
(a) Create a balance table showing the similarity of individuals assigned to treated and control across sex, age, household size, and turnout in previous elections.

(b) Create a balance table showing the similarity of individuals assigned to each level of treatment and control across sex, age, household size, and turnout in previous elections. Be sure to note how many individuals are in each level of treatment.

(c) Calculate the subsample 2006 primary turnout within each level of treatment (and control).

(d) Let's define the following treatment effects of interest: $\hat{\tau}(civic) = \hat{\mu}(civic) - \hat{\mu}(control)$, $\hat{\tau}(hawthorne) = \hat{\mu}(hawthorne) - \hat{\mu}(civic)$, $\hat{\tau}(self) = \hat{\mu}(self) - \hat{\mu}(hawthorne)$, $\hat{\tau}(neighbor) = \hat{\mu}(neighbor) - \hat{\mu}(self)$. Calculate each of these and interpret each in plain language.

(e) Create a bootstrap estimated sampling distribution for each of your $\tau$s and a 95% confidence interval for each.

(f) Create four dummy variables-- one for each treatment-- where an observation is coded as 1 if the household received that treatment and 0 otherwise (other treatment or control). Run an additive linear regression of 2006 primary vote on the four treatment variables. Report your results in a table and provide plain language interpretations of your estimates.

(g) Run an additive linear regression of 2006 primary vote on the four treatment variables and the pre-treatment turnout variables (i.e. general election voting in 2002 and 2000, primary election voting in 2004, 2002, and 2000). Report your results in a table (one table for both models is fine) and compare to your results in part (f).

(h) BONUS: Why might we be concerned about using individual turnout as the outcome for this experiment?

## Women's Health Initiative

```{r}
#| echo: false
# create data with treatment status, age, and breast cancer (0,1) 

#age<- c(rep("50-59",5520), rep("60-69",7509), rep("70-79",3579))
#treat<- c(rep(1,2837), rep(0,2683), rep(1,3854), rep(0,3655), rep(1,1815), rep(0,1764))

#breastcancer<- c(rep(1,55), rep(0,2782),rep(1,42),rep(0,2641), rep(1,97), rep(0,3757), rep(1,75),rep(0,3580),rep(1,54), rep(0,1761), rep(1,38), rep(0,1726))

#whi<- data.frame(treat=treat, age=age, breastcancer=breastcancer)
#write.csv(whi,"whidata.csv")

#whi<- read.csv("whidata.csv")
```

The data based on the CEE+MPA arm of the WHI trial can be found in whidata.csv and contains the following variables:

```{=tex}
\begin{itemize}
\item treat : binary indicating whether the participant received CEE+MPA or placebo 
\item age : the age group that the participant is in at the beginning of the trial 
\item breastcancer : binary indicating whether the participant developed invasive breast cancer during the trial 
\end{itemize}
```
(a) Create a balance table showing the number of participants assigned to CEE+MPA and placebo by age group. Why do randomized experiments report balance tables? What do you think of the balance on age in the WHI?

(b) Estimate the overall treatment effect (difference in proportions) of CEE+MPA on breast cancer and interpret your result.

(c) Create a bootstrap estimated sampling distribution of your treatment effect and report your 95\% confidence interval. Interpret your confidence interval.

(d) Estimate the treatment effect of CEE+MPA on breast cancer within each age group.

(e) Create a bootstrap estimated sampling distribution for the within-group treatment effects and report your 95\% confidence interval for each age group. Interpret.

(f) Using the 50-59 year olds as the reference category, run an additive linear regression with breast cancer as your outcome and treatment, 60-69 year olds, and 70-79 year olds as your regressors. Report your results in a table and interpret.

(g) Using the 50-59 year olds as the reference category, run an interactive linear regression with breast cancer as your outcome and treatment, 60-69 year olds, 70-79 year olds, 60-69 year olds \* treatment, and 70-79 year olds \* treatment as your regressors. Report your results in a table (you can use one table for both models) and interpret.

(h) Write the equations for each or your models using $\beta_i$s as your parameters. Fill in the following table using with the $\beta$s from your models (not numbers, for example $\beta_0 + \beta_1$.) Let $BC(T=1)-BC(T=0)$ be the difference in the proportion of those who developed invasive breast cancer that received treatment and control. Then fill in the table using the estimates from your models.

```{=tex}
\begin{table}
\caption*{Additive Regression }
\begin{tabular}{|c|c|c|c|c| }
\hline
 & Age Group & Prop. Breast Cancer T=1 & Prop. Breast Cancer T=0 & $BC(T=1)-BC(T=0)$ \\
\hline
$\beta$s & 50-59 & & & \\ 
 \hline
$\beta$s & 60-69 & & & \\
\hline
$\beta$s & 70-79 & & & \\
\hline 
numbers  & 50-59 & & & \\
 \hline
numbers & 60-69 & & & \\
\hline
numbers & 70-79 & & & \\
\hline 
\end{tabular}
\end{table}
```
\bigskip

```{=tex}
\begin{table}
\caption*{Interactive Regression }
\begin{tabular}{|c|c|c|c|c| }
\hline
 & Age Group & Prop. Breast Cancer T=1 & Prop. Breast Cancer T=0 & $BC(T=1)-BC(T=0)$ \\
\hline
$\beta$s & 50-59 & & & \\ 
 \hline
$\beta$s & 60-69 & & & \\
\hline
$\beta$s & 70-79 & & & \\
\hline 
numbers  & 50-59 & & & \\
 \hline
numbers & 60-69 & & & \\
\hline
numbers & 70-79 & & & \\
\hline 
\end{tabular}
\end{table}
```



(i) Compare the results from your models to the $\hat{ATE}$s by age group that you recovered in part (d).

\bigskip

Other WHI read + reflect?

## Dogs

The Giant Database of Dogs, a crowd-sourced dataset organized by Prof. Leanne Powner, includes the following variables:

```{=tex}
\begin{itemize}
\item Obs – unique observation number for case identification
\item Name – dog’s name as provided by the owner (excess text removed)
\item Gender – \{male, female\} closed choice
\item Fixed – “yes” if spayed or neutered, as appropriate; “no” if not
\item Color – respondents selected one from \{light brown, dark brown, black, white, reddish,
yellow/blond, no primary color, other\}. Other was not an open-ended response.
\item Heritage – 1 = single breed, 2 = designer/deliberate mix, 3 = mixed/unknown
\end{itemize}
```
Use dogs.csv for the following.

(a) Recode gender and fixed into numerical binary variables. Regress dog's weight on gender and fixed. Report your results in a table.

(b) Create a scatter plot with weight on the y-axis, fixed on the x-axis, and use different colors for male and female dogs (include a legend).

(c) Regress dog's weight on gender, fixed, and gender\*fixed. Report your results in a table (one table for both models is fine).

(d) Write the equations for each or your models using $\beta_i$s as your parameters. Fill in the following table using with the $\beta$s from your models (not numbers, for example $\beta_0 + \beta_1$.)

```{=tex}
\begin{table}[H]
\caption*{Weight: Additive Model $\beta$s}
\begin{tabular}{c | c | c |}
& Male & Female \\
\hline
Fixed & & \\
\hline
Not Fixed & & \\
\hline 
\end{tabular}
\end{table}
```
```{=tex}
\begin{table}[H]
\caption*{Weight: Interactive Model $\beta$s}
\begin{tabular}{c | c | c |}
& Male & Female \\
\hline
Fixed & & \\
\hline
Not Fixed & & \\
\hline 
\end{tabular}
\end{table}
```
(e) Fill in the table using the estimates from your models.

```{=tex}
\begin{table}[H]
\caption*{Weight: Additive Model Estimates}
\begin{tabular}{c | c | c |}
& Male & Female \\
\hline
Fixed & & \\
\hline
Not Fixed & & \\
\hline 
\end{tabular}
\end{table}
```
```{=tex}
\begin{table}[H]
\caption*{Weight: Interactive Model Estimates}
\begin{tabular}{c | c | c |}
& Male & Female \\
\hline
Fixed & & \\
\hline
Not Fixed & & \\
\hline 
\end{tabular}
\end{table}
```
(g) Calculate the subsample mean weights among fixed females, unfixed females, fixed males, and unfixed males. Compare your results to your additive and interactive tables of predicted weights.
