---
title: "220 Quiz 2"
format: pdf
editor: visual
---
## Question 1 
To estimate the average weight of all Chihuahuas, we took a random sample with replacement of 1,000 Chihuahuas from around the world, weighed them, and calculated the average weight to be 3.9 pounds. Using what we learned from QTM 220 when we don't have the population data, we report a 95% confidence interval of [3.6, 4.2]. In one to two sentences, write an interpretation of this interval. 


\vspace{3cm}

## Question 2 
A D-20 is a 20-sided die with the whole numbers 1 to 20 on each face, each of which is equally likely to be rolled. You roll the die repeatedly and record the number you roll each time. 

\begin{enumerate}
\item Write out the probability mass function of this experiment. 

\vspace{3cm}

\item What is the expectation of a roll? 

\end{enumerate}

\newpage 

## Question 3 
Below is a proof using properties/rules of expectations. Select the correct rule being used at each point. 

For a sample $Y$ randomly drawn from a population with mean $\mu$, the sample mean is an unbiased estimator for the population mean: $E[\bar{Y}] = \mu$ 

\begin{tabular}{l l }

$\bar{Y} = \sum_{i=1}^N Y_i$ & definition of sample mean\\
& \\
$E[\bar{Y}] = E[\sum_{i=1}^N Y_i]$ & take expectation of estimator\\
& \\
$ \frac{1}{n} E[ \sum_{i=1}^N Y_i]$ &  (a) Constant Rule \\
 & (b) Linearity of Expectations \\
 & (c) Irrelevant Conditioning \\
 & (d) Law of Iterated Expectations \\
$ \frac{1}{n} E[ Y_1 + Y_2 + Y_3 + ... + Y_n]$ & \\
& \\
$ \frac{1}{n}( E[ Y_1] + E[Y_2] + E[Y_3] + ... + E[Y_n])$ &  (a) Constant Rule \\
 & (b) Linearity of Expectations \\
 & (c) Irrelevant Conditioning \\
 & (d) Law of Iterated Expectations \\
 & \\
$\frac{1}{n}( E[ Y] + E[Y] + E[Y] + ... + E[Y])$ (n times) & Y's are IID\\
& \\
$ \frac{1}{n}(\mu + \mu + \mu + ... + \mu)$ (n times) & by definition \\
& \\
$\frac{1}{n} \sum_{i=1}^n \mu$ & \\ 
& \\
$\frac{1}{n} n\mu$ & \\ 
& \\
$=\mu$ & \\

\end{tabular}
